<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Umum</name>
   <tag></tag>
   <elementGuidId>e1f248b3-602b-4f7b-b2c4-04590bc53b5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Category1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Category1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3f21702-295d-4c85-9166-13518ec1f983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notif-group-option</value>
      <webElementGuid>129dbcca-9a32-4ed0-9b69-cdeed1ff9d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Category1</value>
      <webElementGuid>349b48e7-46fe-44f0-8162-58605b3746db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Umum
                        21
                    </value>
      <webElementGuid>90857b14-57f7-45a9-b627-ec9f2d54843a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Category1&quot;)</value>
      <webElementGuid>8d7c1629-9c5d-447f-b053-940e122c0933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Category1']</value>
      <webElementGuid>bc9f3c2d-b523-4624-9064-22662302fcb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CategoryList']/div[2]</value>
      <webElementGuid>5b18e808-e2c8-4732-be78-01398747612c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Notifikasi'])[1]/following::div[2]</value>
      <webElementGuid>ea6285e4-f8ee-4743-939e-da727c01dec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[1]/following::div[5]</value>
      <webElementGuid>b997bae0-3f41-4168-af41-06a269821177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Big Fleets - Shipper'])[1]/preceding::div[2]</value>
      <webElementGuid>94bca8e5-0fff-4073-b8cb-df850269efaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>c2b62dcc-be50-4ad6-9343-a579585ef072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Category1' and (text() = '
                        Umum
                        21
                    ' or . = '
                        Umum
                        21
                    ')]</value>
      <webElementGuid>8ed34f86-fa60-48d4-9292-d1775bcbea3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
