<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__component-input-border lh-normal _d99f6c</name>
   <tag></tag>
   <elementGuidId>3fee828a-d976-40a7-8af6-225dbd76627d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.component-input-border.lh-normal.fc-1b.ff-medium</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>28f0c235-8333-465d-93bf-e2c0cd19cc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>component-input-border lh-normal fc-1b ff-medium</value>
      <webElementGuid>1188a6ed-43f7-489b-98d2-df22f8879853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93a0d20a-6ce8-4050-83a2-f11833a5a517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan lokasi harga berlaku</value>
      <webElementGuid>ba9180c8-f52c-4421-ba61-687a42988957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>lokasi_harga</value>
      <webElementGuid>72dd23e9-79fa-4766-8d28-20066a8c33d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_harga_berlaku_pada_lokasi</value>
      <webElementGuid>ebc0e56e-26a3-4365-945c-6a2e9741c599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_harga_berlaku_pada_lokasi</value>
      <webElementGuid>cccc8077-0b0d-4041-9b67-d977f62e7760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_harga_berlaku_pada_lokasi</value>
      <webElementGuid>e1e37afe-6a3e-4113-99c8-373cadd8d7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_harga_berlaku_pada_lokasi</value>
      <webElementGuid>110bd829-3ef4-429d-bc40-d72d5beb880c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_harga_berlaku_pada_lokasi</value>
      <webElementGuid>1d3280d3-afd0-4473-bad4-fbf8adf512f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_harga_berlaku_pada_lokasi</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 100</value>
      <webElementGuid>99aa9481-9698-4a96-ba41-a4594229d884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_value_harga</name>
      <type>Main</type>
      <value>Maksimal harga adalah Rp9.999.999.999.999</value>
      <webElementGuid>df2fbecb-0fbe-4521-a8fb-84cdf475451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_harga_berlaku_pada_lokasi</name>
      <type>Main</type>
      <value>Minimal karakter adalah 1</value>
      <webElementGuid>9039bf8e-c1f4-4266-8564-27daf10001af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_value_harga</name>
      <type>Main</type>
      <value>Minimal harga adalah Rp1</value>
      <webElementGuid>57cfee93-cc9a-40b9-ba3c-9dc541880839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>77e467d5-cb2c-4747-953c-489daa7a230e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_harga_berlaku_pada_lokasi</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>94cd03af-e528-418f-a65d-e2754d60675e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_harga_berlaku_pada_lokasi</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>70064e36-b395-49ab-a72c-570fcfddaeef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_value_harga</name>
      <type>Main</type>
      <value>9999999999999</value>
      <webElementGuid>3eecdc70-ed78-4f3e-b17c-8361a098bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_harga_berlaku_pada_lokasi</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b3efbb64-f1b5-4ea8-845c-24b3e7c86746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_value_harga</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>db0f1389-cdf1-4fff-a85d-02279c8516ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField component-262 no-border widget&quot;]/div[@class=&quot;fs-12&quot;]/textarea[@class=&quot;component-input-border lh-normal fc-1b ff-medium&quot;]</value>
      <webElementGuid>7d244216-f7d1-4669-b900-4457538d9a1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[2]</value>
      <webElementGuid>57a9345a-910d-407f-bbfa-ffe69ab4c09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[11]/div[2]/div[4]/textarea</value>
      <webElementGuid>2d65e871-78c7-40e0-b5b4-b320818c54f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>9b7ba123-a55e-4c90-8d53-26f9270ba606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @placeholder = 'Masukkan lokasi harga berlaku']</value>
      <webElementGuid>e0dde62a-3868-4148-aec5-40de9d1b2c0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
