<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_btn--icon btn--no-text font-i_19de8c</name>
   <tag></tag>
   <elementGuidId>76d83ad9-608a-4dfa-8929-fd5d680babda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Form_EditForm_users&quot;]/div[1]/div/div/div/div/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn--icon.btn--no-text.font-icon-caret-down-two.search-box__filter-trigger.collapsed.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c82fb945-295d-41c7-9349-7b19a93d26a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ed7718c-45b3-4be0-9e0c-38a7dbd4312b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>612c3941-55c2-4d1f-b356-92058ff428e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advanced</value>
      <webElementGuid>916e8448-ead6-4f77-b748-589875e95381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn--icon btn--no-text font-icon-caret-down-two search-box__filter-trigger collapsed btn btn-secondary</value>
      <webElementGuid>3aae6d60-76c9-4efc-accd-529059fd0461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advanced</value>
      <webElementGuid>d3afa4cf-9671-42e3-ae4d-ca7f8136a0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form_EditForm_users&quot;)/div[@class=&quot;search-holder grid-field__search-holder&quot;]/div[@class=&quot;search&quot;]/div[@class=&quot;search-box search-box--hideable search-box--has-not-focus search-box--has-filters&quot;]/div[1]/div[@class=&quot;search-box__group&quot;]/button[@class=&quot;btn--icon btn--no-text font-icon-caret-down-two search-box__filter-trigger collapsed btn btn-secondary&quot;]</value>
      <webElementGuid>7ad84419-fde1-4a85-aa12-92b9f074024e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>e1a0420d-c6da-42bd-8a5f-3c44378f217f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='Form_EditForm_users']/div/div/div/div/div/button</value>
      <webElementGuid>d1f2bfd0-1a0c-4f6b-858b-3df0d14b0ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/button</value>
      <webElementGuid>a08b5d63-7a77-46e9-9f93-378dc6ddb282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Advanced']</value>
      <webElementGuid>adc96325-75e3-46bd-8e4a-afa49279ccd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
