<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_Search__Phone</name>
   <tag></tag>
   <elementGuidId>db944bad-1411-4a0d-a968-b82d8a1e2ea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Form_UserssSearchForm_Search_Phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Form_UserssSearchForm_Search_Phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e10e64ec-d655-48d0-bb4f-3d869e54310b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form_UserssSearchForm_Search_Phone</value>
      <webElementGuid>f5da3319-b586-4ba6-8a9f-a63482e87e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search__Phone</value>
      <webElementGuid>4843ae42-0807-47d7-b68c-bd48ce62dcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>71e26745-8b30-4957-8649-98f253e4af42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79716089-ce23-4f64-80c3-4b021d525b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> text stacked form-control</value>
      <webElementGuid>489b0186-6995-4f55-8f5d-f2d6424f8240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form_UserssSearchForm_Search_Phone&quot;)</value>
      <webElementGuid>167a1170-9d86-41ec-a1ac-4792b4715781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Form_UserssSearchForm_Search_Phone']</value>
      <webElementGuid>b7dac3cc-fbc8-40a8-858a-65fcb8c2811d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Form_UserssSearchForm_Search_Phone_Holder']/div/input</value>
      <webElementGuid>8dca032c-1cdc-42e5-842b-c6db0c525386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a53eb1e8-5180-46ce-b80f-8ee525341bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Form_UserssSearchForm_Search_Phone' and @name = 'Search__Phone' and @type = 'text']</value>
      <webElementGuid>c37faa8b-2263-489b-878d-54ef2cab8908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
