<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kec. Seputih Surabaya, Kab. Lampung Tengah</name>
   <tag></tag>
   <elementGuidId>f2eea58b-309e-4fff-b15e-bb5e689e0369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div/div[5]/div[1]/div[2]/div[2]/div[15]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ff-medium.fc-1B.fs-12.mt-8.click-location-dropdownGoogle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>730a46d1-109f-4984-9c2b-3db367a85b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Kec. Seputih Surabaya, Kab. Lampung Tengah</value>
      <webElementGuid>ecea82e3-44f1-446c-8c84-0cd95d4983b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle</value>
      <webElementGuid>5a008395-dc7e-4ce6-9f0f-c52ec0f92bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kec. Seputih Surabaya, Kab. Lampung Tengah</value>
      <webElementGuid>88bbe16c-cfef-4776-bafa-7b39f9dd3ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;parentDropdownGoogle d-flex flex-column&quot;]/div[@class=&quot;bg-white resultDropdown&quot;]/div[@class=&quot;ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle&quot;]</value>
      <webElementGuid>c02201b2-43fd-4452-8177-10019110ec91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[15]/div/div[3]/div</value>
      <webElementGuid>a9787234-e8ee-44d1-b12d-33a167ee5631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::div[3]</value>
      <webElementGuid>bc7f7b1f-0ca2-4fb5-9b3e-029ed81d85b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kec. Seputih']/parent::*</value>
      <webElementGuid>1fd388d8-4a85-4eb1-bd5e-6d3abfdb8355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[3]/div</value>
      <webElementGuid>610e2b0e-14e5-4708-a2d5-1f74b2dab7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kec. Seputih Surabaya, Kab. Lampung Tengah' or . = 'Kec. Seputih Surabaya, Kab. Lampung Tengah')]</value>
      <webElementGuid>3051b700-684c-4c1b-b4b2-9de23fd7b9a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
