<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kec. Seputih Surabaya, Kab. Lampung Tengah</name>
   <tag></tag>
   <elementGuidId>f2eea58b-309e-4fff-b15e-bb5e689e0369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PasangIklanForm']/div[15]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ff-medium.fc-1B.fs-12.mt-8.click-location-dropdownGoogle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>24f9584e-c866-4b06-b436-5538d9a5eeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Kec. Seputih Surabaya, Kab. Lampung Tengah</value>
      <webElementGuid>c57c98a3-771d-4a53-838e-ae7c5af6d6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle</value>
      <webElementGuid>a5532b53-ace6-4efb-adf9-dbd543aa1a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kec. Seputih Surabaya, Kab. Lampung Tengah</value>
      <webElementGuid>1bf318d3-eb21-4ae3-b3fd-5113dd52e83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;parentDropdownGoogle d-flex flex-column&quot;]/div[@class=&quot;bg-white resultDropdown&quot;]/div[@class=&quot;ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle&quot;]</value>
      <webElementGuid>92fceaa2-3da9-4122-809c-b492e2148d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[15]/div/div[3]/div</value>
      <webElementGuid>df0309cc-1491-41f9-8c83-377b7d3327e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::div[3]</value>
      <webElementGuid>74028b48-9b5e-44b0-87aa-b9714b0cf8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kec. Seputih']/parent::*</value>
      <webElementGuid>780add0d-b533-493a-b53f-63f71342e800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[3]/div</value>
      <webElementGuid>411bbd10-8ec9-4f4f-bb54-faac63f2875c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kec. Seputih Surabaya, Kab. Lampung Tengah' or . = 'Kec. Seputih Surabaya, Kab. Lampung Tengah')]</value>
      <webElementGuid>3a285323-197b-4f2a-92cc-81935a266e0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
