<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_FormatInteger</name>
   <tag></tag>
   <elementGuidId>9b58f9bc-6008-420b-9413-7635be0fc718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div/div[5]/div[1]/div[2]/div[2]/div[13]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>108a1337-5434-465c-868e-d6bf0a1c2852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormatInteger</value>
      <webElementGuid>9fdb32d8-04de-419e-8d6f-c3275b174e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c90a15d-2cac-4324-b5c4-41b88db833b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Harga</value>
      <webElementGuid>db2175d2-ff5c-4743-b080-b9604c7ff9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>Harga</value>
      <webElementGuid>4b70e88a-313d-4adf-ace8-d7322f5d4129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_value</name>
      <type>Main</type>
      <value>Maksimal Harag Melebihi Bats Ketentuan!</value>
      <webElementGuid>5385b010-3a95-4e70-8a6d-1b8a40ce63c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_value</name>
      <type>Main</type>
      <value>Harga Tidak Boleh Kurang Dari 0!</value>
      <webElementGuid>126899ad-0a6d-48c8-9baa-d54bde3da6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_value</name>
      <type>Main</type>
      <value>9999999999999</value>
      <webElementGuid>fa6cb2f0-0eff-4f72-b137-9861476c7fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d4c2b20-b471-4379-95c3-b306ac872fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12 component-262 component-input-border-container&quot;]/input[@class=&quot;FormatInteger&quot;]</value>
      <webElementGuid>66a5a511-2ec5-4d8e-8b8a-d555e001fd06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[9]</value>
      <webElementGuid>1caf3882-aff6-483f-ada2-b011cc74fa2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[13]/div[2]/input</value>
      <webElementGuid>361a1f88-9b96-4b3f-b307-cb7e048a95fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/input</value>
      <webElementGuid>eabf66c1-f762-457f-a424-e0ecf40e6029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Harga']</value>
      <webElementGuid>d50f2258-01f0-4e2e-a39b-731d8f1c62c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
