<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__FormatInteger</name>
   <tag></tag>
   <elementGuidId>c06de1a6-9b02-419e-86ef-dfc97c64f164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.FormatInteger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46519d25-9a5a-466c-a0f7-a43a2760dc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormatInteger</value>
      <webElementGuid>cb3dd4eb-b145-49e4-bdb3-14eeed102696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15e354ad-e924-43d1-b6bd-a061bca1bf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jarak Tempuh</value>
      <webElementGuid>53540941-fa69-4fb9-b1ae-63bec89faa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>JarakTempuh</value>
      <webElementGuid>6733d755-9b6b-4736-92f9-8397048adc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_value</name>
      <type>Main</type>
      <value>Jarak tempuh melebihi batas ketentuan!</value>
      <webElementGuid>aa613a0b-d755-420f-8ef8-427a77eca4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_value</name>
      <type>Main</type>
      <value>Jarak tempuh tidak boleh dibawah ketentuan!</value>
      <webElementGuid>4a2a9e23-a5c3-4367-b91a-62d03c53aff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Anda belum memasukkan jarak tempuh!</value>
      <webElementGuid>c29deb02-a706-4e00-8d08-c7f1a67256d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_value</name>
      <type>Main</type>
      <value>9999999999999</value>
      <webElementGuid>fb8cb88e-8015-4adf-8ae0-0ef0c30a2789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3a86d0c4-d87a-44ce-91d7-0d4cd2913652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12 component-262 component-input-border-container&quot;]/input[@class=&quot;FormatInteger&quot;]</value>
      <webElementGuid>d1754d86-797c-48b1-b4d6-5f7116659a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>91388ba3-1abf-48e1-9913-0538ceac0d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[4]/div[2]/input</value>
      <webElementGuid>daeeef92-09f3-42a0-86c2-abfe70804d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>1d06af76-0a6f-4386-8cdc-5e841fb4fab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Jarak Tempuh']</value>
      <webElementGuid>f9f513a5-2f55-46f6-bb1d-49f632c34231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
