<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jenis Truk - Carrier_1</name>
   <tag></tag>
   <elementGuidId>4f8eb4b3-34cf-487e-9ef6-c40067eb3f9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div/div[5]/div[1]/div[2]/div[2]/div[5]/div[2]/div[2]/span/span[1]/span/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection__placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e051e9e-31d8-4a62-ba89-d5fdf258fe4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>f519dde3-e448-4c4c-9c73-4a85c86c303c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jenis Truk - Carrier</value>
      <webElementGuid>48ff7be1-51fc-4e96-bb16-04fa3759149c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-9l4g-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>fc259255-61d7-49de-bf64-ab5f8a4b7e9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-9l4g-container']/span</value>
      <webElementGuid>035d93f1-a4f2-4a40-a071-2f90513aef11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Truk Lainnya'])[1]/following::span[5]</value>
      <webElementGuid>8595070b-e2f1-45ae-9c5e-4988c917b3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colt Diesel Double'])[2]/following::span[7]</value>
      <webElementGuid>8f8bccd9-abd0-43a9-9e8d-42596bc0e84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Carrier Lainnya'])[1]/preceding::span[3]</value>
      <webElementGuid>9899b7ed-059b-4728-b2ef-728d5d5cafd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>2ae29499-faf7-41ec-9410-3c79912dffa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Jenis Truk - Carrier' or . = 'Jenis Truk - Carrier')]</value>
      <webElementGuid>fa2e5cb9-c323-4257-aecd-d9aff241eb4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
