<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__unchecked-icon</name>
   <tag></tag>
   <elementGuidId>c5a45cd0-d8e2-4172-992a-d9ba9d52d575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.unchecked-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PasangIklanForm']/div[7]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c2b15b8-7eae-44f9-b0b5-3861d930e339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unchecked-icon</value>
      <webElementGuid>ca42e05b-d3cb-4674-a8ca-91d518d751cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12  mt-8 row mx-0 no-border&quot;]/div[@class=&quot;CheckBoxButtonItem col-6 d-flex align-items-center px-0&quot;]/div[@class=&quot;d-flex align-items-start mr-12&quot;]/div[@class=&quot;checked-container mr-12&quot;]/div[@class=&quot;unchecked-icon&quot;]</value>
      <webElementGuid>621b473c-c867-4ef2-8234-d5758264f5e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[7]/div[2]/div/div/div/div</value>
      <webElementGuid>cad75809-62ee-4cc9-9b65-e6d942a4ae35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/div</value>
      <webElementGuid>9f29324b-e906-438a-b206-0aff78dddf71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
