<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pencapaian, Penghargaan, dan Ser_d3ca56</name>
   <tag></tag>
   <elementGuidId>0fa8fd9e-e68f-478d-84c3-7832ce8e6ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.component-input-border-container.mb-8 > input.no-border.fs-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cae52584-ad0e-412d-a98e-8fdcef532a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12</value>
      <webElementGuid>7ab0009a-e105-4e0e-808f-e0ad20ee5e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85e874bd-fc21-41cd-9187-a9d5838b9df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Caption</value>
      <webElementGuid>528b9890-a975-4778-8b05-2456d7edc91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_sertifikat</value>
      <webElementGuid>9841a807-b482-4fce-8c63-5eea2f2ab188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_sertifikat</value>
      <webElementGuid>983e8937-75ac-4620-9914-7f4e0b27ca4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_sertifikat</value>
      <webElementGuid>774d6dd4-82d8-4d18-8bd9-2fb10052456f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_sertifikat</value>
      <webElementGuid>8ecda739-793b-4b91-b687-3f4aa5363b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_sertifikat</value>
      <webElementGuid>b4d85f7b-ec2a-4e4e-ac31-e486012bc2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2df9220c-cdfe-4bbe-a4fb-fc81032bb508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>9b832fb7-3c96-4722-b301-94555a4f6a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>Format file tidak sesuai</value>
      <webElementGuid>9199f893-2485-4375-905d-044c5d667537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_sertifikat</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 100</value>
      <webElementGuid>007cae83-0cae-43f2-bf2f-1f0bf690fe79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>Ukuran file melebihi batas 5MB</value>
      <webElementGuid>494b44c6-1fd6-424b-980e-42c9f7f4d9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_sertifikat</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>ae73a4ca-8168-4f85-a24a-a7d4a52677a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG, WEBP, SVG</value>
      <webElementGuid>646de5bb-ce56-4fd6-8da3-1049dd6bd737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_sertifikat</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>50a316ae-7449-46c1-8461-ebf5b716c4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_sertifikat</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>26424590-3dc3-49ff-a827-1865fa97e61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c3868950-5c01-441e-b944-ae135a9c4035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_sertifikat</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b9f815c3-0f4a-4594-9603-f6e8b914f666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;div-grow&quot;]/div[@class=&quot;d-flex component-input-border-container mb-8&quot;]/input[@class=&quot;no-border fs-12&quot;]</value>
      <webElementGuid>3332c007-6777-48b1-b87d-40005bcda7ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[9]</value>
      <webElementGuid>47aeb195-2f48-4f4a-bc5f-616f4cc28e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[13]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>9f77b4ef-68e3-4d7d-8ff1-38d28ac11176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>33a55230-499f-4f7b-9745-e47ff50fefcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Caption']</value>
      <webElementGuid>90e67f7f-ee23-4223-a0d9-fb1d0b2c1efd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
