<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_max_capacity</name>
   <tag></tag>
   <elementGuidId>ea635fe8-c214-47e8-a830-78fd0a1a8596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max_capacity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#max_capacity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b3590d4-52cc-4455-b1b9-28f0595c49d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87eab904-728d-4d5c-8cea-1fd229af5980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2d08c6a4-9bd0-4641-8bc5-a254e60d110f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-input-form ml-14 mr-8 formatMaxKapasitas satuan_berat_dimensi</value>
      <webElementGuid>c11df810-903f-43d0-b511-05a86652c128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>max_capacity</value>
      <webElementGuid>acf2894d-4305-473c-940f-80825d8b8c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max_capacity</value>
      <webElementGuid>dd3a53ac-e6ce-4a19-b4a9-86b9ad1232fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max_capacity&quot;)</value>
      <webElementGuid>097a7f4e-cbda-4a22-8003-71c9c56a2694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max_capacity']</value>
      <webElementGuid>01a48cf1-1803-43ce-8af5-0fd2857f9491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-create-armada']/div/div/div/table/tbody/tr[5]/td[2]/input[3]</value>
      <webElementGuid>2c8b640c-8cfa-4a13-ae9a-3d916c5dc929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>dc026751-63e5-4041-8b2d-ed433e5cd8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '0' and @name = 'max_capacity' and @id = 'max_capacity']</value>
      <webElementGuid>fc52b01b-48d6-46f2-bcd7-a4f5eb0dfff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
