<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Unit_truck_qty</name>
   <tag></tag>
   <elementGuidId>de904b2c-a2ea-42c9-89d2-4ae571a42857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='truck_qty']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#truck_qty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a84a7a66-b30b-42bb-9729-268ee8f23283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b955613-0d55-4833-8581-fc59e9f1ffd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh : 50 </value>
      <webElementGuid>8c2e452b-39ce-40a9-adb2-ca3e44096862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>58aab91f-5c73-41b1-b38a-6291ef440440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-input-form mr-12 hanya_angka number harga</value>
      <webElementGuid>3d79db41-8b27-42e0-8b42-8589e93ae305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>truck_qty</value>
      <webElementGuid>bf0a7cf9-e65c-4ce3-a1ae-7b60e6aedb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>truck_qty</value>
      <webElementGuid>14f67c9c-9ee2-4c05-820f-06b79c626a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;truck_qty&quot;)</value>
      <webElementGuid>3636fa00-90cd-459c-95e1-cd215e349634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='truck_qty']</value>
      <webElementGuid>796d1ac0-1fad-4326-9a86-1bb2b748ce46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-create-armada']/div/div/div/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>158b4e37-279d-4469-bcf9-7003c9264be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>af520e2d-d175-47fd-9630-e623cd2b1225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Contoh : 50 ' and @name = 'truck_qty' and @id = 'truck_qty']</value>
      <webElementGuid>65fae5d6-f3ec-44f5-8ea7-ac7b5ef27488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
