<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Watchlist</name>
   <tag></tag>
   <elementGuidId>ff716ef1-2716-4fbc-95ab-380f07e1d439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-watchlist > a.text-tab-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-watchlist']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>472a9006-1069-457c-bffe-d4743c90277d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-tab-header</value>
      <webElementGuid>0ac7cea7-b25c-4554-9fd5-483c79260ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://bf.azlogistik.id/shipper-menu/watchlist</value>
      <webElementGuid>bb365ea0-9fee-48b4-af64-85ca0e9c04b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watchlist</value>
      <webElementGuid>59bc096e-3363-485a-b670-45ad7d94077f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-watchlist&quot;)/a[@class=&quot;text-tab-header&quot;]</value>
      <webElementGuid>12cca341-9441-478c-bb99-aac61fe34387</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-watchlist']/a</value>
      <webElementGuid>c592a0cf-b445-420c-b50c-33e6c9de84b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Watchlist')]</value>
      <webElementGuid>33bbda3a-73a7-45b7-a923-121ec5474287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trial 7 Days'])[1]/following::a[2]</value>
      <webElementGuid>0b059b6f-7e18-429b-beba-61be43f65418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::a[2]</value>
      <webElementGuid>f68358bc-5ed5-4b0b-aff9-36c6cf9853f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan'])[1]/preceding::a[1]</value>
      <webElementGuid>1f360051-da31-4d79-b295-ebf5c7af8e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/preceding::a[1]</value>
      <webElementGuid>ae024e3b-2396-47fd-893c-a02caabd8208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Watchlist']/parent::*</value>
      <webElementGuid>0836cd70-ade0-4fb0-89f5-81618e6ed369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://bf.azlogistik.id/shipper-menu/watchlist')]</value>
      <webElementGuid>080c7401-b981-4c47-9b6e-c3221aae8355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>3252df09-198e-4ecf-b709-b18ec1f7a6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://bf.azlogistik.id/shipper-menu/watchlist' and (text() = 'Watchlist' or . = 'Watchlist')]</value>
      <webElementGuid>8c4e1b55-5c10-48f8-858f-7af252b028c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
