<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_layanan_container-sales</name>
   <tag></tag>
   <elementGuidId>6c3d1ecc-3393-4a94-a5d8-f25c1510def9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[1]/div/div[5]/div[1]/div[2]/div[2]/div[8]/div[2]/div[1]/div[1]/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
