<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Browse File</name>
   <tag></tag>
   <elementGuidId>449019d2-0ee4-4e58-98ed-55db6dcabc18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addUpload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addUpload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7024c5a6-bc41-47df-84be-19115edefe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addUpload</value>
      <webElementGuid>291c8e4a-7c09-44a7-89c1-7070950e716b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-12-az ff-demi-az fc-1b-az</value>
      <webElementGuid>ddd65356-a205-4bf7-a8b2-ede898d7ab3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>upfileFotoVideo()</value>
      <webElementGuid>c297850e-7cab-424d-810b-f982ad9208b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Browse File
                        </value>
      <webElementGuid>912fb063-a4fb-4902-b359-1b47abecdf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addUpload&quot;)</value>
      <webElementGuid>fdcb3b02-400c-4e72-a17d-4ab51da272cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addUpload']</value>
      <webElementGuid>66e94ae2-e903-4c1b-b628-26ffc2d1fbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalBox']/div/div/div[2]/div[6]/div[2]/a</value>
      <webElementGuid>339c67e0-9a62-4a6a-8bf6-b72afb7f8e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Browse File')]</value>
      <webElementGuid>9604e7c0-a282-4073-bf3c-f378958d4a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Darurat'])[1]/following::a[1]</value>
      <webElementGuid>ca3bca58-70e7-461c-9215-8c068a56dd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/preceding::a[1]</value>
      <webElementGuid>19f1c6f4-0f16-4e97-9931-f114b0f02fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Browse File']/parent::*</value>
      <webElementGuid>2898e027-a6fa-41ee-89e6-3a06b4316157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/a</value>
      <webElementGuid>d329ce11-14a8-4ea1-a5cc-051d7c83af81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addUpload' and (text() = '
                            Browse File
                        ' or . = '
                            Browse File
                        ')]</value>
      <webElementGuid>f128cdca-e65f-46c8-ac5f-fa5c0897c596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
