<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download Template File</name>
   <tag></tag>
   <elementGuidId>336e79e4-49d3-4584-84b4-946dd4159c3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnLihatContohSuratJalan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3330811a-d487-422e-afed-52f05927162e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnLihatContohSuratJalan</value>
      <webElementGuid>95496cdb-7cfc-4c7f-976d-77547a368a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-nowrap btnTemplate</value>
      <webElementGuid>95fb4609-6ef8-4ff0-a243-5287272da77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://tm.azlogistik.id/assets/template/template_nopol.xlsx</value>
      <webElementGuid>5230143b-d49e-4c50-902e-f67e5cff3409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>download</name>
      <type>Main</type>
      <value>Template Plate Truck</value>
      <webElementGuid>281e1d4b-6816-46e5-9c3e-bc923ce98b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Download Template File
                        </value>
      <webElementGuid>565bae29-cbc3-49eb-b345-973f8e63dddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label_fileNoPol&quot;)/div[@class=&quot;default-file&quot;]/a[@id=&quot;BtnLihatContohSuratJalan&quot;]</value>
      <webElementGuid>470a7b3f-651d-4c95-9af9-d297efb63af2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='BtnLihatContohSuratJalan']</value>
      <webElementGuid>df7f6cdf-3056-416b-ac58-b393c09663f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='label_fileNoPol']/div/a</value>
      <webElementGuid>eea51943-2655-4235-866e-57b420c90345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download Template File')]</value>
      <webElementGuid>fdb7a5f3-a516-457c-a709-3385db0e4181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file xls max. 5MB'])[1]/following::a[1]</value>
      <webElementGuid>a2439a7b-75a2-49a6-9f57-2db8a05f9708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[4]/following::a[1]</value>
      <webElementGuid>89e13d35-140c-4660-b7e1-fbb518909ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Daftar No. Pol'])[1]/preceding::a[1]</value>
      <webElementGuid>9ffb2d1a-cffc-49f7-bbaa-db5dcf0350d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Template File']/parent::*</value>
      <webElementGuid>27e69850-0687-4d0f-94d8-425eebcebc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://tm.azlogistik.id/assets/template/template_nopol.xlsx')]</value>
      <webElementGuid>2fc8197e-bd87-4b01-a400-488aa48eee76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>6595a2de-c4e9-4686-8059-076d4c739501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'BtnLihatContohSuratJalan' and @href = 'https://tm.azlogistik.id/assets/template/template_nopol.xlsx' and (text() = '
                            Download Template File
                        ' or . = '
                            Download Template File
                        ')]</value>
      <webElementGuid>57e454c8-5062-445c-b0e5-de9e08eefd31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
