<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pangkas Foto Profil_cropper-container c_db0534</name>
   <tag></tag>
   <elementGuidId>e7a9bcc1-92e8-4fa0-9d60-cf09afda13e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalCrop']/div/div/div[2]/div[2]/div/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cropper-crop-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c52c20fb-4e74-41fe-9332-a6727b06f74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cropper-crop-box</value>
      <webElementGuid>6670694f-a892-475a-96a7-69eb595dab06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>touch-action</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e69c7770-7aa7-4688-9fc6-5d8a0348b903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@id=&quot;modalCrop&quot;]/div[@class=&quot;modal-dialog modal-lg modal-dialog-centered w-451&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body row&quot;]/div[@class=&quot;img-container col-md-12 d-flex justify-content-center&quot;]/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;cropper-container cropper-bg&quot;]/div[@class=&quot;cropper-crop-box&quot;]</value>
      <webElementGuid>ce58b977-fbb7-49ef-8cb3-9a6b61dcf449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalCrop']/div/div/div[2]/div[2]/div/div/div/div[3]</value>
      <webElementGuid>f2407bb5-960b-47ac-b58b-8b5c519d46d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pangkas Foto Profil'])[1]/following::div[8]</value>
      <webElementGuid>db6522ee-76e8-4b98-aa0d-08da5fb23731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/following::div[38]</value>
      <webElementGuid>6001e69c-470a-49bf-9cb9-50a3d1780269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::div[2]</value>
      <webElementGuid>a7cf4e84-691b-4c71-9315-0eb0b93d3408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[2]/preceding::div[2]</value>
      <webElementGuid>76f409dd-ce81-4a9d-8fd5-6be5860db050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[3]</value>
      <webElementGuid>7a4a7963-6794-49ad-b52e-1fdc89d6ef97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalCrop']/div/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>65d11d13-5eea-48b5-a55b-c812799f09ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pangkas Foto Profil'])[1]/following::div[4]</value>
      <webElementGuid>2b70e5b7-d5a8-4d7d-b7c0-b0b1cfaa58d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/following::div[34]</value>
      <webElementGuid>a61330db-72c7-4988-88b2-f55408f5890d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::div[6]</value>
      <webElementGuid>19527824-6a4a-4c80-9f20-d31d3e56515b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[2]/preceding::div[6]</value>
      <webElementGuid>75ae1346-3c51-427d-bd78-753f5b3646c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>c1c15363-44e4-466d-b4ef-845ee1df6a01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
