<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Perusahaan_CompanyName</name>
   <tag></tag>
   <elementGuidId>f250f7cf-1403-4032-85bc-0e10dc5df8da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CompanyName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a101e39e-f6d0-4b07-900c-0f894c1a5f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyName</value>
      <webElementGuid>2fb1de5b-a8c0-4e49-b4ef-8bcc4bfdd545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input filled-requirement-dataPerusahaan</value>
      <webElementGuid>17d86325-f2ab-4adc-8255-a0a1c3e6d1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7cf4bf1-f082-4b1f-89ae-75d0ca55ba8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama perusahaan</value>
      <webElementGuid>1fb1c58d-a57b-4905-bdee-c51543884ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyName&quot;)</value>
      <webElementGuid>1cbe255a-1123-4378-bbe7-b48597de790f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyName']</value>
      <webElementGuid>64e7c1b2-c61d-4c56-a086-0b113bf64447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldCompanyName']/input</value>
      <webElementGuid>54d6fc74-6f81-4b1c-9db6-a040a52109f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>048703ac-4b60-4ec7-90f7-189744bd16d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CompanyName' and @type = 'text' and @placeholder = 'Masukkan nama perusahaan']</value>
      <webElementGuid>dea323cf-8788-44e2-b11b-d5dadd5b7912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
