<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No NIB_TxtNoNIBYayasan</name>
   <tag></tag>
   <elementGuidId>fc446eb5-153f-42e5-a84e-8d9e80dead01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtNoNIBYayasan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TxtNoNIBYayasan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac580e89-76ee-4490-83c7-89e598e73a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>8d7f0126-cf31-4840-8bd5-34b4a5f4a6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> no-border text-field text-field-default font-size-12 ff-medium-az form-input-postalcode-az form-input-number-noncentered-az filled-requirement-dataLegalitasYayasan</value>
      <webElementGuid>0e216fc9-f245-42df-971a-4df10908d53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtNoNIBYayasan</value>
      <webElementGuid>75e11bf6-6e97-4f3e-8a88-0df404827876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca6e6881-7f24-4d69-b78d-b0267a910389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>13 Digit No.NIB</value>
      <webElementGuid>3ad41b4e-35a0-4963-bbc2-35c60a699a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtNoNIBYayasan&quot;)</value>
      <webElementGuid>02af61e1-8149-4f9d-ae3f-736a6b68af31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtNoNIBYayasan']</value>
      <webElementGuid>1c13d67e-9f35-43f4-a6da-586ab9f2221a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisTMTransporterKelengkapanLegalitasFirmaYayasan']/div/div[2]/div[2]/div/input</value>
      <webElementGuid>349957c2-1209-4136-8b04-7b16677951bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>db5153ea-3aa3-4212-a4dd-053ded007e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TxtNoNIBYayasan' and @type = 'text' and @placeholder = '13 Digit No.NIB']</value>
      <webElementGuid>2235df39-d9d5-41b4-8084-66216750a04b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
