<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama PIC 2_Pic2Name</name>
   <tag></tag>
   <elementGuidId>eb9a8cf0-e3aa-4876-ae21-43ac3a5807fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pic2Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pic2Name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e22b946-e661-4190-8ffb-cd17123ceffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pic2Name</value>
      <webElementGuid>7b06cd36-5d40-4cbc-8d2f-2d3802cb00cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input</value>
      <webElementGuid>b50dda8a-9463-444a-91ae-07bf4a5fc479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>665d0948-f45b-4174-8d61-93364ecd3ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama PIC 2</value>
      <webElementGuid>378a5ed0-8edc-4d85-a2b9-3c487c13d617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pic2Name&quot;)</value>
      <webElementGuid>482d36cd-0cbc-472d-942a-bf2bf3765ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pic2Name']</value>
      <webElementGuid>7e79a3c6-e06a-427d-9d14-d5d02afdd027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisTMTransporterDataPerusahaan']/div/div[18]/div[2]/div/input</value>
      <webElementGuid>2684b66b-8441-44b4-a717-e60555893329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[2]/div/input</value>
      <webElementGuid>33988676-99c4-479b-b17e-6a614ee95e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Pic2Name' and @type = 'text' and @placeholder = 'Nama PIC 2']</value>
      <webElementGuid>9e5ee1e0-45d7-4d44-b4bc-a2f0dfaf3f5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
