<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Riwayat</name>
   <tag></tag>
   <elementGuidId>001e1bdb-51dc-4ccc-adff-01bb95930756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#konftrans-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='konftrans-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>599b0eb7-bf2b-48d5-afd5-6d9ef3053b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 tab-folder tab-folder-kontrak-harga tab-folder-inactive d-flex align-items-center flew-wrap</value>
      <webElementGuid>ea024f35-1be6-4914-921e-42aa6e483a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>konftrans-header</value>
      <webElementGuid>1363b6d9-1223-4bc5-869f-0ffaa77a2ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7177e4b5-d501-4dd3-b582-ef480b0ccdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Riwayat
						
						
					</value>
      <webElementGuid>9a19cab9-3c36-4ef5-93a5-a1baa677af0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;konftrans-header&quot;)</value>
      <webElementGuid>ccd1777d-2620-46fa-a2a8-fe2a9bfa091d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='konftrans-header']</value>
      <webElementGuid>53ba548d-1859-419f-a971-27b773f558f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='summary-header']/div[3]</value>
      <webElementGuid>350c138d-58f2-48a0-a123-954690c8f439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::div[1]</value>
      <webElementGuid>3608a6ec-a0b2-40cf-8bc0-5e8d41d50ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan Jumlah Detail'])[1]/preceding::div[3]</value>
      <webElementGuid>7b3a34f1-d4aa-40f1-94df-5a7a78369e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Riwayat']/parent::*</value>
      <webElementGuid>8ac9062b-3888-4ff8-ab0c-269054acec5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[3]</value>
      <webElementGuid>9843b2c4-2e38-446b-af29-09c2dc178d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'konftrans-header' and (text() = '
						Riwayat
						
						
					' or . = '
						Riwayat
						
						
					')]</value>
      <webElementGuid>c658f6b6-48dd-405c-a162-2d382ac6a4b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
