<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pencapaian, Penghargaan, dan Ser_d3ca56</name>
   <tag></tag>
   <elementGuidId>0ab069fa-e595-4f3f-8895-9051e0bacbe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.component-input-border-container.mb-8 > input.no-border.fs-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fe64a8f-fd63-44d0-9697-784dde1e24a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12</value>
      <webElementGuid>f8da9615-609b-441b-94cf-b9b3fdcf777f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e38efe4d-f90b-4501-a3fb-39b9e46a9712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Sertifikat</value>
      <webElementGuid>819bd713-382c-43af-9d61-f7769cbd2e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_sertifikat</value>
      <webElementGuid>73020843-2886-4fbd-81b2-f1300727da86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_sertifikat</value>
      <webElementGuid>8ac0b85d-d2c3-468c-b4ec-8505fd2c1f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_sertifikat</value>
      <webElementGuid>58bc04d8-6ffc-49b6-93c0-274111776646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_sertifikat</value>
      <webElementGuid>21cf3ef1-b1b8-4432-9841-f830a16872e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_sertifikat</value>
      <webElementGuid>97914a5c-ed36-4d01-8f43-19f140bedee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>39ab3252-04c1-497e-815e-75d33c4d798c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>33aae349-473a-460b-a75e-9c411942bc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>Format file tidak sesuai</value>
      <webElementGuid>18649ce3-67fa-4a5c-a533-7a6e9625e7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_sertifikat</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 255</value>
      <webElementGuid>77793e4f-c375-4f6c-a348-c2b7eea91ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>Ukuran file melebihi batas 5MB</value>
      <webElementGuid>3836b79b-7596-4f45-9dc3-d73ac74e6014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_sertifikat</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>a5330d30-97f4-4a64-93b5-e5f419060b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG, WEBP, SVG</value>
      <webElementGuid>ee13d84e-3056-4396-ae79-c70e4344aa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_sertifikat</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>c6069263-0349-49b9-980b-0c98a6901865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_sertifikat</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>dc2d3e88-0885-4ff2-87cc-7fc8f3b27c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ad0b955a-908f-4427-a8b0-89b1e21825ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_sertifikat</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>7fbfa372-c52e-46d6-9db3-0a03dc98740b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;div-grow&quot;]/div[@class=&quot;d-flex component-input-border-container mb-8&quot;]/input[@class=&quot;no-border fs-12&quot;]</value>
      <webElementGuid>5c32c8c9-93b5-4276-a5b3-3e5615a8069a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[8]</value>
      <webElementGuid>ca8fe5ab-1408-44e4-a35a-6f7eeed9890a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[11]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>331b41f6-b6b8-4def-8922-360888b49e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>55291950-db88-4c2c-851d-7dbc6650a520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Sertifikat']</value>
      <webElementGuid>b2365cfa-b53e-4ec2-9cb8-85ffd7cf2144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
