<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lainnya</name>
   <tag></tag>
   <elementGuidId>a701d43d-2164-4005-9890-cad9855caad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContCategoryAdv']/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > a.text-nav-buyer.text-white.fs-16-az.ff-demi-az.lh-19-2.spa-category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d29dd5a-c5e5-48f9-80f2-a9c3b60f7876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://buyer.azlogistik.id/plastic?KategoriID=114&amp;subKategoriID=182</value>
      <webElementGuid>54f70afd-f31d-4828-9621-84ace8f4e128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kategori</name>
      <type>Main</type>
      <value>114-182</value>
      <webElementGuid>8b4c4296-3632-4335-b917-f80074e7b458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-nav-buyer text-white fs-16-az ff-demi-az lh-19-2 spa-category</value>
      <webElementGuid>16cfeaac-84f7-4423-b4ee-667c6cf9a687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lainnya
                                
                                </value>
      <webElementGuid>79fbea67-2eb5-4a6a-af3f-b439c752a6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContCategoryAdv&quot;)/div[3]/a[@class=&quot;text-nav-buyer text-white fs-16-az ff-demi-az lh-19-2 spa-category&quot;]</value>
      <webElementGuid>75821fcd-5594-4ca3-9fcf-c0646785134a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContCategoryAdv']/div[3]/a</value>
      <webElementGuid>958cfb0c-a7f5-41d0-943c-7e85d57eeb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lainnya')])[2]</value>
      <webElementGuid>33ec433c-ad4a-4870-a9e8-19f6416d7fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packaging &amp; Plastic'])[3]/following::a[1]</value>
      <webElementGuid>de5641c9-3399-4792-bf00-88b97b088e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[1]/following::a[2]</value>
      <webElementGuid>905da9b5-0582-4975-b275-ae650eda9a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu Utama'])[1]/preceding::a[1]</value>
      <webElementGuid>e0d5ee5e-80a7-4a9c-94b4-ea757db95f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[2]/preceding::a[1]</value>
      <webElementGuid>c014eb89-53e9-45b2-99b0-61c0b49cfd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://buyer.azlogistik.id/plastic?KategoriID=114&amp;subKategoriID=182']</value>
      <webElementGuid>ed4b9043-8047-4d5e-b8ab-e8defabb813f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/a</value>
      <webElementGuid>61e89443-b83b-4093-ba5b-6203d47b2b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://buyer.azlogistik.id/plastic?KategoriID=114&amp;subKategoriID=182' and (text() = 'Lainnya
                                
                                ' or . = 'Lainnya
                                
                                ')]</value>
      <webElementGuid>29caa941-4fce-4aab-87de-75cd0daa1869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
