<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya_1</name>
   <tag></tag>
   <elementGuidId>bbd0bf53-12a0-466a-a9a1-e78ab4aa734a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnNextRegisBFShipper_step2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnNextRegisBFShipper_step2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64cd5992-25cf-4225-9b03-af7fe1dcaf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>margin-remover ff-demi-az</value>
      <webElementGuid>927d5613-b003-4e84-8583-62671e539c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnNextRegisBFShipper_step2</value>
      <webElementGuid>c732d3f4-9724-46c2-8357-9979ee59df94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Selanjutnya
            </value>
      <webElementGuid>1d572f40-880a-4767-b58f-00bce1487630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnNextRegisBFShipper_step2&quot;)</value>
      <webElementGuid>d3e783dc-4494-42e0-9ea7-8d36bc26f1c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnNextRegisBFShipper_step2']</value>
      <webElementGuid>cc23f4bf-0be5-46a7-a372-ca892f822d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisBFShipperDataPerusahaan']/div/div[24]/button</value>
      <webElementGuid>c80ffd9a-3527-4e58-b2eb-c52fe77b63f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email*'])[1]/following::button[1]</value>
      <webElementGuid>cdf4ef09-b0f4-41ab-aa26-37195d42b6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi dan konfirmasi dari muatmuat akan dikirimkan ke email Pemegang Akun'])[1]/following::button[1]</value>
      <webElementGuid>6d4fc151-51bd-4554-8110-0b6d353ebbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Lokasi'])[1]/preceding::button[2]</value>
      <webElementGuid>6e5a1729-5dbf-44e2-b3d7-c92d9b89dead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lokasi*'])[1]/preceding::button[2]</value>
      <webElementGuid>b4a3edcc-3ad6-4aaf-832d-4c1a27ae47c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/button</value>
      <webElementGuid>5496faef-5574-43c8-aa89-22047416adfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnNextRegisBFShipper_step2' and (text() = '
                Selanjutnya
            ' or . = '
                Selanjutnya
            ')]</value>
      <webElementGuid>e6a7134c-559b-4c43-82ed-220dac2c2437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
