<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload</name>
   <tag></tag>
   <elementGuidId>07c0b771-d819-44c1-94c5-57b45cd00472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnUploadFotoProfil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnUploadFotoProfil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5208f843-1493-4279-bf67-7ab369018d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover fixed-btn-96-32</value>
      <webElementGuid>ade704a6-850a-4a73-9ee4-8fba8c5e2cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnUploadFotoProfil</value>
      <webElementGuid>1e500913-1feb-460f-aac4-a0de86154b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#ModalBox</value>
      <webElementGuid>da556e21-73d8-43a1-9828-1f3456384152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3384b716-b3c8-4162-8fa8-c48e410595f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parameter</name>
      <type>Main</type>
      <value>{&quot;type&quot;:&quot;ModalUpload&quot;,&quot;value&quot;:&quot;asd&quot;}</value>
      <webElementGuid>f45a606c-a128-48a7-8cbf-be41bf3d2a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>0143039d-3c5f-4594-9eb4-abb63a411370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnUploadFotoProfil&quot;)</value>
      <webElementGuid>53c284c7-c6ac-4959-8017-b2cb5f5de749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnUploadFotoProfil']</value>
      <webElementGuid>e289f95c-0607-48c0-98df-9a4cc632c6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisBFShipperDataPerusahaan']/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>06a0a58a-802c-46c2-b577-5149f2acebd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Harus diisi)'])[2]/following::button[1]</value>
      <webElementGuid>951b8b7c-1c1d-4ddb-ad4c-51a583d45063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logo Perusahaan*'])[1]/following::button[1]</value>
      <webElementGuid>b933888c-6290-4b43-b1a1-089367805d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file jpg/png max. 5MB'])[1]/preceding::button[1]</value>
      <webElementGuid>5af3d35d-af7c-4124-8676-d6fe12629e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Perusahaan*'])[1]/preceding::button[1]</value>
      <webElementGuid>d2b32ab3-d45c-40d4-837d-50c2262f6f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>ef31c3e6-c2c5-477c-8a17-27ab4ff231fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnUploadFotoProfil' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>75d431a2-2099-4035-a4f7-1595cbe9ce72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
