<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. HP PIC 1_Pic1Phone</name>
   <tag></tag>
   <elementGuidId>308fcb76-0ff2-4c10-80c2-3f1a4e733202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Pic1Phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pic1Phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d6d84fd-0438-4aa9-bd58-cb112c1957fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>35f17db6-628f-418f-a72b-1773e8910247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pic1Phone</value>
      <webElementGuid>8d1a5b9d-c829-4e9a-ba19-021bebb653ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81bd016e-8b95-4a0d-9010-e926e41a528e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>178d0c19-539a-473e-ab57-e804812c70f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh : 08xxxxxxxxxx</value>
      <webElementGuid>31da9557-3485-4f96-ba1c-10203d0a28b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> no-border text-field text-field-default form-input-postalcode-az font-size-12 ff-medium-az filled-requirement-dataPerusahaan form-input-number2-az</value>
      <webElementGuid>74eaf72b-29cc-4fce-862b-f3242c813f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pic1Phone&quot;)</value>
      <webElementGuid>44b32992-4cf5-4ccc-bc7a-d77ff0e3980c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pic1Phone']</value>
      <webElementGuid>e5813b45-5da2-4ba7-b6bb-944f8f519624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldPic1Phone']/input</value>
      <webElementGuid>d9105b76-c568-4132-b86e-4c59aa2d8ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/div/input</value>
      <webElementGuid>16e16305-69a0-4d91-9691-5dabcefc5e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Pic1Phone' and @type = 'text' and @placeholder = 'Contoh : 08xxxxxxxxxx']</value>
      <webElementGuid>190a16fc-27cb-4d4b-b190-6d3742f1dbcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
