<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama PIC 3_Pic3Name</name>
   <tag></tag>
   <elementGuidId>799d4de1-c1c9-4112-bb25-c4fbe256db52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Pic3Name&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pic1Name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a313fe59-08eb-4ee1-9120-02728958e3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b7ce599e-3b68-4249-a9fa-ad947788d275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pic1Name</value>
      <webElementGuid>48dc3fa3-0ff3-43ee-b72a-0d06dca35280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>dd5aee88-a31e-4d32-9a52-40afb7666876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input filled-requirement-dataPerusahaan</value>
      <webElementGuid>c06fc23b-3d99-42e8-b059-67b5d7a7815e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee71cb7c-12f9-4664-997b-6e9ec02e01ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama PIC 1</value>
      <webElementGuid>5179d745-d427-4238-bd12-7705adc494c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pic1Name&quot;)</value>
      <webElementGuid>92d9b9ca-0b69-4078-9391-148790cee3de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pic1Name']</value>
      <webElementGuid>9d51ae8f-8295-4da4-97c6-a077cd59b543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldPic1Name']/input</value>
      <webElementGuid>2a805585-f6bc-4237-a14f-62db77a0dcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/div/input</value>
      <webElementGuid>711a49f1-f7b6-4da8-b5ce-e18d1f33119e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Pic1Name' and @type = 'text' and @placeholder = 'Nama PIC 1']</value>
      <webElementGuid>3b8261e3-963a-42a3-87c0-ce4131cad984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
