<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Perusahaan_ValueAddres</name>
   <tag></tag>
   <elementGuidId>89918e93-67bb-45a1-abad-992739d48372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValueAddres</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValueAddres']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba9ea195-a5bd-406e-bbab-5aca5d05a888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ad04ef03-9b48-4c39-839d-a52f2c45eb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input filled-requirement-dataPerusahaan</value>
      <webElementGuid>27c9fccb-3a36-4e64-8985-af60e09e16d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a150709-a4d3-4ea4-afab-238a9577a263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alamat perusahaan</value>
      <webElementGuid>a2af3e58-585e-4481-b91c-46f812503d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValueAddres</value>
      <webElementGuid>74f90bf1-2008-4d01-928b-a55155117b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValueAddres&quot;)</value>
      <webElementGuid>c50610e2-734a-49e6-8e2c-ce2880aa22ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValueAddres']</value>
      <webElementGuid>66d7b789-391b-4927-99c0-558a55046058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerAlamatDepan']/input</value>
      <webElementGuid>4ee8c028-097f-4965-8f6a-b4e9e69d06c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>535428f4-ed04-4b18-9699-6bd9c8c8ae3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan alamat perusahaan' and @id = 'ValueAddres']</value>
      <webElementGuid>31efc503-7cfa-4a68-a646-37e85a2b45c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
