<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. HP PIC 3_Pic3Phone</name>
   <tag></tag>
   <elementGuidId>77292db9-dfd0-4f52-a695-12ab4af9a42c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pic3Phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pic1Phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15e48e12-53af-4c96-933a-9c3970a78a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3fdbeba1-474e-46fd-9564-51a6400899d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pic1Phone</value>
      <webElementGuid>ba2dbbbb-483a-439e-9bf9-58b6b16eb9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2406f2df-23c9-44bc-8250-a7e7dc0a0e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>2a6c32d4-2e13-4f30-b031-52f1136def65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh : 08xxxxxxxxxx</value>
      <webElementGuid>070dc036-8032-4e23-8e53-c2a970eb923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> no-border text-field text-field-default form-input-postalcode-az font-size-12 ff-medium-az filled-requirement-dataPerusahaan form-input-number2-az</value>
      <webElementGuid>27426a44-42db-41c4-a32b-4a0d77bb59ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pic1Phone&quot;)</value>
      <webElementGuid>3232c670-196a-4c92-8770-7edd6c6cf5de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pic1Phone']</value>
      <webElementGuid>74d56319-9384-40ee-a9fe-6037de86ef94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldPic1Phone']/input</value>
      <webElementGuid>5adb91f3-b856-4285-a655-02a81b26348f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/div/input</value>
      <webElementGuid>83ac1be8-8494-45cf-b019-f62195a5e357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Pic1Phone' and @type = 'text' and @placeholder = 'Contoh : 08xxxxxxxxxx']</value>
      <webElementGuid>bd746efc-39d7-483e-a1f8-b5f9549255de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
