<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Perusahaan_CompanyName</name>
   <tag></tag>
   <elementGuidId>acd2ffe7-d009-47c8-942e-c233f93a60bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CompanyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c098805-32d5-48f1-871b-72ddcc713bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ba63b65a-968c-43e3-b32d-39353ad3774e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyName</value>
      <webElementGuid>836a7edf-536d-4481-a933-1d1b1f2b384c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input filled-requirement-dataPerusahaan</value>
      <webElementGuid>6e9cc73f-5d21-4d48-b8d3-1f33404cf17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>918fc109-c79a-4928-bf47-65621c046c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama perusahaan</value>
      <webElementGuid>7d78324f-e0fe-4c14-b92b-5119004f2bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyName&quot;)</value>
      <webElementGuid>74d2a663-63e1-4d9e-8892-370e7b3c2bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyName']</value>
      <webElementGuid>396d0959-0efc-4824-9d08-4f86ab4e7a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldCompanyName']/input</value>
      <webElementGuid>6da1ee4c-3ff9-49c7-8956-5f1ca1220fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>3b3cd5ec-717a-4189-845f-ead622922d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CompanyName' and @type = 'text' and @placeholder = 'Masukkan nama perusahaan']</value>
      <webElementGuid>20ed363c-56ef-4a1c-be3a-8e84bbcb30d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
