<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lihat Barang Lainnya Dari Penjual</name>
   <tag></tag>
   <elementGuidId>def5d8db-1b1f-45c0-b0e1-d2fd44687f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-lainnya</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-lainnya']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d3e55a86-97dc-4b2a-a374-3cafebcc82f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-outline-az margin-remover</value>
      <webElementGuid>0591e72f-7b4a-490d-881d-61aea050e7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-lainnya</value>
      <webElementGuid>2ca94f3d-3ca8-4e98-95eb-92d07306260d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Barang Lainnya Dari Penjual</value>
      <webElementGuid>60b699d6-c3fc-4191-9828-37b8d601a8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-lainnya&quot;)</value>
      <webElementGuid>de91c4a7-3fbd-46f1-9e0b-6f50b4459a50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-lainnya']</value>
      <webElementGuid>d8b28d56-1c15-4fad-a0d8-9b955c33e25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi'])[1]/following::button[1]</value>
      <webElementGuid>ccec367f-e15c-4d50-8bfb-46c316f5d25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporkan Iklan Ini'])[1]/preceding::button[1]</value>
      <webElementGuid>099abd17-2eeb-42c2-afb5-fcf2561fc373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Barang Lainnya Dari Penjual']/parent::*</value>
      <webElementGuid>a4b710e1-3eca-4b6a-856d-f998be6bf092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>1d276fb0-2bbb-4226-a5b3-46b0794d2aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-lainnya' and (text() = 'Lihat Barang Lainnya Dari Penjual' or . = 'Lihat Barang Lainnya Dari Penjual')]</value>
      <webElementGuid>cb9c427e-1880-472e-8c96-a65b90eec2f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
