<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama File_no-border fs-12 ff-medium</name>
   <tag></tag>
   <elementGuidId>604601de-a263-4e91-a4ca-dde146c525a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.component-input-border-container.mb-8 > input.no-border.fs-12.ff-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bbbb7f7-074c-4106-b63e-49d2226c4d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12 ff-medium</value>
      <webElementGuid>873c4e74-d909-400b-bb13-ce86dc150284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84915828-a22a-4b40-bd96-e5daa3dd8e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama File</value>
      <webElementGuid>7057d91f-bcae-4544-bca9-fee2918c16af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_portofolio_testimoni</value>
      <webElementGuid>91a953b0-3827-4913-984c-51824df2640b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_nama_file</value>
      <webElementGuid>d1fb32e0-e8c7-47ef-8b16-b985136b35d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_nama_file</value>
      <webElementGuid>909b6a50-fbb7-405c-8f24-7fcc2f538d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_nama_file</value>
      <webElementGuid>e3174ec4-6632-4cf2-a42a-ebc5645ae49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_nama_file</value>
      <webElementGuid>2cfd6a20-86d6-4e39-a7fe-aac40da331e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>15facb50-de45-4345-b0ba-d7cf4cf9c01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>04a93496-336a-494c-9a21-81aff9128ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_file</name>
      <type>Main</type>
      <value>Format file tidak sesuai</value>
      <webElementGuid>766c7e6d-14bf-4894-8292-cc61defd55bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_nama_file</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 100</value>
      <webElementGuid>dd264e24-91a5-422f-a9fd-f8ec8a7ae056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_file_size</name>
      <type>Main</type>
      <value>Ukuran file melebihi batas 5MBMaksimal 5MB</value>
      <webElementGuid>39ab0c5e-1527-49f5-9c2b-0fabf8a79d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_nama_file</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>af6c4145-16fd-4405-a213-76cca6c0c9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_file</name>
      <type>Main</type>
      <value>All, PDF, DOCX, JPG, PNG, WEBP, SVG</value>
      <webElementGuid>b9c2e2fc-4737-4cad-a623-88612397e395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_nama_file</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>fed64695-4cf5-403e-833d-7f81bbfd4431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_testimoni</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6e2f3e63-d3a7-473a-b9ed-345fab0788a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_file_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d3169e53-7b70-49a4-af2f-c71a62e41b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_nama_file</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d088e198-c674-4790-9d48-cdd5f7e1fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;div-grow&quot;]/div[@class=&quot;d-flex component-input-border-container mb-8&quot;]/input[@class=&quot;no-border fs-12 ff-medium&quot;]</value>
      <webElementGuid>ee3b7d4e-6ff2-4dfa-8288-cf662cc2ac26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[12]</value>
      <webElementGuid>3f6a2dfa-5757-406a-b9fb-908b6d3cb4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[16]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>76e57325-c0a7-4eab-a694-4ba9cdc14fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>6e1659f9-c9e3-4108-b667-697c2d6ea57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Nama File']</value>
      <webElementGuid>385a54dd-b8ad-4b51-8519-7eb503a3c5a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
