<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat_searchBoxModalAddress0</name>
   <tag></tag>
   <elementGuidId>64918ee6-a458-42ab-8226-774235f32a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBoxModalAddress0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBoxModalAddress0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04b443dd-93dd-4dc8-984f-938e23feeced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64c57e9a-d255-4737-9ca6-3eeecd443114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mapsSearch fs-12 fc-1b no-border</value>
      <webElementGuid>143f7c78-0bda-4c8e-9bf0-ebc27ca723c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBoxModalAddress0</value>
      <webElementGuid>d6d2402c-b02f-4ca1-bc39-81d6387af10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hidden</name>
      <type>Main</type>
      <value>Address0</value>
      <webElementGuid>397ac9c4-f570-40c0-bf5e-a32a1456d885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan lokasi</value>
      <webElementGuid>aad4b6ed-6a10-4e84-90ec-aab1e10905b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>d632d2c0-6e12-4ccf-9341-dfe128698bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>2c9a6382-0f31-4c05-be0d-5480b910844d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bf4287a6-8cda-4606-b41c-cac95cb0d127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBoxModalAddress0&quot;)</value>
      <webElementGuid>9b07db80-121e-4a75-bcf3-aed06765064f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBoxModalAddress0']</value>
      <webElementGuid>4e6392e6-77f8-4733-af78-c8129077ed23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='parent-searchBoxModalPickUp']/div/div/input</value>
      <webElementGuid>bfbf89bd-e077-4287-9a2e-9f669071dbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>a900c224-ab91-4145-a3a5-7494097f2509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'searchBoxModalAddress0' and @placeholder = 'Masukkan lokasi']</value>
      <webElementGuid>9b3a108c-1713-4439-a15a-cdd9de699618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
