<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no-border fs-12 h-30 w-100</name>
   <tag></tag>
   <elementGuidId>830e7e27-9d6c-4bde-9bac-f0edc7785e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.no-border.fs-12.h-30.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2c988fc-11ca-4754-95d9-66240bd76bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12 h-30 w-100</value>
      <webElementGuid>967db0b3-7592-4d35-8e61-7bb43101d858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db0ff1ca-8bd2-4880-ba80-a2c817b61f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Caption</value>
      <webElementGuid>21ea32c8-b4b0-42eb-aec7-425815003158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>caption</value>
      <webElementGuid>67f202f2-5cf3-4289-96d7-13776a064c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cd785702-ea25-4ad0-9927-712c9aed7d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>Format file tidak sesuai</value>
      <webElementGuid>6e5a86d5-8686-4951-9a54-214ddd6d3282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_caption</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 100</value>
      <webElementGuid>6be56277-4d9b-499b-ad3a-6db847f523c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>Ukuran file melebihi batas 5MB</value>
      <webElementGuid>2fda6b4e-4a30-462d-8608-f3a52ae418fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_caption</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>2ce6e4b4-3e38-4339-8cd2-f010ec2f6395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>3fff6e7b-9ebd-4bff-9cdf-6be2b17f5176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG, WEBP, SVG</value>
      <webElementGuid>02b21803-9a39-413a-850d-baf6bc69ab6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_caption</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1c4857b0-69a4-4728-a883-8fe39dd066d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_galeri</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>3e3765a0-a1e2-44f5-a8bc-e1d2e4432ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>94731c14-a9fa-4453-96f5-d4ceb614912f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_caption</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>13f0eed6-e96c-4144-b1e0-1686c1f2ceef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_caption</value>
      <webElementGuid>d8336aa0-e949-4d61-ba87-3e7e120d4e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_caption</value>
      <webElementGuid>5a6509ba-6a7c-4a44-a08e-232e5aa78385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_caption</value>
      <webElementGuid>7f8bec8f-0ad0-41a0-a7ee-50ccbe27412a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_caption</value>
      <webElementGuid>0e9dc5a4-7bb3-4e83-b960-cdcb5d7ac36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;d-flex component-input-border-container mb-8 h-32&quot;]/input[@class=&quot;no-border fs-12 h-30 w-100&quot;]</value>
      <webElementGuid>1024f053-dda2-4eef-b524-ec0e8d42f12f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[8]</value>
      <webElementGuid>6c43cb9e-f4cb-4f5f-a914-039df30d0f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[12]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>6c94048d-d51d-422c-8d28-c12eb12942ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>090749b4-75f5-433a-8837-b9c63043c81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Caption']</value>
      <webElementGuid>d1c054f5-e9dc-4258-8a41-aad06e7538bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
