<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Lainnya_CBLainnyaField component-i_347356</name>
   <tag></tag>
   <elementGuidId>0af95908-292e-48d0-aff0-10ca1eff6779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.CBLainnyaField.component-input-border.fs-10.ff-medium.fc-1b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PasangIklanForm']/div[6]/div[2]/div[19]/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4c1773a2-440f-4501-80b8-c553de62b00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CBLainnyaField component-input-border fs-10 ff-medium fc-1b</value>
      <webElementGuid>51957928-d54d-481e-b9ea-3f0f9cd1d9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Karoseri Lainnya</value>
      <webElementGuid>536a7876-8c15-481a-a6f8-14ca25827b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f58a98d9-dca8-4c0c-96a7-ecd5339c434e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_opsi_lainnya</value>
      <webElementGuid>0a8da5f3-b422-46f7-baed-4a0e365a6cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_opsi_lainnya</value>
      <webElementGuid>f7fc9675-dd8a-4d92-8864-2f24af589073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_opsi_lainnya</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 100</value>
      <webElementGuid>1184f46a-f3f0-4144-b967-f3aa71390a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>d575fa16-ec48-4628-9c3b-331dacbdf754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_opsi_lainnya</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>88922efe-f772-4ff2-885c-d92015ec3496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12  mt-8 row mx-0 no-border&quot;]/div[@class=&quot;CheckBoxButtonItem col-12 d-flex align-items-center px-0&quot;]/div[@class=&quot;flex-column d-flex&quot;]/div[@class=&quot;CBLainnyaField&quot;]/textarea[@class=&quot;CBLainnyaField component-input-border fs-10 ff-medium fc-1b&quot;]</value>
      <webElementGuid>cbb69c09-6796-4386-b410-8539e29d0461</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[6]/div[2]/div[19]/div/div/textarea</value>
      <webElementGuid>d2fbbd5f-b3fd-4bd8-a39a-1730bad44142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/textarea</value>
      <webElementGuid>7896ed61-74fd-4822-b02e-e35f7ff98117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Masukkan Karoseri Lainnya']</value>
      <webElementGuid>5528d3a9-2329-48b1-be9c-5fc53c3c793a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
