<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat</name>
   <tag></tag>
   <elementGuidId>fa9119d9-b13c-42df-a5a7-dd3da57d4bcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=&quot;form-submit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24c81e54-f050-4011-990d-88d92fe17922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1fb95d1e-2488-4de5-af2a-fbe4ba2e37f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-submit</value>
      <webElementGuid>10311db9-bb57-4d52-99d0-54fa10a1e307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn upload-btn btn-fi btn-flex</value>
      <webElementGuid>a6b7a1ad-0260-4c35-903c-f65b5122e6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buat</value>
      <webElementGuid>5f1bde22-8141-4fb5-b31e-bc80016712f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-submit&quot;)</value>
      <webElementGuid>8195c2e6-31b8-477d-9100-861c995fd6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form-submit']</value>
      <webElementGuid>ee49bf02-1f15-4bf7-9833-a401dbabbb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[5]/div/button</value>
      <webElementGuid>0a393ace-4a2a-415d-8e75-fb781953fec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(opsional)'])[6]/following::button[1]</value>
      <webElementGuid>6affef5f-7db0-4003-8c4d-811c875269af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diumumkan Kepada*'])[2]/preceding::button[2]</value>
      <webElementGuid>6fd1c8fb-1f98-437f-a89e-b749373cd8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Transporter'])[1]/preceding::button[2]</value>
      <webElementGuid>fa51151c-2564-4f9b-a17f-885979084c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat']/parent::*</value>
      <webElementGuid>3c081a37-b934-4692-a7f8-9405e09571fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>2ca518ef-014e-4d7a-a002-d2702ca1cdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'form-submit' and (text() = 'Buat' or . = 'Buat')]</value>
      <webElementGuid>1d7ed8ea-c755-45d7-8e82-dc2a2d37725e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
