<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(opsional)_panjang</name>
   <tag></tag>
   <elementGuidId>486b27b4-d852-4acf-8eb8-aba48f33215f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dimensi_panjang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dimensi_panjang']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2cfb3af-c2c0-402a-b06b-998e177cf15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb371207-3bf4-456b-b172-7f61c08ab4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>panjang</value>
      <webElementGuid>f2bcb042-a8da-4754-bcae-dea80475fa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d93da96e-9a6e-47ad-89b3-4a0d19701ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dimensi input-component ff-medium fs-12 formatDimensi satuan_berat_dimensi fc-1B text-center</value>
      <webElementGuid>9622ef22-4743-46a4-a77a-7de7de902cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>#dimensi_panjang</value>
      <webElementGuid>1dbe4519-05c8-4ede-8716-0f021bc794a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dimensi_panjang</value>
      <webElementGuid>8e017cd5-08f2-4969-8920-ab5b9b1c648a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dimensi_panjang&quot;)</value>
      <webElementGuid>3819ad32-ab58-4587-ab54-9483d68fe457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dimensi_panjang']</value>
      <webElementGuid>9a66d0ca-1264-4fd5-a8a3-43ea5209c2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[2]/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>be239562-df30-4467-90f6-f39891bedcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>cde96f33-e2b6-4e8d-831d-f7d94fdd2162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'panjang' and @placeholder = 'p' and @id = 'dimensi_panjang']</value>
      <webElementGuid>6083dd7e-4181-4a53-8cbb-78f3d6218adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
