<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah_unit_truk0jumlah_truck</name>
   <tag></tag>
   <elementGuidId>5de62682-706a-40fe-8852-2daedb22a1ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jumlah_truck-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jumlah_truck-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86352404-4909-455f-b2d8-1e0d104fcbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51bb8ef2-9364-42ba-bd4b-28f6884d9b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unit_truk[0][jumlah_truck]</value>
      <webElementGuid>e278358d-1189-49f4-9c03-aed2c0d5322f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formatNumber jumlah-truk input-text-pratender form-control  fs-12 fc-1b ff-demi pl-8px</value>
      <webElementGuid>075ecbd4-3bb6-45ac-a6a2-795ed6c0b6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumlah_truck-0</value>
      <webElementGuid>1ecda81f-4a45-44e2-9e69-232479edb8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>465333bb-699e-4fdc-a9d4-afbce457f48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4e2741bb-0cb3-4d04-9eba-1a80782476b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumlah_truck-0&quot;)</value>
      <webElementGuid>1d5ed65f-19ce-47d1-9779-e224b99f49ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jumlah_truck-0']</value>
      <webElementGuid>3318103c-6b8e-413d-b9fd-87b090b5f481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unit-truk-0']/div/div[2]/input</value>
      <webElementGuid>3e18da5e-c6ff-446d-8545-af5bbde728f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/input</value>
      <webElementGuid>fe2371ef-7ebb-4f00-a1ce-0530e3a5dbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'unit_truk[0][jumlah_truck]' and @id = 'jumlah_truck-0']</value>
      <webElementGuid>d31eae41-e2eb-4302-a606-7dd4aca16d00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
