<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_x_lebar</name>
   <tag></tag>
   <elementGuidId>ee227202-3083-4f9f-a2b7-71d8e7eab02e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dimensi_lebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dimensi_lebar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebd5860a-7750-4da2-8272-091e5d796a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10a346ed-9c3e-4778-b1e3-4e92a9dbef95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lebar</value>
      <webElementGuid>617dae7b-e6bd-48c0-9f9f-19e619230e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>c94004dd-8060-4cb0-a766-7f444e3b4c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-component dimensi ff-medium fs-12 formatDimensi satuan_berat_dimensi fc-1B text-center</value>
      <webElementGuid>922c5836-ec79-40ca-b7ad-b362ac421af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dimensi_lebar</value>
      <webElementGuid>9985e8ac-e297-42f2-9e28-15b439735143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>#dimensi_lebar</value>
      <webElementGuid>a8f9683a-df09-4f24-8fea-86c4eb1af7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dimensi_lebar&quot;)</value>
      <webElementGuid>8e238dd4-ac7b-4e0f-99d9-befc05ff2e1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dimensi_lebar']</value>
      <webElementGuid>7bba48f6-e2d9-4acb-9d2a-7394537e7a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[2]/div[2]/div[3]/div[2]/div/input[2]</value>
      <webElementGuid>8b38806f-dd04-47a1-83c9-06b22c12711d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input[2]</value>
      <webElementGuid>b773771d-1753-4dc8-b865-986fda06f986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lebar' and @placeholder = 'l' and @id = 'dimensi_lebar']</value>
      <webElementGuid>e5c2b5e7-78d7-4cb8-92dc-cb7d335ed9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
