<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kota Surakarta_rute0destinasi</name>
   <tag></tag>
   <elementGuidId>692ee420-1626-47be-8383-7bb28e766f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;destinasi0&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#destinasi0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d22d4491-2b41-4ca5-8f4f-264b312604c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10890124-9151-416f-800a-3deb3f4f61d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rute[0][destinasi]</value>
      <webElementGuid>3ab44d7b-ce09-43b7-aec0-0efe89128207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>destinasi0</value>
      <webElementGuid>a9be781f-f75f-4b45-9270-58ef8bdb580a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>025b7f60-56c5-4742-afcd-3aafef9ed058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fs-12 fc-1b ff-demi input-text-pratender pl-8px inputan-kota-destinasi mr-12 hg-32</value>
      <webElementGuid>debd5fc4-a0cb-4c98-81fc-751f6c02c987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lokasi Destinasi</value>
      <webElementGuid>3eca18ff-adc8-4129-adb8-8ef76528e34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;destinasi0&quot;)</value>
      <webElementGuid>d22ad678-0563-4f95-89e0-65afe8b22a45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='destinasi0']</value>
      <webElementGuid>1ac7420d-a2aa-41e3-b7bd-5143815432c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-rute-0']/div[2]/input[2]</value>
      <webElementGuid>b5911b29-85da-422a-a632-be05d5bf8903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input[2]</value>
      <webElementGuid>350191aa-a972-42c9-ab57-17acfb484863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'rute[0][destinasi]' and @id = 'destinasi0' and @placeholder = 'Lokasi Destinasi']</value>
      <webElementGuid>81647ee5-369c-4e27-bb47-1c2301f07305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
