<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sd_tahap_tender0max_date</name>
   <tag></tag>
   <elementGuidId>829f007d-fdf0-4e90-ac71-7f2e20d6256f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#max-date-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max-date-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71cff51d-c642-4fab-ba8a-ef6567092837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b30939d4-eb7a-4d9e-8e09-630c58681b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tahap_tender[0][max_date]</value>
      <webElementGuid>c5e3c453-897a-41ec-9acf-3a6bb0917bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>DD MMM YYYY</value>
      <webElementGuid>851cd561-0b98-41ae-b863-2a8ada5e2971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>Tanggal Akhir</value>
      <webElementGuid>59cc52f1-ecdf-4ec3-a450-196313e88469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max-date-1</value>
      <webElementGuid>c5b44149-3a35-4e04-a0d5-6eb6793c1195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tglSelesai input-pratender input-text-pratender form-control input-medium mr-10 max-date datepicker akhir i2 noOverlap</value>
      <webElementGuid>da1fa49b-e45d-4cd1-9697-cf7f09e381e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal Akhir</value>
      <webElementGuid>5f526286-e4d5-4d9b-9542-97db792b6f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provide</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>18f2bf78-e138-4649-9b06-4e178baaf034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>20 Jul 2023</value>
      <webElementGuid>600c61a6-bc34-496f-a24b-c9c3ce58001b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max-date-1&quot;)</value>
      <webElementGuid>f22bbcd1-5d64-4ea3-90fe-ac0c4ec4ca91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max-date-1']</value>
      <webElementGuid>f64f94af-4783-4dfe-ae31-02db7d49bba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area-tahap-tender']/div[2]/div[2]/input[2]</value>
      <webElementGuid>3be940fe-4a67-443c-81a4-b44abc1df7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>dd8d7932-9046-4889-b9f2-e3e5bb4fcc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tahap_tender[0][max_date]' and @id = 'max-date-1' and @placeholder = 'Tanggal Akhir']</value>
      <webElementGuid>156b1bf7-b913-456c-9a0c-effb02aeeef1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
