<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat Info Permintaan Muat</name>
   <tag></tag>
   <elementGuidId>ffc2e4aa-a38c-4cf7-85fb-95e8afd341fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;form-submit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea281379-377b-47bf-8292-60f41aad83aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd2b2251-3571-4135-8a5e-2c08706750e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-submit</value>
      <webElementGuid>29b517e8-f3f2-4f92-9606-0dd0f4f084f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flex btn-primary btn-fi</value>
      <webElementGuid>01654d7a-9ffd-41ba-8695-77cfd076abd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buat Info Permintaan Muat</value>
      <webElementGuid>3644513c-71a3-4965-b722-e20fe8f754a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-submit&quot;)</value>
      <webElementGuid>c6d16e41-0132-4935-8537-f3b6c0790c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form-submit']</value>
      <webElementGuid>f4c94815-cbe1-463a-9db8-770bf113f8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[6]/div/button</value>
      <webElementGuid>883d86f9-5649-4719-95ac-f01a729c938f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[1]/following::button[1]</value>
      <webElementGuid>f0cbf42a-79e3-4963-8ae0-ec4f9e9a5c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::button[1]</value>
      <webElementGuid>81aad0c7-4afa-4926-9fdd-4b0f69f995be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Destinasi / Bongkar'])[1]/preceding::button[2]</value>
      <webElementGuid>f0dedb8b-3040-44a8-b0e4-ac67d1b1ca5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Pick Up / Muat'])[1]/preceding::button[3]</value>
      <webElementGuid>7c3bee53-d288-4046-949d-108dfd593aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button</value>
      <webElementGuid>755adf17-a3ed-409a-9bfb-c2c15c3fc41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'form-submit' and (text() = 'Buat Info Permintaan Muat' or . = 'Buat Info Permintaan Muat')]</value>
      <webElementGuid>9e834759-a222-4208-8cc5-8acf345bd7fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
