<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Terapkan</name>
   <tag></tag>
   <elementGuidId>1d6962e8-19f1-4889-bb21-4f95f3251bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terapkan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='terapkan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>284021ec-40d2-4638-beb4-ea47ec0a7447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn upload-btn ff-demi fs-14 btn-flex m-0</value>
      <webElementGuid>c12b37df-c988-42ce-859c-69dfe32034ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terapkan</value>
      <webElementGuid>5ecfd13e-183e-4a27-8366-6153f516a4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terapkan</value>
      <webElementGuid>e386da47-d219-42f1-a5de-bfbb094819c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terapkan&quot;)</value>
      <webElementGuid>b1a623e3-41c8-4e11-a7ac-e1c6e121068f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='terapkan']</value>
      <webElementGuid>04d42048-846a-4944-bb57-91fee8ee3f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer-invites']/button[2]</value>
      <webElementGuid>aaa96e5e-6834-4e6f-8ae5-cfdb7c76ec07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::button[1]</value>
      <webElementGuid>d9d2f3c6-0315-4c49-aefa-93c392836694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Undang Transporter diluar komunitas Big Fleets'])[1]/following::button[2]</value>
      <webElementGuid>925662a9-7d8f-4f40-9ccd-278365cc7633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitra'])[1]/preceding::button[2]</value>
      <webElementGuid>583171d1-a9a2-49b6-b572-025886808222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transporter'])[2]/preceding::button[2]</value>
      <webElementGuid>47903c69-76d1-4988-b870-72ef345fa0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]</value>
      <webElementGuid>30470d94-4bfd-4a25-987c-48c63cac32c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'terapkan' and (text() = 'Terapkan' or . = 'Terapkan')]</value>
      <webElementGuid>47facf51-0679-4f35-a976-3f66e46392f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
