<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih TransporterMitra</name>
   <tag></tag>
   <elementGuidId>5c568301-b7f5-44af-bc0d-f714b5567d0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pilihTransporter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pilihTransporter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96b2dc09-52ac-48c3-9f5f-6dc264dee76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93f66097-36d9-4509-8727-52c77a038d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary ff-demi btn-primary-new</value>
      <webElementGuid>10b32486-064d-4ff0-aefc-a21de5064b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pilihTransporter</value>
      <webElementGuid>beb76853-ff7e-44d7-8cb9-c54ee3282329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>cc017f03-3af3-4841-b2de-56ffdbea129f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#diumumkanKepada</value>
      <webElementGuid>d252ed9f-0963-4590-bc85-5d1d2c335584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Transporter/Mitra</value>
      <webElementGuid>c92b73f6-37cd-4d96-a095-bf10f3657b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pilihTransporter&quot;)</value>
      <webElementGuid>7656f87d-5e17-4a59-ae0c-ef0c6501842f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pilihTransporter']</value>
      <webElementGuid>c0f5b2c1-cbae-446d-97b0-daf8f9629eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pilihTransporterBtn']/button</value>
      <webElementGuid>580195b5-0b10-42ea-ad90-504884553e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::button[1]</value>
      <webElementGuid>87362984-740b-451a-a806-0d25580db6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[1]/preceding::button[1]</value>
      <webElementGuid>11a25992-8c80-45fa-aa00-551e4f8ea5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Transporter/Mitra']/parent::*</value>
      <webElementGuid>676d619e-63e0-4224-a007-fc7927bdcc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>20d0b0a7-42d7-48c9-86d1-7305510758d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'pilihTransporter' and (text() = 'Pilih Transporter/Mitra' or . = 'Pilih Transporter/Mitra')]</value>
      <webElementGuid>d3b7aff8-17b6-497e-887b-c63fcc5d53d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
