<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jumlah_truck</name>
   <tag></tag>
   <elementGuidId>51255196-deb4-4034-8b7c-843ef1981d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jumlah_truck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jumlah_truck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cf13a15-88ba-4b6f-b519-13d7cefc3597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23c9b92c-b43e-4947-8c46-05132f546b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_truck</value>
      <webElementGuid>0392a90f-3588-41ad-bc70-71ee6456015b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formatNumber form-control fs-12 fc-1b ff-demi</value>
      <webElementGuid>8872027c-e443-41a3-b137-88dc893339f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumlah_truck</value>
      <webElementGuid>625a97d2-36c6-4386-9b40-7a8b6f131270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>21a080cd-a824-434d-a811-b69f07d972ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumlah_truck&quot;)</value>
      <webElementGuid>a5b4e14a-b14f-4c76-a086-fdbe33db2a62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jumlah_truck']</value>
      <webElementGuid>e3d965d3-d73f-43b3-99a7-85d08d2245a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[3]/div/div[2]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>a3b76e2c-d62e-4a2f-8913-ce7131bed98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>492183de-2882-439b-ba49-6e94ed6f6d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jumlah_truck' and @id = 'jumlah_truck']</value>
      <webElementGuid>9beb4d1e-8f4f-4651-b251-47213e0f2a68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
