<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(opsional)_berat</name>
   <tag></tag>
   <elementGuidId>d177fabf-38fa-4e01-abb1-ebf7d6b75e7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;berat&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;form-frontend&quot;]/div/div[4]/div/div[2]/div[2]/div[2]/div/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9fd5fef-a8c0-4433-af8e-9ec5f5150290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6892d01-05a4-452e-bfbc-bf10ebe37071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>berat</value>
      <webElementGuid>13914f1a-d021-4de4-bc46-acfcc9dfdc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-50 fs-10 ff-demi formatBerat satuan_berat h-100</value>
      <webElementGuid>bf91d881-8ed1-48ac-9465-93628e8bdefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-frontend&quot;)/div[@class=&quot;container px-0 d-flex&quot;]/div[@class=&quot;mx-4&quot;]/div[@class=&quot;card card-container&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row mb-20&quot;]/div[@class=&quot;col-lg-9 pl-0&quot;]/div[@class=&quot;row pl-15&quot;]/div[@class=&quot;d-flex pl-0 text-icon-center&quot;]/input[@class=&quot;form-control w-50 fs-10 ff-demi formatBerat satuan_berat h-100&quot;]</value>
      <webElementGuid>abfa7427-ebab-43cb-bd37-89f6aed9e913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='berat']</value>
      <webElementGuid>66585624-089e-4d5d-8c25-4a1d0b5947ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[4]/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>ad85ffb6-4406-46dd-8782-d207b7b8f023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>18c4c2c4-5c65-4124-8702-cffe8d828e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'berat']</value>
      <webElementGuid>da88fdd0-a287-49ec-bcda-fcab7ecd8664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
