<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Colt Diesel Double</name>
   <tag></tag>
   <elementGuidId>93feebc3-3912-4baa-aead-9abc8db5d6df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-jenis_truck-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-jenis_truck-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e22c077-b32f-47a0-9a33-d8eff104397a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>5b92e016-bc88-4a57-84be-ae7fb356ddc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-jenis_truck-container</value>
      <webElementGuid>3a5d0060-9764-4cd4-926b-220e6fd93d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Colt Diesel Double</value>
      <webElementGuid>18808f9b-d921-4711-8317-fc6c961185a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Colt Diesel Double</value>
      <webElementGuid>88c801c8-c6a9-487c-b4a4-790af6eaf363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenis_truck-container&quot;)</value>
      <webElementGuid>87b9855d-f1ea-4025-be62-178c84c4c078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenis_truck-container']</value>
      <webElementGuid>090ce9d2-aab1-4368-902b-50077421299a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jenis_truc_alert']/span/span/span/span</value>
      <webElementGuid>a32ca8dc-fc2a-47b8-90e9-e4710d47bd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bak Terbuka'])[2]/preceding::span[3]</value>
      <webElementGuid>862492d3-2de8-4c09-a235-d7cc4f966889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kapasitas/Dimensi Max'])[1]/preceding::span[9]</value>
      <webElementGuid>29d6f737-b6e7-4305-b9c0-116f2996484f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/span/span/span</value>
      <webElementGuid>d4360bb5-b297-4526-aa72-2fa814443e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenis_truck-container' and @title = 'Colt Diesel Double' and (text() = 'Colt Diesel Double' or . = 'Colt Diesel Double')]</value>
      <webElementGuid>78c15b04-66e0-412a-9f17-85d38923a6bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
