<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(opsional)_deskripsi</name>
   <tag></tag>
   <elementGuidId>af94dd73-878f-4003-b331-1cc6386d51e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;deskripsi&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='deskripsi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ab4542e4-579f-4aac-810a-32f7953aa0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>1b8e8a2e-5e2d-45e0-bb03-594c83974a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>4ea97280-828e-408e-bb93-5ef4de0971db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bb25f95f-daaf-48db-8875-828ee399fbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fs-12 ff-demi fc-1b</value>
      <webElementGuid>c0970115-f957-495b-82eb-0b924ed24ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Catatan Tambahan</value>
      <webElementGuid>d1074ea3-2ade-460d-8abb-49d7554bb8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-frontend&quot;)/div[@class=&quot;container px-0 d-flex&quot;]/div[@class=&quot;mx-4&quot;]/div[@class=&quot;card card-container&quot;]/div[@class=&quot;card-body px-30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 pl-0&quot;]/textarea[@class=&quot;form-control fs-12 ff-demi fc-1b&quot;]</value>
      <webElementGuid>3570880e-26fa-4498-ae72-e4699386ef1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='deskripsi']</value>
      <webElementGuid>c62aac30-a524-4f67-a603-949c37270eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[5]/div/div/div/div[2]/textarea</value>
      <webElementGuid>ec1b9472-bd91-4e9f-b210-56cf00ee91fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/textarea</value>
      <webElementGuid>2593d915-bede-48ca-a913-627df11f6313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'deskripsi' and @placeholder = 'Masukkan Catatan Tambahan']</value>
      <webElementGuid>ed525bf7-5f7d-4827-97c9-66d347b55b3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
