<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__pickUpDetailAddress0</name>
   <tag></tag>
   <elementGuidId>4a0131fe-9ff3-435b-a592-5497857564bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pickUpDetailAddress0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pickUpDetailAddress0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1fa4a592-a934-43b6-9401-bf0ab8023ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pickUpDetailAddress[0]</value>
      <webElementGuid>393422b9-fdb8-4787-909e-1494a72b37b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>b43d17fd-b9d3-4fa3-8eb7-31255445909c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1fd17acd-0eaa-4a65-83b2-e38a1850c140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-address</value>
      <webElementGuid>5000753d-49ca-48ec-9cc5-8ff94d73841a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pickUpDetailAddress0</value>
      <webElementGuid>d210973f-abfd-461d-a5ca-c553fc6f8393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Lokasi</value>
      <webElementGuid>41237de7-f606-4626-9cc4-c47d0ab24c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pickUpDetailAddress0&quot;)</value>
      <webElementGuid>1b7d77c6-9852-4eb0-a0dd-a0cf9f8cbe74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pickUpDetailAddress0']</value>
      <webElementGuid>9d1ef6b4-9d5a-4898-9854-66ff3818fd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div/div/div[2]/div[4]/div/div[2]/div[2]/textarea</value>
      <webElementGuid>e95c3d26-92f3-408d-a07f-e6f3a29ff070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>84bd60cf-5f17-4ae7-bdd4-87194d82eb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'pickUpDetailAddress[0]' and @id = 'pickUpDetailAddress0' and @placeholder = 'Pilih Lokasi']</value>
      <webElementGuid>f6d0c077-148d-46c2-b41b-672f995dd1ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
