<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>1988f78e-72ad-4b75-b1d1-8b06ac5c8206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnNextTermCondition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnNextTermCondition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0cdea15-80ce-42da-a8d1-78b1ad1aeb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnNextTermCondition</value>
      <webElementGuid>9a7153a4-4017-4d4a-b408-28abb677d333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-alt-az ff-demi-az fc-17-az</value>
      <webElementGuid>cca1ae4f-5eb7-4444-ac8f-5f4153c5fde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Selanjutnya
                    </value>
      <webElementGuid>9f7cee9b-6164-4d5c-923c-acf2a463d48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnNextTermCondition&quot;)</value>
      <webElementGuid>9abce739-970e-4be8-ab35-1968ebf15be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnNextTermCondition']</value>
      <webElementGuid>802e7f2d-a381-401b-a83c-26658c9c7239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerkotakkananterms']/div[4]/button</value>
      <webElementGuid>8bcee213-a0c8-4b8c-9e49-045467db90b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda belum checklist ketentuan ini'])[4]/following::button[1]</value>
      <webElementGuid>2daf225e-61bc-4b10-b075-19ec905a32a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda belum checklist ketentuan ini'])[3]/following::button[1]</value>
      <webElementGuid>8422c1ed-8a07-44c4-ab8b-c96474148013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maaf Sedang Terjadi Gangguan Teknis'])[1]/preceding::button[2]</value>
      <webElementGuid>9a9fd5e4-b3be-46a9-bf26-b90ab9a3f9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KODE ERROR : 101'])[1]/preceding::button[2]</value>
      <webElementGuid>73eb2743-05e6-45e7-80f8-415e729c774d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>381d9a1c-a242-47cb-a178-b309d021e530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e0008a50-e5b1-47e8-89a8-c501024c94e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnNextTermCondition' and (text() = '
                        Selanjutnya
                    ' or . = '
                        Selanjutnya
                    ')]</value>
      <webElementGuid>8c14d1ac-b037-43a6-9971-0ba532908334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
