<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Anda belum checklist ketentuan ini_terms2</name>
   <tag></tag>
   <elementGuidId>fa17486c-132c-46e6-ab73-a3b2d12f565f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='terms2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08abeda9-a47d-4961-b0aa-54d55ae42b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0035f5ea-7a6b-4b48-ae35-73cbcaa105d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-checkbox-terms</value>
      <webElementGuid>6e55a72b-cd8e-45df-8f23-925a791fb8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms2</value>
      <webElementGuid>0e718e12-7476-4bf9-85a6-269c46a359b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms2&quot;)</value>
      <webElementGuid>51208351-b39f-4736-8fbd-cca9cfaa8808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='terms2']</value>
      <webElementGuid>b441304f-bcc9-49f7-8669-b2f682b2ae12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divcb']/input)[3]</value>
      <webElementGuid>5603a97d-b4b2-400c-805d-0354d5168c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b1c91f6f-9212-4d42-821d-cef8c47984f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'terms2']</value>
      <webElementGuid>ce46a3ab-20c5-4577-b80f-a636a6b99410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
