<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan OTP_OTPField6</name>
   <tag></tag>
   <elementGuidId>e89c8457-5e21-4316-b590-1e367047ee8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OTPField6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OTPField6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>245b8391-a14c-4b4c-8a5f-a09bb71613f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input-general-number-az input-text-otp ff-bold-az fs-14 text-black ta-center line-height-16-8</value>
      <webElementGuid>c7a61768-44f2-4a53-9211-14ccfb5caa9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTPField6</value>
      <webElementGuid>783b4dbc-cac5-4644-b08e-160b76de817e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]</value>
      <webElementGuid>9713ca66-dc9a-4f52-a3de-4c1216393422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc531584-a25e-4a6b-9112-e553c03bd93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTPField6&quot;)</value>
      <webElementGuid>620f3887-b906-42ee-8c0b-6beb83c0968e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OTPField6']</value>
      <webElementGuid>93f13bcb-e72e-43ee-97b3-121ed1870ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>b696d7d1-63df-40e7-bd54-1e4c2a55f0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OTPField6']</value>
      <webElementGuid>d9b18202-bb27-4ee2-80df-5fc091db5d15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
