<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk Bigfleets</name>
   <tag></tag>
   <elementGuidId>77d11447-6376-4401-b605-f08954c638de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tombolPromo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tombolPromo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5cfe23b-dddd-44cc-8b61-87de1752ec00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az</value>
      <webElementGuid>2785c0b1-afbc-49f7-90cf-1937b40e4525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tombolPromo</value>
      <webElementGuid>e780f724-74f1-4f17-8b3a-73ecd24c9cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirectPromo()</value>
      <webElementGuid>f15c0ea1-4259-421f-a132-f5f9b3f13af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk Bigfleets</value>
      <webElementGuid>ec8239e1-f461-425b-a9fe-161d95713126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tombolPromo&quot;)</value>
      <webElementGuid>d9c3b934-8ed8-4d89-aec0-bbd865bc2e6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tombolPromo']</value>
      <webElementGuid>dc15bc9e-2522-4a44-9127-4e7895a40d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopUpPromo']/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>79adf899-fe14-47e0-b6b9-17b42472d016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Berlaku selama periode 17 Juli 2023 - 17 Oktober 2023'])[1]/following::button[1]</value>
      <webElementGuid>d469b299-df5b-4f23-bd5d-bb3101d8993d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo Menarik'])[1]/following::button[1]</value>
      <webElementGuid>e77c37a6-5b0a-48a7-9122-72bbeb52563a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangan tampilkan lagi'])[1]/preceding::button[1]</value>
      <webElementGuid>d12c3fcc-5698-436b-9441-8213b9948330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambil Kesempatan Anda Mencoba muatmuat Sekarang'])[1]/preceding::button[2]</value>
      <webElementGuid>a9e0c9bb-1468-4ba3-a1e5-6bac25c5d97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk Bigfleets']/parent::*</value>
      <webElementGuid>47210852-e08e-4653-a9d4-02253660d9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>afc59253-7777-4f00-a90a-3399b8c2b4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tombolPromo' and (text() = 'Masuk Bigfleets' or . = 'Masuk Bigfleets')]</value>
      <webElementGuid>2b9ca48f-9670-4916-8668-145e9d72d0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
