<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail Riwayat Arsip</name>
   <tag></tag>
   <elementGuidId>d1994a27-875c-4635-a381-1ac008a23823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[11]/div[2]/div[2]/div/div/div[6]/div[1]/div[1]/div[3]/div[2]/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tombol-primary-az.detail-history.detail-page.tombol-salin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe5b36d0-1e0f-42ae-b61a-69e025a8238d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aktifitas</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>de1ddc9f-77a9-4c70-8cc2-6ed80d5b831a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activitymenu</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>96c2e68e-aa79-462f-9b3a-bea22e72fc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8d0b1b8b-b624-4ecc-aa66-00c79f2262f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>174ac266-90e7-408e-99c0-f5ac01dc10c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az detail-history detail-page tombol-salin</value>
      <webElementGuid>55d63f41-ba04-4c44-851f-d708d310e1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Detail
											</value>
      <webElementGuid>7dbecc2d-71e7-437d-9e91-1eb410002296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-data-kontrak-daftar-kontrak&quot;)/div[1]/div[@class=&quot;d-flex flex-row justify-content-between align-items-center&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;tombol-primary-az detail-history detail-page tombol-salin&quot;]</value>
      <webElementGuid>fb883d3e-35af-4ad5-b8ed-27c401e2e474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-data-kontrak-daftar-kontrak']/div/div[3]/div[2]/button[4]</value>
      <webElementGuid>33e6d28e-c4bf-4f80-a563-232c5ddcd132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi'])[1]/following::button[1]</value>
      <webElementGuid>a9d4090f-aa5d-48ca-b838-49462609b831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salin'])[1]/following::button[2]</value>
      <webElementGuid>fded2cf6-e7a1-48ea-9bb0-4d17f72d90f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>bbee22da-9f90-4c8c-92c5-be2e41dec208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>110aa882-5b1a-4eac-a20d-3a8a23ba6e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
												Detail
											' or . = '
												Detail
											')]</value>
      <webElementGuid>57932a3b-6e7b-4f04-a8ff-65c1df423983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
