<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sort_TabDaftarKontrakPenawaran_NoReferensi</name>
   <tag></tag>
   <elementGuidId>07fc02c6-5611-4a32-937e-f5c8c1b25206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[11]/div[1]/div[2]/div[2]/div[2]/div[2]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tombol-primary-az.detail-history.detail-page.tombol-salin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3913d8e7-01c8-4460-8cc6-b1e23ff348fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aktifitas</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>f949893f-b9cc-49fb-9c51-730a81c828da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activitymenu</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c4c1f8f-3681-4b94-a34b-2ade6723e6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>848eb1a3-9f1d-4ec2-97a8-0ab6547ca36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>854d3d3a-f630-4a40-ac24-d17f91d19ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az detail-history detail-page tombol-salin</value>
      <webElementGuid>0c29c290-ab59-4106-aa27-2e0deaf09551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Detail
											</value>
      <webElementGuid>b763a54d-1cf2-441b-9b7d-310116aeea0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-data-kontrak-daftar-kontrak&quot;)/div[1]/div[@class=&quot;d-flex flex-row justify-content-between align-items-center&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;tombol-primary-az detail-history detail-page tombol-salin&quot;]</value>
      <webElementGuid>ab5e24d0-0f50-4000-9eaa-793738d58212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-data-kontrak-daftar-kontrak']/div/div[3]/div[2]/button[4]</value>
      <webElementGuid>4e8f9998-9122-4bd9-bc2b-1536f24d0610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi'])[1]/following::button[1]</value>
      <webElementGuid>beb29eb8-a71c-4f7b-83ca-0ea123d9b6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salin'])[1]/following::button[2]</value>
      <webElementGuid>e52fdcf9-260a-4a7e-a142-d75e74bebeb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>d5cda4aa-428b-4567-ae9c-892c8e346b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>618e8799-a60b-443d-8c0e-92cc83bc217d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
												Detail
											' or . = '
												Detail
											')]</value>
      <webElementGuid>555db78a-d41a-45a4-bb1a-1f1666966e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
