<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sort_TabDaftarKontrakPenawaran_TanggalDisetujui</name>
   <tag></tag>
   <elementGuidId>4f958324-111f-4a91-bd9f-b597ac633bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[11]/div[1]/div[2]/div[2]/div[2]/div[2]/div/div/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tombol-primary-az.detail-history.detail-page.tombol-salin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>939cb5ff-f43e-4633-9cfc-bf01c6ec524e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aktifitas</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>0fee04b6-2952-473d-89d6-dcea78a19a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activitymenu</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f2b06a8-b312-4872-b9d3-e7ef0929ab33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7b3eab0f-f529-4e35-9ff3-0e257b2384d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>e99a2f67-ffa8-4435-aa11-cc95f6ec1f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az detail-history detail-page tombol-salin</value>
      <webElementGuid>8e29bfe0-837b-46c3-932d-7dbde94e76c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Detail
											</value>
      <webElementGuid>12be6ee8-56c6-4757-b9e3-bc8649dccdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-data-kontrak-daftar-kontrak&quot;)/div[1]/div[@class=&quot;d-flex flex-row justify-content-between align-items-center&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;tombol-primary-az detail-history detail-page tombol-salin&quot;]</value>
      <webElementGuid>41ff0a7d-649e-4d0b-9ca4-37e6136ffe49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-data-kontrak-daftar-kontrak']/div/div[3]/div[2]/button[4]</value>
      <webElementGuid>68f4f55f-eec6-4f70-9e57-6a093235c843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi'])[1]/following::button[1]</value>
      <webElementGuid>d690559e-c797-4f12-becc-ca59d49b01f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salin'])[1]/following::button[2]</value>
      <webElementGuid>1170a91e-2466-4e64-a82e-68782fdbce0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>8b815418-e62e-427b-bcd5-ab0bf9857707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>83e511ec-897e-4590-9fc2-bb59ffdb3e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
												Detail
											' or . = '
												Detail
											')]</value>
      <webElementGuid>5dcd2784-c837-4c31-b868-69a7e7b655dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
