<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail Kontrak</name>
   <tag></tag>
   <elementGuidId>0c87ed10-cc8b-4b76-aff8-b92f02c63cc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-data-kontrak-daftar-kontrak']/div/div[3]/div[2]/button[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tombol-primary-az.detail-history.detail-page.tombol-salin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>233cf34f-0424-46f3-bfc6-fe3521b52386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aktifitas</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>bd4726d9-83e2-49fe-9489-9e6b773b9d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activitymenu</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>df7de422-4892-4b6f-865e-65511bec6dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>68fe56b6-3ac6-4665-8871-6557459769ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>f95093bb-2d8b-43fc-be51-103493f07f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az detail-history detail-page tombol-salin</value>
      <webElementGuid>f507252e-04e1-4807-9dd2-6bf7aca796ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Detail
											</value>
      <webElementGuid>85679da9-9e7e-463c-9529-eafb38f4647c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-data-kontrak-daftar-kontrak&quot;)/div[1]/div[@class=&quot;d-flex flex-row justify-content-between align-items-center&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;tombol-primary-az detail-history detail-page tombol-salin&quot;]</value>
      <webElementGuid>20637948-5e99-4e2f-b719-395006eb1779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-data-kontrak-daftar-kontrak']/div/div[3]/div[2]/button[4]</value>
      <webElementGuid>de8938ed-53bd-4017-9d2b-29d1670420dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi'])[1]/following::button[1]</value>
      <webElementGuid>1bc37bde-6ed9-4b46-999a-2e19b148d4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salin'])[1]/following::button[2]</value>
      <webElementGuid>3d92cbd4-3da8-4824-97b1-5a5f8198ee19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>e384f4c3-71cd-4fae-814f-6dee9182d488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>c6f780cc-9653-43c5-8eb9-8fd4654b5078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
												Detail
											' or . = '
												Detail
											')]</value>
      <webElementGuid>f0d79139-bb8a-450d-b28a-78294f3142a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
