<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail Persetujuan</name>
   <tag></tag>
   <elementGuidId>33784f5a-e630-4844-9b8b-4cbb4e0598b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;list-data-konfanda&quot;]/div[1]/div/div[3]/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tombol-primary-az.detail-history.detail-page.tombol-salin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3710905b-61d8-461d-9cd9-daf5c9dbd7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aktifitas</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>5fbae197-9d52-48c5-b573-89f40f2acfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activitymenu</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3facd64b-8f80-4ea1-80c9-2865463b817a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d0a21250-2505-41a9-8649-2093b43f368d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-token</name>
      <type>Main</type>
      <value>pDJK8wOD3yHE0kanJ41ORhtjgE1mKwLty0xacfn13EZuIV98F62HAkSTfwbVqeg3NGhYEkxkB2Afgj79HYvOb4y3meI-</value>
      <webElementGuid>9ec7b508-eb96-4bda-b374-d239be04eaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az detail-history detail-page tombol-salin</value>
      <webElementGuid>80860da2-264e-4dba-b1ef-788897e8a81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Detail
											</value>
      <webElementGuid>87dd57d0-9920-49eb-a7e8-e44c4e59f138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-data-kontrak-daftar-kontrak&quot;)/div[1]/div[@class=&quot;d-flex flex-row justify-content-between align-items-center&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;tombol-primary-az detail-history detail-page tombol-salin&quot;]</value>
      <webElementGuid>e74d5d03-d1ab-4296-84f6-4410174f156d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-data-kontrak-daftar-kontrak']/div/div[3]/div[2]/button[4]</value>
      <webElementGuid>25a9280f-8db0-482b-b112-ff7334d59244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi'])[1]/following::button[1]</value>
      <webElementGuid>bd352a01-b7c7-4be9-a451-a7e77d892d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salin'])[1]/following::button[2]</value>
      <webElementGuid>f4de9840-81fc-483a-b46d-ecf56d9f1584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>a34bbf19-d0c7-4d91-99b2-d8291707a847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>1689b7cf-2de8-4bfa-9295-ab673012abf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
												Detail
											' or . = '
												Detail
											')]</value>
      <webElementGuid>247f96bb-462d-485b-9960-42ca1a6fba99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
