<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dimensi Maksimum_dimensi_panjang</name>
   <tag></tag>
   <elementGuidId>ba375078-8c40-4345-b01d-36e078179bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dimensi_panjang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dimensi_panjang']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>363bc2e6-d641-425d-a88b-51f3d392518c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad8c88b9-ff52-4050-b743-ab011156907f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>101c7ba3-4ec4-4630-9755-e885c20cacd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-input-form mr-14 formatDimensiArmada satuan_berat_dimensi</value>
      <webElementGuid>3416a7f7-ae9d-434e-8be9-f8080b9c7adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dimensi_panjang</value>
      <webElementGuid>dbed91ff-d2fd-4ce4-813c-76ae811c352a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dimensi_panjang</value>
      <webElementGuid>99c23ac2-c92f-4279-a62b-01c9a6418a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dimensi_panjang&quot;)</value>
      <webElementGuid>24cf1b87-a4ee-4594-abeb-9200883944bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dimensi_panjang']</value>
      <webElementGuid>15241ff5-d3c2-413a-be84-dd22fe599667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_dimension']/td[2]/input</value>
      <webElementGuid>46f93ee8-a0bf-445a-8944-81ec859df072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>d808610b-9d57-47d5-86fb-fcd7ee86c489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '0' and @name = 'dimensi_panjang' and @id = 'dimensi_panjang']</value>
      <webElementGuid>b6636169-ff2e-4043-b18f-805167776d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
