<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Masuk</name>
   <tag></tag>
   <elementGuidId>64b52396-5c11-4ab0-bd43-1d29960b36bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnMasuk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnMasuk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43039e73-94bc-458d-a182-4da74b831f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-daftar</value>
      <webElementGuid>3e5b83c9-f318-4232-b9ef-8ec8b9ac3a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnMasuk</value>
      <webElementGuid>b7a397e9-8a86-4f15-92b0-102e417160bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Masuk
                </value>
      <webElementGuid>21f4ef79-71cc-460a-ac8f-9e1cc65e4d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnMasuk&quot;)</value>
      <webElementGuid>3bc5cdb1-4dd3-4816-be27-7d8921e3bc95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnMasuk']</value>
      <webElementGuid>443a3487-34fe-4417-b13e-5664c7bf6d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerkotakkanan']/div[9]</value>
      <webElementGuid>53402418-f272-4a45-a13c-1937aaea0b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/following::div[1]</value>
      <webElementGuid>42a31b4e-8a55-4da6-9eab-2f727ad5c3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tetap Masuk'])[1]/following::div[1]</value>
      <webElementGuid>49dd2dd7-1b97-4342-96fa-e2cf7168e9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Punya Akun?'])[1]/preceding::div[1]</value>
      <webElementGuid>cba6ebeb-937a-4a00-b27e-4d187143e9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>59e11b73-9dee-4f1d-bade-834676184bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnMasuk' and (text() = '
                    Masuk
                ' or . = '
                    Masuk
                ')]</value>
      <webElementGuid>606629f4-1059-4d01-94e5-60ba13a276a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
