<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Transporter</name>
   <tag></tag>
   <elementGuidId>ea96a1f5-1a3e-4fe5-92fe-903eac389d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Shipper > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Shipper']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0eaba03-44a1-445f-bfbe-06213c7af40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://bf.muatmuat.com/bigfleets/menu_shipper_show_transporter</value>
      <webElementGuid>47056eb2-68c0-47e2-b453-a3fccaf7e15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transporter</value>
      <webElementGuid>7604d2f2-5812-4852-ab56-7e235e3fa390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Shipper&quot;)/a[1]</value>
      <webElementGuid>7bbe02b8-5638-4d4c-ba42-3e2e07f4c601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Shipper']/a</value>
      <webElementGuid>9599f08b-6085-40f3-bfb5-d9b026f4daf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Transporter')]</value>
      <webElementGuid>e38ff2a8-e214-485b-aeda-da87fcb3257c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscription'])[1]/following::a[1]</value>
      <webElementGuid>72d87282-4b21-4aca-96f6-a015c1f656e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[2]</value>
      <webElementGuid>1defdc53-5838-436c-81c3-00fd8f0830c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen Mitra dan Grup'])[1]/preceding::a[1]</value>
      <webElementGuid>4711d366-b401-450b-8112-9464804d3756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontrak Harga'])[1]/preceding::a[2]</value>
      <webElementGuid>e38ea402-2524-4755-bbfa-9a3b31f71a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transporter']/parent::*</value>
      <webElementGuid>98a56c10-ac02-49b9-b820-49b085aef698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://bf.muatmuat.com/bigfleets/menu_shipper_show_transporter')]</value>
      <webElementGuid>faa3c14c-1f8c-4287-9da9-7524379de1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>c27d8b41-8cf3-4b29-b070-b8bb9e41a7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://bf.muatmuat.com/bigfleets/menu_shipper_show_transporter' and (text() = 'Transporter' or . = 'Transporter')]</value>
      <webElementGuid>958cff20-cb3d-4612-9c26-ebf737a1541d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
