<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>712453c1-f99d-4613-816e-9ddc1e3f9f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lblSelanjutnya']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lblSelanjutnya</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4c601117-d943-4fb3-bed0-3b6dc49c68f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl-btn-selanjutnya</value>
      <webElementGuid>94bda210-dbaa-4891-ae5e-6c4cdfddb4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lblSelanjutnya</value>
      <webElementGuid>6266be49-dffa-4262-8a39-dd43e295b4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>b9da2361-4405-46e4-a217-568db4163090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lblSelanjutnya&quot;)</value>
      <webElementGuid>649d2d46-3334-4c36-9acc-eb45d70b90ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lblSelanjutnya']</value>
      <webElementGuid>c13f30e3-ef30-49d9-a04a-eb60fc073e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BtnNextTermCondition']/span</value>
      <webElementGuid>6c8e1815-ada9-4d6b-b5f5-049c0348b2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda belum checklist ketentuan ini'])[1]/following::span[1]</value>
      <webElementGuid>05bb0d54-e396-499b-a136-ff8ce77a48b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password Baru belum diisi'])[1]/following::span[1]</value>
      <webElementGuid>5c42a377-13a9-4f4a-8f3c-f926fe42b45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi Pengguna'])[1]/preceding::span[1]</value>
      <webElementGuid>28dad610-b911-441d-a32c-4508425dd9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>57f1a6e7-68d6-4147-82c4-cd4f80c0ab50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div[5]/div/span</value>
      <webElementGuid>ffb2542a-ce9e-4168-873e-b9a2782bb884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lblSelanjutnya' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>2546f898-72bb-417d-a2e1-f7c7c1f204d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
