<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hubungi</name>
   <tag></tag>
   <elementGuidId>a3d38812-118c-48d0-b2f3-fe6db7e4b344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonHubungi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonHubungi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ba3250a-3a44-4652-b251-c12bf519c76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover buttonHubungi</value>
      <webElementGuid>e26bf487-039d-4b02-bd7c-ee4e701784f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonHubungi</value>
      <webElementGuid>9b19a867-401d-4e27-b4d9-6fe514985c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi</value>
      <webElementGuid>379b58e7-0883-440d-abe9-50d1457c9152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonHubungi&quot;)</value>
      <webElementGuid>5406a733-da8c-4115-abdf-fe58924f4286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonHubungi']</value>
      <webElementGuid>0d4226d9-7798-427e-9532-27dbd57769e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Briko Batu Bata'])[1]/following::button[1]</value>
      <webElementGuid>d2cd9a57-0741-45c2-af7b-80639bfbe7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Barang Lainnya Dari Penjual'])[1]/preceding::button[1]</value>
      <webElementGuid>f31ca62c-d472-4eae-a023-5351bd979ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hubungi']/parent::*</value>
      <webElementGuid>1b5deb23-76fe-408c-b7cd-ee864ff525e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div[3]/button</value>
      <webElementGuid>64a99c6f-5308-4a2c-96fe-20f65de44f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonHubungi' and (text() = 'Hubungi' or . = 'Hubungi')]</value>
      <webElementGuid>fd9ea92e-851a-4483-9ad3-2cd105e3b5ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
