<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan OTP_OTPField6</name>
   <tag></tag>
   <elementGuidId>2c087daf-84b9-41ca-9fe7-857647cf3256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OTPField6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OTPField6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bd54891-a5f0-4e73-a19a-8e1d6dfc143a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input-general-number-az input-text-otp ff-bold-az fs-14 text-black ta-center line-height-16-8</value>
      <webElementGuid>c753d331-12d4-4092-8824-dd1eaa1e8262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTPField6</value>
      <webElementGuid>665607ee-a8e4-457e-9349-f0c0fd75cbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]</value>
      <webElementGuid>f9af2190-3b64-4527-9a4f-803475dd5877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>49e9f5a2-0f21-4a3d-9fb0-881241683999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTPField6&quot;)</value>
      <webElementGuid>84d576de-37a0-4cca-832e-c4e8d7e54130</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OTPField6']</value>
      <webElementGuid>47f6e7df-0459-48c6-b398-0d22ec2d4ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>c759a833-e504-4a39-9281-75f9e92fe496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OTPField6']</value>
      <webElementGuid>3dbe781b-0f37-4446-9065-e3e951c16934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
