<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan OTP_OTPField4</name>
   <tag></tag>
   <elementGuidId>94d8b36f-5c65-4f87-ab22-4bc622c72f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OTPField4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OTPField4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dad4e16e-86ce-4fd1-b5e7-8b864717e421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input-general-number-az input-text-otp ff-bold-az fs-14 text-black ta-center line-height-16-8</value>
      <webElementGuid>b138acc6-b521-4636-8d93-165d0c9dd351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTPField4</value>
      <webElementGuid>c39c61b9-4d39-49ca-97ad-93dd33035b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]</value>
      <webElementGuid>e21fbb5b-9567-44d8-b606-ea3091c103a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d5e1df6d-bfdd-4369-b5a2-dda7b43e0afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTPField4&quot;)</value>
      <webElementGuid>1d9c0440-b977-404f-9fa2-098be4edd400</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OTPField4']</value>
      <webElementGuid>33b7926a-6210-401e-8bbd-99ee1f04ae03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>184e3150-bbb3-41cb-b919-5d7442da7949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OTPField4']</value>
      <webElementGuid>880622d6-bbbc-4c8b-a837-984f24ce8bb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
