<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Box</name>
   <tag></tag>
   <elementGuidId>fa468b39-a471-4dc3-9d93-c48a80b4ad2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='scroll-custom-az']/a[2])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>004c09ae-dd24-4504-8325-fd978775edee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item dropdown-item-list-sub-user ff-mediu m-az fs-12-az fc-black-az</value>
      <webElementGuid>2e5dedb1-cedc-45e8-9a35-f80061821a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Box</value>
      <webElementGuid>4b534215-72ab-410b-b133-daf7eedb5de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-vue&quot;)/div[2]/div[@class=&quot;form-kontrak-container rutetransactionviewvalidate&quot;]/div[@class=&quot;form-kontrak-content-container&quot;]/div[@class=&quot;form-kontrak-column&quot;]/div[2]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;ff-demi-az&quot;]/div[@id=&quot;dropdownPilihHover&quot;]/div[@class=&quot;dropdown-menu show&quot;]/div[@id=&quot;scroll-custom-az&quot;]/a[@class=&quot;dropdown-item dropdown-item-list-sub-user ff-mediu m-az fs-12-az fc-black-az&quot;]</value>
      <webElementGuid>4fb89944-8a9c-4402-b850-173d151356fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='scroll-custom-az']/a[2])[2]</value>
      <webElementGuid>27bc6833-5eea-43f0-88df-67af2bd96ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Box')]</value>
      <webElementGuid>3a9c4ad6-19f0-48f7-9984-fe472d8e00b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bak Terbuka'])[1]/following::a[1]</value>
      <webElementGuid>ff46eef2-cb7a-4e53-95b2-a4921fc6f962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Jenis Carrier'])[1]/following::a[2]</value>
      <webElementGuid>5875601d-8066-4fac-a1cd-f4ca5a79a9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dump'])[1]/preceding::a[1]</value>
      <webElementGuid>413798a7-fe9a-4fb8-8ce1-1341cbed8d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Los Bak / Flatbed'])[1]/preceding::a[2]</value>
      <webElementGuid>45ab51e4-8c6b-4a40-ade3-89a9bf243273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Box']/parent::*</value>
      <webElementGuid>111689bb-2116-4fd9-b6de-6a424144343d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/a[2]</value>
      <webElementGuid>3882ed7f-d6e7-4bab-8263-c54e0bb1a52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Box' or . = 'Box')]</value>
      <webElementGuid>5a2937eb-fccd-48ce-a858-31561c88cbb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
