<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat KontrakPenawaran</name>
   <tag></tag>
   <elementGuidId>4a0fe2fc-008f-4486-b548-ca9d3336702b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buat-kontrak</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buat-kontrak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf3b401f-0e26-48d9-a68c-3cd94b6de78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5192993f-dc4d-447c-b325-18dea8908049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buat-kontrak</value>
      <webElementGuid>88e859b3-c5f8-49c3-bf80-d6ea47859696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az</value>
      <webElementGuid>9acb45a1-c44c-4745-8f59-9484ea3b3854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Buat Kontrak/Penawaran </value>
      <webElementGuid>aee3d412-5dcd-4383-9e87-5b9268c4ce17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buat-kontrak&quot;)</value>
      <webElementGuid>bc18a738-2806-4fd4-b115-fb53965977a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buat-kontrak']</value>
      <webElementGuid>c78bf9f7-216f-4a88-8b89-cc40da02cdfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[2]/following::button[1]</value>
      <webElementGuid>7d2c0ae3-6812-47b2-b269-e5f54d1f8f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontrak dan Penawaran'])[2]/following::button[2]</value>
      <webElementGuid>dc176915-af1f-45a4-9e35-a5815010a251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan'])[1]/preceding::button[1]</value>
      <webElementGuid>89099a21-e286-4868-9f69-5d35d020a1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Kontrak Harga'])[1]/preceding::button[2]</value>
      <webElementGuid>214a7cb4-acd5-488f-bdc3-b5dd3c6ed753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat Kontrak/Penawaran']/parent::*</value>
      <webElementGuid>a5b2c30f-39fc-4514-afc5-3dd1bd5428eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>5688648d-e059-412a-81c8-86a308cbf3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'buat-kontrak' and (text() = ' Buat Kontrak/Penawaran ' or . = ' Buat Kontrak/Penawaran ')]</value>
      <webElementGuid>86840c89-ae17-4208-92a6-15be2dff2479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
