<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kec. Gambir, Kota Jakarta Pusat</name>
   <tag></tag>
   <elementGuidId>81a24e40-30fb-428b-a8b7-3252876d5512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PasangIklanForm']/div[11]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ff-medium.fc-1B.fs-12.mt-8.click-location-dropdownGoogle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fef5f9e6-1cb6-45dd-8e35-83747307a270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Kec. Gambir, Kota Jakarta Pusat</value>
      <webElementGuid>af009ec0-8570-42c4-8100-aed1102cb454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle</value>
      <webElementGuid>afee8ecb-b3c1-45e2-82c8-77762b277b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kec. Gambir, Kota Jakarta Pusat</value>
      <webElementGuid>a187741e-d21c-41a8-8aa1-3d9d732b5266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;parentDropdownGoogle d-flex flex-column&quot;]/div[@class=&quot;bg-white resultDropdown&quot;]/div[@class=&quot;ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle&quot;]</value>
      <webElementGuid>a91e432d-fbe7-401e-ac22-6228ec91189c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[11]/div/div[3]/div</value>
      <webElementGuid>2da2c9ca-dd85-45e8-a2d9-21f904854dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::div[3]</value>
      <webElementGuid>ceb7fbc2-3a06-4528-9bc2-f005655bfe5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kec. Gambir, Kota']/parent::*</value>
      <webElementGuid>ced8b47b-3e0e-4989-a6a3-b09403cc36fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[3]/div</value>
      <webElementGuid>1cda2d45-a38b-4a38-bf0e-ee64d4543720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kec. Gambir, Kota Jakarta Pusat' or . = 'Kec. Gambir, Kota Jakarta Pusat')]</value>
      <webElementGuid>7d557244-60de-4bfe-af6d-7b9a4bac8549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
