<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Terapkan</name>
   <tag></tag>
   <elementGuidId>5f499fd2-cddc-416f-8f03-b3c99b44abe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;terapkan('pickup')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mr-0.tombol-special-az</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b24a09c4-63fb-4713-80b3-1cbb5902521b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-0 tombol-special-az</value>
      <webElementGuid>3d6fdeb4-0462-4e27-bc13-12cec03e20e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>terapkan('pickup')</value>
      <webElementGuid>2c0d7d7d-60eb-497f-a4ee-ed4a0cd947b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3b2c2bbe-8a39-4544-96d8-8c337ca282a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Terapkan</value>
      <webElementGuid>0f12a80a-771e-444b-b96a-51dbd3e74c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_kecamatan_pickup&quot;)/div[@id=&quot;modal-kecamatan&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body d-flex flex-column&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/button[@class=&quot;mr-0 tombol-special-az&quot;]</value>
      <webElementGuid>5b18ae48-0d45-4ba0-9f54-2dcde13dc91a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;terapkan('pickup')&quot;]</value>
      <webElementGuid>2e1da46c-eafe-4459-8694-7b081cb3acae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-kecamatan']/div/div/div[4]/button[2]</value>
      <webElementGuid>ea3db88b-1a4d-4a1e-a448-12293ce7c50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[3]/following::button[1]</value>
      <webElementGuid>880d3fe7-b735-4bcc-b78b-e758e36118e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wonokromo'])[1]/following::button[2]</value>
      <webElementGuid>7104347d-3cd4-4d45-8ab4-03912b2e8bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[2]/preceding::button[1]</value>
      <webElementGuid>9688ca79-4d1c-401b-ba9a-92e187208b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Kecamatan'])[3]/preceding::button[1]</value>
      <webElementGuid>28dc0aed-ad1d-44c2-9e49-b5e0d9d23a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terapkan']/parent::*</value>
      <webElementGuid>2e0cf5ac-5c99-47a1-932e-bc8506355dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>80052b3c-5718-4ac9-a559-8ddf99231f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Terapkan' or . = ' Terapkan')]</value>
      <webElementGuid>490fcef1-d29b-410f-9282-d6b77df576be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
