<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kecamatan_destination-semua</name>
   <tag></tag>
   <elementGuidId>c5f5a24e-aa5a-4c17-a624-faf7462c27c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='destination-semua']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#destination-semua</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6654b91-dd7d-4e72-83f7-5f2354a5cf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>destination-semua</value>
      <webElementGuid>5f3bdf34-7ff7-4290-806e-0e9da51b4e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-checkbox custom-checkbox kecamatan-checkbox kecamatan-checkbox-all</value>
      <webElementGuid>623acdf8-b00f-4921-ba30-8c2bf7216bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>6e9792bd-458a-4805-a455-e2b57fc636d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a61f17c8-4b64-4e06-815e-64655ed3d376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Semua Kecamatan</value>
      <webElementGuid>5081ad77-4a64-431e-922e-f8a018880817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;destination-semua&quot;)</value>
      <webElementGuid>b5c39af4-2fa7-47af-a2a0-b373d606946e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='destination-semua']</value>
      <webElementGuid>04f39fbd-17a9-4831-a85d-04272f968ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='modal-kecamatan']/div/div/div[3]/div/div/input)[2]</value>
      <webElementGuid>23ce7f88-8196-4623-b8aa-06f4aa1e2b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>2725f613-f054-4906-84c5-23aab06eb06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'destination-semua' and @type = 'checkbox']</value>
      <webElementGuid>9aa22795-8cd7-4c00-ab63-49796d79805c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
