<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kec. Gambir, Kota Jakarta Pusat</name>
   <tag></tag>
   <elementGuidId>feda685f-d885-408b-b2f8-656c8eda229e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ff-medium.fc-1B.fs-12.mt-8.click-location-dropdownGoogle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PasangIklanForm']/div[9]/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c39afe78-eebf-4893-9d2b-26c09a2ca135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Kec. Gambir, Kota Jakarta Pusat</value>
      <webElementGuid>29915559-2315-4d7e-98d2-7dcd7f15aa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle</value>
      <webElementGuid>e338acc5-0a64-4d91-ab2f-cfddf7912a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kec. Gambir, Kota Jakarta Pusat</value>
      <webElementGuid>6de3e49e-2969-4bec-a49f-4cb7e9abc236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;parentDropdownGoogle d-flex flex-column&quot;]/div[@class=&quot;bg-white resultDropdown&quot;]/div[@class=&quot;ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle&quot;]</value>
      <webElementGuid>086cb71c-cabe-419e-873e-65fc835d5105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[9]/div/div[3]/div</value>
      <webElementGuid>fa8bb233-fe4d-40b1-b8f9-72895d74609b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[3]</value>
      <webElementGuid>390284c5-eebe-4756-97a9-45959e5d5b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kec. Gambir, Kota']/parent::*</value>
      <webElementGuid>5d5f8dab-ca94-4539-94a9-5679c7ce521e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[3]/div</value>
      <webElementGuid>c4bd3657-9cec-4811-b346-a97c778c261d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kec. Gambir, Kota Jakarta Pusat' or . = 'Kec. Gambir, Kota Jakarta Pusat')]</value>
      <webElementGuid>1ad491a7-f956-4fcb-a513-960e15603ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
