<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e64f9820-03e9-450b-b9db-bc273bcf07a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.close.btn.closeMaps > span > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapsModalnya0']/div/div/button/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>85ee6253-e68c-4e2e-b406-8c86f6ede645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_resources/themes/muat/image/icon/close-biru.svg</value>
      <webElementGuid>20535aed-22ac-45dd-9d77-c593ff269df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>2e1b1151-0665-43d4-995d-11e42cdd1cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>9e3c3300-ada3-405d-ad35-7c941b1e97a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapsModalnya0&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content modal-see-map&quot;]/button[@class=&quot;close btn closeMaps&quot;]/span[1]/img[1]</value>
      <webElementGuid>b2038cd3-cbdb-43ff-8401-afeae8453d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mapsModalnya0']/div/div/button/span/img</value>
      <webElementGuid>faa4f300-21f8-4571-b743-4f086455f923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/img</value>
      <webElementGuid>a8433898-c306-4eaa-a48c-0e3d36cb1782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_resources/themes/muat/image/icon/close-biru.svg']</value>
      <webElementGuid>090ecc73-5de8-46c4-888b-311018a6cbfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
