<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_component-input-border l_97f996</name>
   <tag></tag>
   <elementGuidId>a6a6ab46-b6a7-4c05-a4ed-b6f9715aaf51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.component-input-border.lh-normal.fc-1b.ff-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6a04f359-902b-4f2c-900b-01ca8cb095f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>component-input-border lh-normal fc-1b ff-medium</value>
      <webElementGuid>fcd49792-7776-48ba-b621-3d5ff7b2b8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f95f4a21-2d04-4049-8052-abc6037bdaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Deksripsi</value>
      <webElementGuid>8ef00715-8703-4115-9fac-93464e28f57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_deskripsi</value>
      <webElementGuid>2549e07a-a66d-47d4-88b3-e17ed169436f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_deskripsi</value>
      <webElementGuid>251716b1-0be6-493f-9a97-10e8f04043b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_deskripsi</value>
      <webElementGuid>f77d4abb-9074-4a04-a3d1-317cb489df96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_deskripsi</value>
      <webElementGuid>1da6fa63-45f1-4535-a550-66cf61f7f98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_deskripsi</value>
      <webElementGuid>c325cfc5-b27b-4d3f-a97f-c4a64d1f55ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d8477b7-2450-4acf-9b0a-d52b6b1e0194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>8394c465-c749-4595-a3aa-889945eabdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>Format file tidak sesuai</value>
      <webElementGuid>6b7d0acc-7117-41bf-90ed-dfee8f63be98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_deskripsi</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 500</value>
      <webElementGuid>6a4f734c-4dac-4ea9-9a65-76ba2b4821e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_judul_promo</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 100</value>
      <webElementGuid>59ada4ce-7f7a-409b-81e2-a636216f68ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>Ukuran file melebihi batas 5MB</value>
      <webElementGuid>19579a10-cab1-49e4-ba77-8fd89ad34b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_deskripsi</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>06358f3a-3c84-4394-818b-6f112f7e9d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_judul_promo</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>62dd73c4-56b5-4a77-a8f7-44562e7c3aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG, WEBP, SVG</value>
      <webElementGuid>e5d2b99c-acbc-4b9c-990b-8c760df8fccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_deskripsi</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>5f6ee0e4-7ee7-49c7-8656-6ff9507aad29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_judul_promo</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>404f5fb9-9f56-4aa2-a330-e95bdd6ecd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_promo</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9ee50c6c-578c-4f6d-a98b-0a9e7406eca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>7e8edd1d-8b38-4233-9072-12400088a2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_deskripsi</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a5c28fc5-25c1-4ef6-bf47-72549b337c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_judul_promo</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a2fe03e9-e5b8-414d-be2d-1d19b1ed62a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;fs-12&quot;]/textarea[@class=&quot;component-input-border lh-normal fc-1b ff-medium&quot;]</value>
      <webElementGuid>3b6b8a28-42d6-4620-958d-9b7809943def</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[4]</value>
      <webElementGuid>d69348c8-d680-42e5-aea3-a015447ab485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[14]/div[3]/div/div/div/div[2]/div[4]/textarea</value>
      <webElementGuid>3bce742a-bf1c-4290-bdae-1b5e286a1edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>f3006593-3a8c-45be-a398-0cede9d59425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @placeholder = 'Masukkan Deksripsi']</value>
      <webElementGuid>c77c0657-22cf-449c-8101-317c29116aba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
