<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hubungi</name>
   <tag></tag>
   <elementGuidId>7394deae-59c0-4498-9c9a-dd5b744758ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonHubungi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonHubungi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd40ffbc-0cfa-4511-9bed-1cbf7cde1eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover buttonHubungi</value>
      <webElementGuid>79d381e2-354d-4154-b78f-ca7921f79cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonHubungi</value>
      <webElementGuid>99696bce-20c4-44d2-948a-8adefdb69ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi</value>
      <webElementGuid>76183fa5-35c2-42b6-a9a4-a4568edb1caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonHubungi&quot;)</value>
      <webElementGuid>47911167-6a8e-44cb-8c8a-3728c23271f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonHubungi']</value>
      <webElementGuid>f3aeed80-e1ec-493a-96ca-ee5c2bcb87e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Briko Batu Bata'])[1]/following::button[1]</value>
      <webElementGuid>a0d626d1-227f-49b4-92d3-b6bbb0e2de01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Barang Lainnya Dari Penjual'])[1]/preceding::button[1]</value>
      <webElementGuid>973f7533-1dc3-467f-a638-0204a8a832b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hubungi']/parent::*</value>
      <webElementGuid>aef74ab7-0c1e-427a-9e8b-47060034b4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div[3]/button</value>
      <webElementGuid>50bb0aac-9ad5-4211-947a-9ea39a69f8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonHubungi' and (text() = 'Hubungi' or . = 'Hubungi')]</value>
      <webElementGuid>0298c78b-8165-4cca-983a-7d1597117567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
