<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Crop</name>
   <tag></tag>
   <elementGuidId>b425d044-f381-4b09-aa38-e25e07464745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cropImageComponent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cropImageComponent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b88a002-86d2-4797-9311-2810a5f76733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce44518e-924d-47da-b0b1-9c7021179737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary ff-demi</value>
      <webElementGuid>f3b66593-e377-4e83-be0d-8bcf52e73007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cropImageComponent</value>
      <webElementGuid>28221f2e-4d65-467f-81ff-66c4c6a139ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crop</value>
      <webElementGuid>77d9cafa-77bc-4864-a4e1-540e3df59ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cropImageComponent&quot;)</value>
      <webElementGuid>efb9f873-4264-4be1-a47a-cc57d22bb775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cropImageComponent']</value>
      <webElementGuid>316b0d87-70e4-4a99-b41f-2c3ff78b4d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalCropImageComponent']/div/div/div[3]/button[2]</value>
      <webElementGuid>bce49202-edf3-4926-9852-189503027839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>fe914e6c-3478-4105-b122-68729828b1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original'])[1]/following::button[6]</value>
      <webElementGuid>ab3b29df-3d12-4609-9fe4-1eaa920d59de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'cropImageComponent', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>6802c3fa-0478-4509-af82-083f5688a4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Crop']/parent::*</value>
      <webElementGuid>e8ecdc0e-abfa-4b9a-a94a-5f58f9e9185d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/button[2]</value>
      <webElementGuid>5543ddd1-e2b5-416d-aa4d-061fd8fc3dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'cropImageComponent' and (text() = 'Crop' or . = 'Crop')]</value>
      <webElementGuid>36cf5504-472c-4a40-90b4-2ef20951a042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
