<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5a29d0a8-703e-4a75-9a96-d908ccddb9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.close.btn.closeMaps > span > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapsModalnya0']/div/div/button/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f974a8e9-ab2a-4a0d-a697-54a329a49f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_resources/themes/muat/image/icon/close-biru.svg</value>
      <webElementGuid>adf2ce66-a234-4568-a266-a58bacf3dce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>38f5ba38-6f3f-43ec-9aab-08f634e7ff09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>edfd30c9-c4e6-4e02-974b-f1cf1e4fbed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapsModalnya0&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content modal-see-map&quot;]/button[@class=&quot;close btn closeMaps&quot;]/span[1]/img[1]</value>
      <webElementGuid>e39bc88b-f712-4393-b187-14e8b3f50d41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mapsModalnya0']/div/div/button/span/img</value>
      <webElementGuid>1d82aeb9-576d-4d18-bdee-3e38860f7c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/img</value>
      <webElementGuid>5b4ec6b9-6d59-4005-84ad-bd231cc372a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_resources/themes/muat/image/icon/close-biru.svg']</value>
      <webElementGuid>5b24d6ef-3f6b-4a60-a771-0bce1e1ee21d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
