<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pencapaian, Penghargaan, dan Ser_d3ca56</name>
   <tag></tag>
   <elementGuidId>c12238e6-9ff6-42d0-beaf-68a57e0b484b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.component-input-border-container.mb-8 > input.no-border.fs-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c5de3f5-1afb-40ae-b408-9b7d7adfb368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12</value>
      <webElementGuid>700a42ea-aef1-49d7-b0fb-49582fc1f24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3e19954-8992-41fd-a150-bce83fd8cb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Caption</value>
      <webElementGuid>f4450a52-bfb9-4793-8d23-0ac9e95a9d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_sertifikat</value>
      <webElementGuid>43141b23-6e0f-4f77-af70-ad90bf2ea8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_sertifikat</value>
      <webElementGuid>08748511-1ad8-42be-a098-c439d1c80204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_sertifikat</value>
      <webElementGuid>f6929193-2c99-48f2-99ef-16596b519455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_sertifikat</value>
      <webElementGuid>95fab1db-ae44-4b7e-a1f1-08e8f8444b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_sertifikat</value>
      <webElementGuid>42c5f2ce-3d24-43ff-8307-63870e912853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12680b41-9ad7-40e0-8028-f262e60cd0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>fa870f56-8388-445d-95c9-d84fe9ea8990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>Format file tidak sesuai</value>
      <webElementGuid>d636b89f-d529-457f-b1ae-101e5f250885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_sertifikat</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 100</value>
      <webElementGuid>5f4a597b-3d98-4b24-b39a-e468f9992287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>Ukuran file melebihi batas 5MB</value>
      <webElementGuid>e2ee53d7-08ca-430a-9bd5-4327cd010750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_sertifikat</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>4051f70a-4fd4-4c4c-9e5d-218a8b9cc932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG, WEBP, SVG</value>
      <webElementGuid>d6d0cbd4-79fc-41a5-b2be-7bfec8e4c148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_sertifikat</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a332bbde-ee6a-4ca2-9dda-fed2a0148943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_sertifikat</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>89158927-bedf-4239-9077-16a2d04d6de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6b426ee5-107f-4266-bb6a-c5b39d200d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_sertifikat</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>24e06cc1-5e55-4f28-b465-20efa205811a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;div-grow&quot;]/div[@class=&quot;d-flex component-input-border-container mb-8&quot;]/input[@class=&quot;no-border fs-12&quot;]</value>
      <webElementGuid>482b7097-7e96-4894-be47-1d52a5fc5b7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[7]</value>
      <webElementGuid>57ac02a9-6a2c-4b0e-9be8-1491f5cb5692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[11]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>4d3214d3-2537-4478-9605-757196584d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>4c5309e4-e43f-4ce4-bd37-785d8250d7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukan Caption']</value>
      <webElementGuid>bd4b926e-ff38-447b-baf6-9b77fc1fe04e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
