<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_component-input-border l_97f996</name>
   <tag></tag>
   <elementGuidId>ffcc5569-b152-4e87-b9db-72d887fad7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.component-input-border.lh-normal.fc-1b.ff-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1f973814-604b-4a49-b6c0-b94573a921c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>component-input-border lh-normal fc-1b ff-medium</value>
      <webElementGuid>9b87f165-f6c5-4e21-8cdc-c70ab7a6c5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc40580a-4d73-46f2-9cb1-2bb7652ffd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Deskripsi</value>
      <webElementGuid>c81000ff-c016-477f-896c-8fcaaa0d3e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_deskripsi</value>
      <webElementGuid>0445cda0-ed71-4137-822e-b2477f770aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_deskripsi</value>
      <webElementGuid>b7b1a322-f360-4d44-acfb-f261d6373b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_deskripsi</value>
      <webElementGuid>0c6290c4-36d0-4f4a-83de-55df7ef3cd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_deskripsi</value>
      <webElementGuid>4932e915-67c0-4e54-900d-0b5bda3234df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_deskripsi</value>
      <webElementGuid>cd713f55-a891-49a8-9eaf-ac069ffb7c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a815875f-a37b-4420-94e2-89574eca5fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>afa266c3-4abc-4add-a03e-9efbbad7e689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>Format file tidak sesuai</value>
      <webElementGuid>3f239125-9d3c-4a8f-b078-917a272ef8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_deskripsi</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 1000</value>
      <webElementGuid>87efa6e8-5175-4bba-ac62-84a5a33dddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_judul_promo</name>
      <type>Main</type>
      <value>simal karakter adalah 100</value>
      <webElementGuid>1555006b-b187-4658-9237-e3a58ece5e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>Ukuran file melebihi batas 5MB</value>
      <webElementGuid>994db1ed-ab78-418b-811c-8e7eaaa5082b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_deskripsi</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>bb327084-2af2-4469-8f41-307e8d1a747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_judul_promo</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>4c7fb939-e172-48be-a868-4944e3ef8d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG, WEBP, SVG</value>
      <webElementGuid>e990c5c4-de81-47b7-b95b-be88b6158a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_deskripsi</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>11476ca1-327a-4247-a314-1fa6fdbd115e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_judul_promo</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c9fda6eb-fbd3-4b02-a0e1-16fe1a219ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_promo</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>137d25f1-325c-42fe-b84e-a863d2f8dfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2b4fd11a-cae7-497b-a099-4d19f293fbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_deskripsi</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>63183db9-13fe-4d36-afc9-92737519d760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_judul_promo</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1c815084-8e82-4e2c-be4e-605a4a635949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;fs-12&quot;]/textarea[@class=&quot;component-input-border lh-normal fc-1b ff-medium&quot;]</value>
      <webElementGuid>c235b07b-ea48-4e59-b93b-f2f1e4557d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[3]</value>
      <webElementGuid>93a87188-5a7e-41e6-8d74-ee73485747a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[14]/div[3]/div/div/div/div[2]/div[4]/textarea</value>
      <webElementGuid>dae8c495-ac8e-4075-a61d-e2775e7a2d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>57211f70-47d2-4c60-af08-b734daf4fb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @placeholder = 'Masukkan Deskripsi']</value>
      <webElementGuid>306dba56-394e-43ca-b8ee-61ef8c19ed5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
