<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jenis Semi Trailer Carrier</name>
   <tag></tag>
   <elementGuidId>1f529de4-55a0-40ff-b5d6-c2433e9e1517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-pfrn-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-pfrn-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52df5a79-f966-4983-847c-8d439d1d4ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2516b3c9-4aa5-422e-bed3-909025686ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-pfrn-container</value>
      <webElementGuid>28227848-8d3b-468d-9535-da71dae225b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>154abb66-1daf-404c-864b-66a79998095a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82b81e6f-227a-4d9f-92b0-2f4f64469ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jenis Semi Trailer Carrier</value>
      <webElementGuid>1828f1bf-9040-413c-9506-ed22aacd7fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-pfrn-container&quot;)</value>
      <webElementGuid>cc2193a0-0d54-4a5f-ad0f-2f30dbe61452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-pfrn-container']</value>
      <webElementGuid>ec783480-0fd2-4e36-9b4f-84e09c2283a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[3]/div[2]/div/span/span/span/span</value>
      <webElementGuid>a6228641-d087-4140-bd20-57a83b78801b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[4]</value>
      <webElementGuid>d462cf07-2e15-4f24-aee2-cb395c504630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Semi Trailer Carrier Lainnya'])[1]/preceding::span[4]</value>
      <webElementGuid>1f9108ce-9630-40ae-a3d5-44bbe52ea537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>fa944fb0-5612-434b-b770-3385e357d629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-pfrn-container' and (text() = 'Jenis Semi Trailer Carrier' or . = 'Jenis Semi Trailer Carrier')]</value>
      <webElementGuid>d19fc4cd-28e2-4d47-be59-47da8c623db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
