<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Saya Transporter</name>
   <tag></tag>
   <elementGuidId>007a2f9c-75ce-48f7-9fcc-da785ab675df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='TransporterDocOption']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TransporterDocOption</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>223ac6fe-31eb-461b-b7f8-2b53175ab6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b8db79db-b329-4659-acd9-ba1d77366473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-opt line-height-24 ta-center tombol-primary-az ff-demi-az fs-14-az</value>
      <webElementGuid>93dda46f-3e91-40b0-91ca-47064b2b0396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TransporterDocOption</value>
      <webElementGuid>779f836e-71fa-44aa-81da-de112b89506e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saya Transporter</value>
      <webElementGuid>026679e7-752f-4028-88fc-a568abebb3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TransporterDocOption&quot;)</value>
      <webElementGuid>2954bbfe-d5a3-4e2b-b356-a4b61563cbc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='TransporterDocOption']</value>
      <webElementGuid>cbb9e8ad-68c0-471e-909c-afc552cd942f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='boxTransporter']/button</value>
      <webElementGuid>9431450a-7d9f-47bf-98d4-4559b084e5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transporter'])[1]/following::button[1]</value>
      <webElementGuid>72500641-f282-4b4d-b11b-e27e753e318e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya Shipper'])[1]/following::button[1]</value>
      <webElementGuid>64b6c854-1cef-4ad8-9d0b-3de83cd7a32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipper'])[2]/preceding::button[1]</value>
      <webElementGuid>21a13bdf-c5fb-4fbb-87c7-750aa2a661fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saya Transporter']/parent::*</value>
      <webElementGuid>8411a5a3-c45b-4368-b36c-f3ef213359ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>2e9a6fe0-32f3-40f9-b368-035b41f3f5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'TransporterDocOption' and (text() = 'Saya Transporter' or . = 'Saya Transporter')]</value>
      <webElementGuid>4e6277d4-7b16-42f6-ad89-d42934acff13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
