<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Tender dan Eksekusi</name>
   <tag></tag>
   <elementGuidId>127a69f4-0690-467b-8e5d-1b3ef356b209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EksekusiTenderRef</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='EksekusiTenderRef']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>780f0083-0c96-4ecb-ba84-641bde72b14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EksekusiTenderRef</value>
      <webElementGuid>6a157a4d-838b-4ae6-b817-55403d0c9561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://bf.azlogistik.id/eksekusi-tender?isMenu=1</value>
      <webElementGuid>fc166e22-fbce-4fc8-b672-246595fc6647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-12 ff-medium-az</value>
      <webElementGuid>dc738515-0fcb-46e0-b62a-f2d5ae6dd012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Tender dan Eksekusi</value>
      <webElementGuid>e6840248-e86c-4917-b39f-a9800d5f39f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EksekusiTenderRef&quot;)</value>
      <webElementGuid>b10c9ddf-9ed5-4573-9b4c-d0cff8bd0362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='EksekusiTenderRef']</value>
      <webElementGuid>fed65576-ec11-4326-88a7-226f2d67ff12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='EksekusiTenderSidebar']/a</value>
      <webElementGuid>7d172455-73aa-4c4c-b920-c2eb7cf021b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar Tender dan Eksekusi')]</value>
      <webElementGuid>3d762bbd-9af9-435e-90f3-ad0c9f7049b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(5)'])[1]/following::a[1]</value>
      <webElementGuid>8b5cec1f-1c7b-4359-a6d5-5d5f45cdbc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amandemen Tender'])[1]/following::a[1]</value>
      <webElementGuid>354a923b-d53e-40af-9513-2ed913bc5c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Entry'])[2]/preceding::a[1]</value>
      <webElementGuid>886ebdd5-f936-4ec4-b80c-aef9ad8ba6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instant Order'])[1]/preceding::a[2]</value>
      <webElementGuid>5db8a622-2db3-4dab-9412-0d3277f17853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Tender dan Eksekusi']/parent::*</value>
      <webElementGuid>87c806d1-ac06-490e-ae52-7a531d4a5f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://bf.azlogistik.id/eksekusi-tender?isMenu=1')]</value>
      <webElementGuid>f4c53f0d-d054-4326-92e8-3a3f2e5da4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>425d3596-273e-4a13-ad52-a18993dd639b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'EksekusiTenderRef' and @href = 'https://bf.azlogistik.id/eksekusi-tender?isMenu=1' and (text() = 'Daftar Tender dan Eksekusi' or . = 'Daftar Tender dan Eksekusi')]</value>
      <webElementGuid>2ef26680-3650-484e-9ace-d78f2dcdc0bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
