<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Shopee Pilih Lokal</name>
   <tag></tag>
   <elementGuidId>f1bd9334-04ae-45ac-80a9-5e1469275728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div[2]/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kmYTt8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>add089b6-25fd-400d-9dd3-988db16c6ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kmYTt8</value>
      <webElementGuid>ea531ee8-ea1f-4635-ad4d-3bf1940535af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shopee Pilih Lokal</value>
      <webElementGuid>50ecebf1-3e97-4128-8e78-d659bcc07efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;VrJeJi IF2WWf&quot;]/div[@class=&quot;home-page&quot;]/div[@class=&quot;section-banner-hotword--no-skin&quot;]/div[@class=&quot;full-home-banners-wrapper&quot;]/div[@class=&quot;XhCeW7&quot;]/a[1]/div[@class=&quot;kmYTt8&quot;]</value>
      <webElementGuid>0ff1e88f-5b32-4a3e-b94f-10c1436d029a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div[2]/div/div[2]/a/div</value>
      <webElementGuid>35c6e365-9f40-4194-aed7-f09c07301390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casing HP OPPO A16 Aesthetic'])[1]/following::div[68]</value>
      <webElementGuid>39430a12-717f-4988-967b-649f6fb5977d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sandal Wanita'])[1]/following::div[68]</value>
      <webElementGuid>8a0f6827-0e78-41a2-b7f4-50c653e4b690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serba Seribu'])[1]/preceding::div[8]</value>
      <webElementGuid>f7fe1b86-cc5e-4fbd-99ff-4a8a049ba237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div</value>
      <webElementGuid>59143fdb-a3dd-4beb-8efb-7225e315cfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Shopee Pilih Lokal' or . = 'Shopee Pilih Lokal')]</value>
      <webElementGuid>e6dade56-62a0-45c8-ae98-5a188a322375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
