<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dealer  KaroseriDirektori dealer dan ka_3b1b20</name>
   <tag></tag>
   <elementGuidId>cadf5172-856b-4f25-8682-4f6a246375ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > a:nth-of-type(2) > div.card-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContainerCard']/div[2]/a[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07f33302-db45-4ea5-bbcd-0257de655ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-border</value>
      <webElementGuid>0512e304-9e55-4922-9951-6516bad82108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dealer &amp; KaroseriDirektori dealer dan karoseri se-Indonesia.</value>
      <webElementGuid>c5443780-1eae-4439-8fd6-ac1de9cbd7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContainerCard&quot;)/div[2]/a[2]/div[@class=&quot;card-border&quot;]</value>
      <webElementGuid>1b0d2152-7918-402f-8682-da5e3e80b18d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainerCard']/div[2]/a[2]/div</value>
      <webElementGuid>a7bda3cd-48ff-4484-873f-26f3aa2742af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace kebutuhan logistik terlengkap.'])[1]/following::div[1]</value>
      <webElementGuid>8f5e55d9-1ad4-4375-9923-d37a79af1363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transportation Store'])[1]/following::div[2]</value>
      <webElementGuid>ac8d36fa-47d1-486b-8235-59b0f033117c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]/div</value>
      <webElementGuid>9c29ebac-67c9-4e8c-82eb-6a35373d2a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dealer &amp; KaroseriDirektori dealer dan karoseri se-Indonesia.' or . = 'Dealer &amp; KaroseriDirektori dealer dan karoseri se-Indonesia.')]</value>
      <webElementGuid>34a3e390-22f1-4dae-bec0-95f1621f4f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
