<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>0ed3d262-c6e5-4073-b53f-52dbcc914632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lanjutkanSurvey']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lanjutkanSurvey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>21ff8425-27e8-4992-a2e2-b739b3e355a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az</value>
      <webElementGuid>a7981e66-94d9-45a1-a109-f0c749c5c9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lanjutkanSurvey</value>
      <webElementGuid>686c3808-5c0c-4cf8-99a2-5649b35f245e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Lanjutkan
                </value>
      <webElementGuid>77d74665-9a30-461b-b2ea-1ee54a7f3e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lanjutkanSurvey&quot;)</value>
      <webElementGuid>833b62ce-3c9b-4ccd-9ead-49f067fbae56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='lanjutkanSurvey']</value>
      <webElementGuid>9e276357-728c-4f9b-9846-528e9de30245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopUpSurvey']/div[2]/div[2]/div[5]/div</value>
      <webElementGuid>cfbdd233-2cad-4a70-a159-43cc7cf6d35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kami mengapresiasi dan berterima kasih atas partisipasi Anda'])[1]/following::div[2]</value>
      <webElementGuid>2fd2fdfc-c584-4dd9-a430-2daddd060bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lainnya'])[1]/following::div[4]</value>
      <webElementGuid>a01e4e6c-9fe1-41e0-b846-d0d70c0578a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo Terbatas!'])[1]/preceding::div[3]</value>
      <webElementGuid>5bebf7ee-147d-4165-9d53-8e286fd91205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Berlaku selama periode 17 Juli 2023 - 17 Oktober 2023'])[1]/preceding::div[6]</value>
      <webElementGuid>d5433ec2-3a71-4090-9034-f8587a160e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>0955847f-a13a-4295-bc82-9222b15ac8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div</value>
      <webElementGuid>b0c8c0fb-31d9-43dd-8e8f-574b3b1d93cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'lanjutkanSurvey' and (text() = '
                    Lanjutkan
                ' or . = '
                    Lanjutkan
                ')]</value>
      <webElementGuid>5bfb8950-ea93-4e97-9762-596a2a778156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
