<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownPilihPembayaranPenuh</name>
   <tag></tag>
   <elementGuidId>1e2ce05f-4fc3-40a6-acd3-8456341efde2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-cc-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
