<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_FormatInteger</name>
   <tag></tag>
   <elementGuidId>acf3177b-f048-4a72-a53f-a0413ce9aedb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.FormatInteger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0079f200-a480-4899-b9b5-7ce8313d1cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormatInteger</value>
      <webElementGuid>c8aaf51a-284b-4faa-987f-eb6b9bd00704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6dd38e24-59b9-4e5f-b099-ffeb9bf060db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan harga sewa</value>
      <webElementGuid>9f68c31d-975a-4c84-95ae-9615458dcd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>Harga</value>
      <webElementGuid>4b498248-6461-465d-ae06-dd4e4d2214bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_value</name>
      <type>Main</type>
      <value>Harga maksimal Rp 99.999.999.999!</value>
      <webElementGuid>2ed01cd9-10e4-4369-832f-5ca6718f3673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_value</name>
      <type>Main</type>
      <value>Harga minimal Rp 100.000!</value>
      <webElementGuid>cb87feb8-822a-45d4-ac2d-24012bc179da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_value</name>
      <type>Main</type>
      <value>99999999999</value>
      <webElementGuid>458e22f0-9d00-4c9f-a398-69c79347a9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_value</name>
      <type>Main</type>
      <value>100000</value>
      <webElementGuid>419eff73-90c5-417c-a972-6541831cffdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12 component-262 component-input-border-container&quot;]/input[@class=&quot;FormatInteger&quot;]</value>
      <webElementGuid>84ae0ee9-cf3c-4df1-a0fc-2b19f48bcda0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[7]</value>
      <webElementGuid>e21260dc-9e65-46c3-b9de-ba3b8e37ffbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[14]/div[2]/input</value>
      <webElementGuid>6154b189-0af1-4a05-8183-7f5ce9f086a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/input</value>
      <webElementGuid>3275d0eb-9a39-4cb4-90dd-6acd1ff8692e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan harga sewa']</value>
      <webElementGuid>b6316c7f-37bf-4e7b-9b22-6756167a6cc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
