<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tahun Terakhir Renovasi</name>
   <tag></tag>
   <elementGuidId>8fd32e8b-fcc4-43b8-83a4-33b97e8c0f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-vtt5-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div/div[4]/div[1]/div[2]/div[2]/div[10]/div[2]/div/span/span[1]/span/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c5ead06-ca6a-4bbd-813e-bdb129f7dccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>65e316e8-18b5-4529-a9d2-d04c97fd3751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-vtt5-container</value>
      <webElementGuid>51bfdc21-289b-4e07-8a2e-7928cd6a12cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3b64a742-a57f-40b2-82d7-61a465e1d8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93706758-d642-452a-b8a8-22a0b4444898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tahun Terakhir Renovasi</value>
      <webElementGuid>b8bed53b-4cdc-4f13-ab45-27d757dcecd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-vtt5-container&quot;)</value>
      <webElementGuid>365754e2-f957-4e6c-9b03-89f6015f7df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-vtt5-container']</value>
      <webElementGuid>4fe2ee27-c7d5-40b8-86d0-7c23ba8e84de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[10]/div[2]/div/span/span/span/span</value>
      <webElementGuid>0cbb5560-62eb-4c39-ad93-d1695f939441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Terakhir Renovasi'])[1]/following::span[4]</value>
      <webElementGuid>b4f8c4cd-a00a-439c-9507-6a76fb384430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::span[10]</value>
      <webElementGuid>119730fe-1b42-4f34-a96c-fa298d8cdb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/span/span/span/span</value>
      <webElementGuid>24e6e2f8-a7c2-4409-aed3-1029b3c2144f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-vtt5-container' and (text() = 'Tahun Terakhir Renovasi' or . = 'Tahun Terakhir Renovasi')]</value>
      <webElementGuid>87dcb858-9d82-4507-95b2-56a6c3b609be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
