<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tahun Dibangun</name>
   <tag></tag>
   <elementGuidId>d76c4852-b646-47e1-85bb-40c1caefbbb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-s1z3-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-s1z3-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66f07a36-a624-4591-bc55-45891d49a035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ae4cecbc-76db-403f-852b-44c1612b7cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-s1z3-container</value>
      <webElementGuid>a313ef17-fe35-45da-aa0e-bc759210cc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d6f3c1b0-0c49-4ad6-b1ef-35b51b66f2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>654a46ed-e4af-4baa-bf6e-9a8f9a1552a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tahun Dibangun</value>
      <webElementGuid>2c406126-73fd-4afc-9b3e-f594798f6f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-s1z3-container&quot;)</value>
      <webElementGuid>79e7e41d-c8e4-42fa-9d24-a38a6c42802e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-s1z3-container']</value>
      <webElementGuid>81143d55-bc9a-4568-9e35-abee79ffc650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[9]/div[2]/div/span/span/span/span</value>
      <webElementGuid>e476ee6f-d4bb-44ac-9bf1-1538a156cdde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::span[4]</value>
      <webElementGuid>88f24198-41c5-44c5-ae37-b7a23016c1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Terakhir Renovasi'])[1]/preceding::span[4]</value>
      <webElementGuid>be11231a-ea0f-408c-9d74-782b96f7afa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/span/span/span/span</value>
      <webElementGuid>330c806f-b86b-4579-9581-60a6203a4880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-s1z3-container' and (text() = 'Tahun Dibangun' or . = 'Tahun Dibangun')]</value>
      <webElementGuid>d663323f-51d3-40a4-a874-0cb9546ed3e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
