<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hadap</name>
   <tag></tag>
   <elementGuidId>122c9dea-72c5-4ecf-ba0e-8557822f0bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-3t7n-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div/div[4]/div[1]/div[2]/div[2]/div[7]/div[2]/div/span/span[1]/span/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef837494-1ef9-4c80-8752-4839758ace85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>10400a00-457f-4cce-90d7-a77b534556fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-3t7n-container</value>
      <webElementGuid>252b17a5-033b-45e4-80bf-b2d1f0e497ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>79e6142b-1d53-482a-9576-2851bf87bcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0bc942f6-49dc-4296-a27e-d60a8d2a2220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hadap</value>
      <webElementGuid>319f40eb-4fdd-4635-91e6-f65603f536fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-3t7n-container&quot;)</value>
      <webElementGuid>23e34216-0fe2-4e44-865c-d78ff8caaed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-3t7n-container']</value>
      <webElementGuid>b725c892-69e1-4144-90aa-a14f49813d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[7]/div[2]/div/span/span/span/span</value>
      <webElementGuid>3378bedc-70d3-4809-9b13-a29cd0dbce93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::span[4]</value>
      <webElementGuid>ca7b2f59-94d2-42b0-a2ef-c8c4567f7a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/span/span/span/span</value>
      <webElementGuid>a1e459eb-117c-4e02-9fd8-2135de557c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-3t7n-container' and (text() = 'Hadap' or . = 'Hadap')]</value>
      <webElementGuid>b8ecbff0-b4e1-415d-9744-5ce864323328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
