<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChkBoxAllKecamatanDestinasi</name>
   <tag></tag>
   <elementGuidId>29606880-e9f4-4499-8744-caf7e43197ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modal_kecamatan_destination&quot;]/div/div/div/div[3]/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
