<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropdownSelectLokasiDestinasi</name>
   <tag></tag>
   <elementGuidId>6892fee3-7f77-499a-adfd-be89fded659c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main-window&quot;]/div[4]/div[2]/div/div[2]/div[1]/div[2]/div[2]/div[1]/span/span[1]/span/span[2]/b</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
