<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Upload</name>
   <tag></tag>
   <elementGuidId>46617d23-95d2-4e67-87d2-9c114cdbf020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-window']/div[4]/div[2]/div/div[2]/div[3]/div[2]/div[5]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.flexible-button.tombol-primary-az.mr-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f375542d-14bb-46a9-bee1-86357d4b7925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>readURL(this)</value>
      <webElementGuid>339036ec-6efd-4330-83b5-e4bf4ad7bffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flexible-button tombol-primary-az mr-12</value>
      <webElementGuid>1f88e495-1e15-4cc1-84ce-87cbeb45f849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>btn-upload</value>
      <webElementGuid>e15cb503-830d-4d4f-b87c-3a850fd69562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>48072510-c8ea-4eda-ac82-8dc6478c6e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-window&quot;)/div[@class=&quot;row&quot;]/div[2]/div[@class=&quot;content create-lelang&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/label[@class=&quot;flexible-button tombol-primary-az mr-12&quot;]</value>
      <webElementGuid>1e1027cb-40ca-4a29-b05d-d5309f9e8dd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-window']/div[4]/div[2]/div/div[2]/div[3]/div[2]/div[5]/label</value>
      <webElementGuid>87e711de-228c-4cc9-b851-46b365992772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brosur Gambar Promo*'])[1]/following::label[1]</value>
      <webElementGuid>dced5f59-8dfc-495a-8597-41dccefc06ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Opsional)'])[1]/following::label[1]</value>
      <webElementGuid>c1f99aa1-ed72-4e58-ba7c-81a074fc9415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file jpg/png max. 5MB'])[1]/preceding::label[1]</value>
      <webElementGuid>6e66a585-5cd0-4973-b6d4-853d2515009a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[3]/preceding::label[1]</value>
      <webElementGuid>83e8d773-3eb7-44a0-a5f8-737bcbb8df10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label</value>
      <webElementGuid>b1e9a79a-ddc5-481c-bd2f-1e55494a1a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>9f224a46-dd79-45a0-8c10-8cd8b19fff90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
