<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0ab0c2ce-fdef-4208-9b0e-4caa96e071bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.close.btn.closeMaps > span > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapsModalnya0']/div/div/button/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1372e334-58b7-45ce-944c-6348b1c17c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_resources/themes/muat/image/icon/close-biru.svg</value>
      <webElementGuid>db0ff81e-ff58-42c2-b718-2fefa32c4129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>66142af9-faa1-49f4-8293-4d6c09f4f744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f2b63247-f242-4e76-89d4-da4b87055aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapsModalnya0&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content modal-see-map&quot;]/button[@class=&quot;close btn closeMaps&quot;]/span[1]/img[1]</value>
      <webElementGuid>58e9d513-b931-4392-bc0e-fb3082367b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mapsModalnya0']/div/div/button/span/img</value>
      <webElementGuid>22f73686-4db8-42ab-88ec-01cecc1796db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/img</value>
      <webElementGuid>1b8eac82-8552-4f8a-88cc-6b6ec8e58f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_resources/themes/muat/image/icon/close-biru.svg']</value>
      <webElementGuid>c0ccabfe-bbab-4734-9dd9-704c17dd45c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
