<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat_searchBoxModalAddress0</name>
   <tag></tag>
   <elementGuidId>a063b702-e5f1-47c0-be5b-3ebd38009c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBoxModalAddress0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBoxModalAddress0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf5299d2-10fa-4311-abc8-ee4c699cf5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92220eb6-515a-47e3-812f-454bc8474dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mapsSearch fs-12 fc-1b no-border</value>
      <webElementGuid>9857ca97-85cc-4cd4-b062-256540331992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBoxModalAddress0</value>
      <webElementGuid>c18937b8-0182-460d-b99e-9d8b7d659548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hidden</name>
      <type>Main</type>
      <value>Address0</value>
      <webElementGuid>5c7ef15a-75ac-48d7-bacb-987e71728d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan lokasi</value>
      <webElementGuid>6ab45e68-2e1b-4eaa-b407-cfaea3d2fb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>bfb52f5d-c431-4f5c-992d-bef974847db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>db30f836-9db3-4fa8-a7e3-89191301455b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d108467a-e278-445e-aa63-b08fb071b389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBoxModalAddress0&quot;)</value>
      <webElementGuid>8f54d4e9-ddd2-4125-a3c4-06438f39fcf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBoxModalAddress0']</value>
      <webElementGuid>e682181e-35fa-4850-8cdd-c28855d2fd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='parent-searchBoxModalPickUp']/div/div/input</value>
      <webElementGuid>9f7be454-fb37-46cc-b10d-0a9fd1718bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>d73802e8-de4c-40e9-be1d-901829922e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'searchBoxModalAddress0' and @placeholder = 'Masukkan lokasi']</value>
      <webElementGuid>925cef61-bad5-4c7c-9dc6-98bf4c68d214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
