<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Margo</name>
   <tag></tag>
   <elementGuidId>9e4f43d4-fdda-47ef-9dc8-416d94378ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputRequester']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputRequester</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b606102-8815-46d4-93c2-a7fe8156e413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputRequester</value>
      <webElementGuid>06afd051-2291-40bc-98e3-e2c19d4330f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Margo</value>
      <webElementGuid>ec456e3b-a4da-4cbf-99a0-e955a1a73b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputRequester&quot;)</value>
      <webElementGuid>cef17a26-b63c-44da-ac0a-848e770fc9f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputRequester']</value>
      <webElementGuid>ed182950-11a8-42b6-b6ad-e00c92609dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ecdc31d2-b6cb-49e7-9050-ed510c8634b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputRequester' and (text() = 'Margo' or . = 'Margo')]</value>
      <webElementGuid>03589e65-c84c-4d4d-ad62-f0af19a286b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
