<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no-border fs-12</name>
   <tag></tag>
   <elementGuidId>eb2465b5-9e56-492b-9fc1-6f90f26b7bc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.component-input-border-container.mb-12 > input.no-border.fs-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb34c6b4-1402-4994-af93-3806050762eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12</value>
      <webElementGuid>7175489f-3623-45ff-888b-aa662e069c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b816cd7-581c-43d5-916b-6c6e317089d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Judul Promo</value>
      <webElementGuid>8751dcda-a27f-45f3-be0d-535b4772f29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_judul_promo</value>
      <webElementGuid>e80abf1e-7c9b-41cc-9c42-36d5666658ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_judul_promo</value>
      <webElementGuid>0fdb9c76-6c64-407f-a5f5-432764bdea24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_judul_promo</value>
      <webElementGuid>1901a551-baf6-43b8-8e90-f8b2aab80ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_judul_promo</value>
      <webElementGuid>72f459b7-29fa-4bc5-8482-b7b6825fab94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_judul_promo</value>
      <webElementGuid>76acaee2-62d7-4d4a-b414-4abb3d1e19b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>610e81c8-0924-4954-9672-0aa98b69b54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>judul</value>
      <webElementGuid>26c00664-a803-4c5b-8154-04092960b18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>File harus JPG/PNG</value>
      <webElementGuid>4fc9b6ce-2218-47d7-b551-500f604f968c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_deskripsi</name>
      <type>Main</type>
      <value>Max Character 9999</value>
      <webElementGuid>f8e74244-4359-464b-97e9-a99719c34cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_judul_promo</name>
      <type>Main</type>
      <value>Max Character 255</value>
      <webElementGuid>ae9e41e0-fc5a-4183-91b1-03f269d1e60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>File Max 5MB!</value>
      <webElementGuid>0dc183fd-b45a-48e8-b7c5-c208087a86ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_deskripsi</name>
      <type>Main</type>
      <value>Min Character 3</value>
      <webElementGuid>f61161ac-dcd0-45b5-8078-95e406c2e80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_judul_promo</name>
      <type>Main</type>
      <value>Min Character 3</value>
      <webElementGuid>ba85924c-e34f-42ff-817b-40443cc3db6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_deskripsi</name>
      <type>Main</type>
      <value>Deskripsi Harus Diisi!</value>
      <webElementGuid>22a870f2-9a96-4b68-8ad6-948bce754c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_judul_promo</name>
      <type>Main</type>
      <value>Judul Promo Harus Diisi!</value>
      <webElementGuid>4680924e-d093-452f-b74c-8dcfb056f93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG</value>
      <webElementGuid>ef53e040-7aaf-491b-a0ab-03faa40f03e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_deskripsi</name>
      <type>Main</type>
      <value>9999</value>
      <webElementGuid>c8a68917-c5b9-4c29-b187-f6c9f7153e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_judul_promo</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f7878074-d40d-4c5f-8acf-91aa61b077d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_promo</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>56d8b3a4-f98e-4ac2-ac92-44d5b878f27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>230bdafa-9368-4c73-b7a9-7de92e4f6a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_deskripsi</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>782d450f-e93e-4a08-8294-34c21ed4e056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_judul_promo</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>849b870e-6f86-46da-8052-908965350708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;d-flex component-input-border-container mb-12&quot;]/input[@class=&quot;no-border fs-12&quot;]</value>
      <webElementGuid>6e9a56a3-9a12-4b8e-abbc-b2ee5057a1ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[11]</value>
      <webElementGuid>83b3b67b-e271-4f12-8b41-d16df8df900d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[14]/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>fd5b5bcb-1d28-40a9-9d41-1eb423caea57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>cc883d05-6111-47c5-8eeb-a9e7d6b475bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukan Judul Promo']</value>
      <webElementGuid>0053db67-8c4d-4d5f-9b05-e23f722606be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
