<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no-border fs-12 h-30 w-100</name>
   <tag></tag>
   <elementGuidId>b755d0b2-ee69-49b5-bcd0-e0a1c367f058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.no-border.fs-12.h-30.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15434d4b-b670-4008-a473-c328cae80ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12 h-30 w-100</value>
      <webElementGuid>361724e6-7fdb-489d-9f85-7b0988d57883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0dab6fc-e930-437f-855d-f830d67383da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Caption</value>
      <webElementGuid>a52992ee-b7f3-42b0-a403-c2a9a9ccd3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>caption</value>
      <webElementGuid>f2e45267-9403-47d9-93f7-28e276782752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>50a75c3e-7cca-4417-bdab-beed455f3e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>File Harus JPG/PNG</value>
      <webElementGuid>033d7d66-acae-41e6-a182-8f32bdf55bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_caption</name>
      <type>Main</type>
      <value>Max Char 255</value>
      <webElementGuid>ba463843-8a95-4395-b6ec-be36b81c4b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>File Max 5MB!</value>
      <webElementGuid>7fe6cbc4-30a1-4169-8024-a77e66c5eb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_caption</name>
      <type>Main</type>
      <value>Min Char 3</value>
      <webElementGuid>d6df1904-82ad-47f0-bc91-b972247ec0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib Diisi!</value>
      <webElementGuid>20ee80a1-4c21-46ea-94c7-e29f3c6ea979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG</value>
      <webElementGuid>13a3b699-c370-42c0-981a-bf3a1df7f87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_caption</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>3ce04e72-6b2a-4349-9598-ddf5853034a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_galeri</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>aab92e2e-3596-43ff-b69f-1d1190f40a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>cd0d33c9-362c-43fa-a5ea-cb9f5be516d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_caption</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>83ae8eb3-a2fc-44c8-b37f-5b2a4bdc3a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_caption</value>
      <webElementGuid>6c87c52c-4a1f-4e47-9142-c86b907d9d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_caption</value>
      <webElementGuid>835f9a5c-fd8f-4f32-a0a2-f98368bd4979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_caption</value>
      <webElementGuid>61910ba2-22b2-48c4-a32c-8962a6f9a462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_caption</value>
      <webElementGuid>2f42cdc3-927b-4ff0-b910-12dd818efd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;d-flex component-input-border-container mb-8 h-32&quot;]/input[@class=&quot;no-border fs-12 h-30 w-100&quot;]</value>
      <webElementGuid>616ceae2-5e02-4cb0-b8ed-06b53fa5cfa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[9]</value>
      <webElementGuid>09990d22-f934-4238-a15e-5f2c0f42c00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[12]/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>bc085d11-2004-472e-bef2-78a67d73c99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>bf2f9031-9ba0-4aca-b218-0ef135057605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukan Caption']</value>
      <webElementGuid>0ae93288-4ab8-4054-be74-c20f53e18675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
