<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lokasi Iklan_no-border form-control d_722d8f</name>
   <tag></tag>
   <elementGuidId>f546ed3a-6b07-4e73-ad1e-5bd8b84d244a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.no-border.form-control.dropdownGoogle.ff-medium.fs-12.fc-1b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce921d68-349b-4dff-9172-ea0b4569b304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a39857b-bd40-432e-83f7-b5fae7e1317a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border form-control dropdownGoogle ff-medium fs-12 fc-1b</value>
      <webElementGuid>e02106f8-c105-4dab-a13b-7f91335c641a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Lokasi Iklan</value>
      <webElementGuid>b19def4e-855d-41be-bf9f-a04e28229fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search</name>
      <type>Main</type>
      <value>kecamatan</value>
      <webElementGuid>a8d60ff2-6d96-42cc-9247-234f0a39dabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>LokasiIklan</value>
      <webElementGuid>c00281f5-3d11-4cd0-a0d1-b2c271aa2cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e4af3075-93a2-4415-9e45-97fe56e30875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;parentDropdownGoogle d-flex flex-column&quot;]/div[@class=&quot;input-group mt-8 ComponentField component-input-border-container flex-middle&quot;]/input[@class=&quot;no-border form-control dropdownGoogle ff-medium fs-12 fc-1b&quot;]</value>
      <webElementGuid>a866874f-3f0c-483e-b6b5-6f997cfb450d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>418881e1-c804-4db4-b085-9987edde83e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[9]/div/div[2]/input</value>
      <webElementGuid>84c967d8-6786-49db-a05d-95f939288996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/input</value>
      <webElementGuid>6b64471a-644f-4009-92d9-0fdc4a08f2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukan Lokasi Iklan']</value>
      <webElementGuid>adb5715c-d683-475f-93d6-e2c0a453e721</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
