<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_upload_foto1</name>
   <tag></tag>
   <elementGuidId>e9d4f76d-e4e9-4370-a3c4-f69b8a06cfdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[1]/div/div[5]/div[1]/div[2]/div[2]/div[4]/div/div[2]/div/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
