<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sisa Kuota_radio_pasang_ku</name>
   <tag></tag>
   <elementGuidId>be98b534-bc07-4c3a-be2a-70cf98da78ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radio_pasang_ku&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radio_pasang_ku']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee296ebd-685e-4e1a-8250-04fc54d6c1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f021757f-5201-42f3-97a3-31b140adc3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24859</value>
      <webElementGuid>427db0fb-b618-4a93-b595-71833354f2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio_pasang_ku</value>
      <webElementGuid>5b105bd0-8159-4cb8-ac23-b40354e58674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-6</value>
      <webElementGuid>19f0f138-46bb-4216-973d-e3e26f926bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;bg-menu-big&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;alertfe&quot;]/div[@class=&quot;alert-custom&quot;]/div[@class=&quot;body-alert&quot;]/div[@class=&quot;isi-body&quot;]/div[@class=&quot;bdr-12 bdr-86&quot;]/div[@class=&quot;isi-pilih-paket&quot;]/div[@class=&quot;ff-medium fc-86 fs-14 d-flex flex-row&quot;]/div[@class=&quot;align-items-center d-flex&quot;]/input[@class=&quot;mr-6&quot;]</value>
      <webElementGuid>a1636bdd-43bc-48fe-a209-275190bf7fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radio_pasang_ku']</value>
      <webElementGuid>20648257-cced-4fe1-9394-e57d550efd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c92c4b2b-3b91-49ff-a06b-01310d7fc002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio_pasang_ku']</value>
      <webElementGuid>d4b4d3c0-044d-4bde-86ea-0b891bb2e56b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
