<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Keputusan(0)</name>
   <tag></tag>
   <elementGuidId>96285d63-ca5d-4afc-8a28-704ec3c06a68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='konftrans-header'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9bb4be22-6d8b-44f9-98ac-544bab7e6c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 tab-folder tab-folder-kontrak-harga tab-folder-inactive</value>
      <webElementGuid>86000cc2-4a4d-45a3-b96f-43ee8d4840c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>konftrans-header</value>
      <webElementGuid>c9765a04-4684-4c5c-916d-4206adb21f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3229adfe-8917-4d22-b8f8-29765c0cc327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							Keputusan
							(0)
							
						</value>
      <webElementGuid>b07e11f1-b8d3-469f-8716-9dfaa3a5355c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;summary-header&quot;)/div[@id=&quot;konftrans-header&quot;]</value>
      <webElementGuid>bfb5c14c-347f-45c6-b4fa-da44b45dae6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='konftrans-header'])[2]</value>
      <webElementGuid>543a6f6d-cce5-4bb0-b29b-8316c1e7c9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='summary-header']/div[2]</value>
      <webElementGuid>21dbf9f1-4e9f-4f02-918c-88f3dc4ed900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::div[1]</value>
      <webElementGuid>148ea887-d451-41c5-8aea-3ddaf361d338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ditolak'])[1]/preceding::div[1]</value>
      <webElementGuid>77d77366-9eed-4c6d-8e0e-29a543c61d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keputusan']/parent::*</value>
      <webElementGuid>abeb79c2-5cbb-4db0-a001-91b607a12de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]</value>
      <webElementGuid>aac0ceb3-11c4-4f2f-8aff-b42d1bb799f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'konftrans-header' and (text() = '
							Keputusan
							(0)
							
						' or . = '
							Keputusan
							(0)
							
						')]</value>
      <webElementGuid>6a5aee7b-848a-468c-9c67-48923ad31bca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
