<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hubungi</name>
   <tag></tag>
   <elementGuidId>2d9d6fd0-5fb6-4280-877b-0db5cbb87e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonHubungi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonHubungi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af61839f-268f-4a91-b7b4-ea6b43f3da59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover buttonHubungi</value>
      <webElementGuid>90996ba7-0e47-499b-9913-4c6f9b02c168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonHubungi</value>
      <webElementGuid>79f0e165-ca5c-47f1-87bb-1e9756e4d2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi</value>
      <webElementGuid>35ffa889-3f9a-4901-8b56-922258cb38a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonHubungi&quot;)</value>
      <webElementGuid>d24875b6-14c1-4185-a3d0-9c8eee4a1ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonHubungi']</value>
      <webElementGuid>d272494e-4478-4c52-a9e6-de646483c003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Briko Batu Bata'])[1]/following::button[1]</value>
      <webElementGuid>f02bd566-b23f-485b-8406-93abecb240df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Barang Lainnya Dari Penjual'])[1]/preceding::button[1]</value>
      <webElementGuid>a4998572-e5d8-4c2c-8803-4c20ee451f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hubungi']/parent::*</value>
      <webElementGuid>7de589b4-a6d7-4133-8896-8cfca27fad4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div[3]/button</value>
      <webElementGuid>8ebe0f7f-c8a7-4238-98a8-b3c9cc3c4e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonHubungi' and (text() = 'Hubungi' or . = 'Hubungi')]</value>
      <webElementGuid>dbcae8a8-0351-42f8-a85b-024a720ba16a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
