<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hubungi</name>
   <tag></tag>
   <elementGuidId>d438775a-d58b-4fab-b972-f8b994c837c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonHubungi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonHubungi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a96012d4-a49e-44f9-bdb2-83af6a20615e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover buttonHubungi</value>
      <webElementGuid>e75da1c0-2408-4451-92cc-3835d8a10658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonHubungi</value>
      <webElementGuid>4697f33a-f361-481d-9cd2-3c1cd28dbb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi</value>
      <webElementGuid>7ca74f7a-ae5d-4a91-8d2e-e622f75c5760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonHubungi&quot;)</value>
      <webElementGuid>c2d057f8-ae2a-402b-b8f8-e28b5a2e303a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonHubungi']</value>
      <webElementGuid>082a8685-79ea-426f-9cac-f5368e9dbc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Briko Batu Bata'])[1]/following::button[1]</value>
      <webElementGuid>8119346f-3cde-4d48-b8c9-da60022e7d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Barang Lainnya Dari Penjual'])[1]/preceding::button[1]</value>
      <webElementGuid>e55e64e8-ca43-4ef9-99f6-aaa101cf8e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hubungi']/parent::*</value>
      <webElementGuid>73a80dc1-3bd2-4d5f-8a36-10f96935eb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div[3]/button</value>
      <webElementGuid>6bad2d12-38a0-4afe-b0db-2187903115f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonHubungi' and (text() = 'Hubungi' or . = 'Hubungi')]</value>
      <webElementGuid>5bf2941b-fcb5-47f5-b17b-07ea4ceb760d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
