<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Human CapitalCari lowongan dan pelamar _efa029</name>
   <tag></tag>
   <elementGuidId>1e18d162-eed0-44e2-b4eb-cd43d8cb269d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;menuCategory&quot;]/a[7]/div/div/div[1]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > a:nth-of-type(2) > div.card-border</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dcea9b78-aa64-4e6f-a3a2-6e17a9d700e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-border</value>
      <webElementGuid>f08bd04c-40e1-4330-a715-a29b75dd0273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Human CapitalCari lowongan dan pelamar pekerjaan di bidang logistik.</value>
      <webElementGuid>9d8dfa26-8fb3-4146-85d3-5de5af188404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContainerCard&quot;)/div[3]/a[2]/div[@class=&quot;card-border&quot;]</value>
      <webElementGuid>cdf97f78-e979-4479-b5e7-91ec07abbfd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainerCard']/div[3]/a[2]/div</value>
      <webElementGuid>737ad685-761b-4926-af10-8f956bb0995e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temukan info promo dan discount kebutuhan logistik Anda di seluruh Indonesia.'])[1]/following::div[1]</value>
      <webElementGuid>694a58c1-fcbb-43ae-a97f-2b41dd449730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Places &amp; Promo'])[1]/following::div[2]</value>
      <webElementGuid>58df5939-6260-4c92-b458-05da6650d303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]/div</value>
      <webElementGuid>ead19429-cfba-4a58-8bd4-8ea017059d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Human CapitalCari lowongan dan pelamar pekerjaan di bidang logistik.' or . = 'Human CapitalCari lowongan dan pelamar pekerjaan di bidang logistik.')]</value>
      <webElementGuid>beb45628-a905-40ac-a578-a8e2eb67559c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
