<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Sub User Anda Berhasil didaftar_39f6d7</name>
   <tag></tag>
   <elementGuidId>2c2a9840-0485-4354-a95c-1bdc1004e5e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ulangi_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ulangi_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6e9f915-6efe-459f-a83a-4ff0ea5ef4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-verifikasi-email icon-eye-pw</value>
      <webElementGuid>9edc644d-6bb1-40e5-b3b6-4e9fe3ca6181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>900afa9f-80e1-4f1f-add9-546e4cfa422e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ulangi_password</value>
      <webElementGuid>9b0cc9de-bf84-410b-a4c4-51ea2b52c83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Konfirmasi Password</value>
      <webElementGuid>0e5896ca-fec4-45ec-b21f-229c1421ebb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulangi_password&quot;)</value>
      <webElementGuid>c4d8b7ff-2828-4914-adea-67f4594f1eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ulangi_password']</value>
      <webElementGuid>5b13eb7f-59a9-4537-b81b-6774b050d699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a920e101-f6a9-489d-9abd-c0b321b8098a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'ulangi_password' and @placeholder = 'Konfirmasi Password']</value>
      <webElementGuid>278db611-5d7c-45dd-8b5e-a90663fa2718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
