<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agen Dari Perusahaan_ff-medium fs-12</name>
   <tag></tag>
   <elementGuidId>214211b4-13d0-4e65-b5f0-e8230a61100f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c9c90ce-4089-4084-8a5c-6883e5134e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-medium fs-12</value>
      <webElementGuid>00c24f0c-5cc9-457e-8045-5f39461129d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30a41531-2795-4712-8b33-3274090a9eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>AgenDariPerusahaan</value>
      <webElementGuid>88d59f25-6401-4ce0-85b5-44821933cd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Agen Dari Perusahaan</value>
      <webElementGuid>c8242e84-2d22-4222-a828-91efa52c301b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 255</value>
      <webElementGuid>401a85a1-3f27-4587-9989-d2eb11b0cc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>42fd9713-ac6e-4516-918f-75b0b00485ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>c5146d73-8874-4216-8b04-37d294758eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ca1ed7ea-d970-47f9-b886-ba6b79eedaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField component-262 component-input-border&quot;]/input[@class=&quot;ff-medium fs-12&quot;]</value>
      <webElementGuid>ae55a4f0-eb62-453f-b9d1-c12e72b06e68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>2dd67f1d-bd8e-4d80-b5b1-906c9c39f240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[7]/div[2]/input</value>
      <webElementGuid>422a1a02-8cc4-4981-91dd-884f323c15d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>e48d4902-b238-467b-8826-4dc9a4ca633a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Agen Dari Perusahaan']</value>
      <webElementGuid>e08f6f9c-8676-44ba-a435-aec0812add41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
