<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sisa Kuota_radio_pasang_ku</name>
   <tag></tag>
   <elementGuidId>388495e5-2f2b-4a30-9c89-115db775fab8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radio_pasang_ku']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radio_pasang_ku&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef4d6107-5f99-4a36-ab73-71d7e17639f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8c8fad3a-c8f5-4241-961c-8d79b451b368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33868</value>
      <webElementGuid>31982444-8358-4eed-a7a3-3b7bb2e6ccd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio_pasang_ku</value>
      <webElementGuid>8d884a72-b80e-44a7-b58c-7054a5a70141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-6</value>
      <webElementGuid>ddc55183-b8d6-4f60-bde1-9de9f4c3b814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;bg-menu-big&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;alertfe&quot;]/div[@class=&quot;alert-custom&quot;]/div[@class=&quot;body-alert&quot;]/div[@class=&quot;isi-body&quot;]/div[@class=&quot;bdr-12 bdr-86&quot;]/div[@class=&quot;isi-pilih-paket&quot;]/div[@class=&quot;ff-medium fc-86 fs-14 d-flex flex-row&quot;]/div[@class=&quot;align-items-center d-flex&quot;]/input[@class=&quot;mr-6&quot;]</value>
      <webElementGuid>c7ceca00-62f8-45f7-aee1-cab33f23914b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radio_pasang_ku']</value>
      <webElementGuid>be22a196-9c5c-42ed-b333-87f6b7f24a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4f2b54a8-6454-47fc-b995-06ae6903094a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio_pasang_ku']</value>
      <webElementGuid>dbab37ea-1b4a-4b55-b6fb-bb6a4067283f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
