<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_text_1</name>
   <tag></tag>
   <elementGuidId>e7887f40-51c8-4d20-89c6-2f03c6747b2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>184927ab-e7ae-49f2-b683-24e4a0808364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>092fece9-2b3f-4141-b90b-5285a4f08531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Rute yang dilayani</value>
      <webElementGuid>cd215d4f-801c-4b8c-bb64-817133bd6c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>Ruteyangdilayani</value>
      <webElementGuid>b09109ef-cc4b-4100-9885-02b1e9984e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 1000</value>
      <webElementGuid>070887f1-38c8-4826-9369-8f07f170f195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>839d0077-6f38-4388-b260-b64420b3aad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>9800ba35-6c20-47e0-b82f-f0f955148698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ecfff6e5-c8a3-4cf1-8e22-2887fcdfa408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12 component-262 component-input-border&quot;]/textarea[1]</value>
      <webElementGuid>b8b7745c-ec07-4074-8fab-c63e13a8e380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[2]</value>
      <webElementGuid>4355de15-4958-46e4-8f28-24579d246a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[9]/div[2]/textarea</value>
      <webElementGuid>7371abd0-86f7-4d26-81b4-dd365640b777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/textarea</value>
      <webElementGuid>d9693790-7296-40aa-8626-be9a555be787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @placeholder = 'Masukkan Rute yang dilayani']</value>
      <webElementGuid>19704545-590a-4f5a-83dc-3b7d69d89268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
