<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sisa Kuota_radio_pasang_ku</name>
   <tag></tag>
   <elementGuidId>2111d6f1-e641-44fb-8a93-2d957a8aa1cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radio_pasang_ku']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radio_pasang_ku&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c05be41c-e7c5-4e34-afab-23bf4f10a729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ad069652-e657-46a7-9f85-fbf0ad06b562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>21174</value>
      <webElementGuid>8cb16570-29f3-4d28-955b-8dd9c4f22756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio_pasang_ku</value>
      <webElementGuid>1e891624-e780-4fff-99c1-fe2255bea1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-6</value>
      <webElementGuid>35b57f5f-84b3-4c24-ad44-458111e37612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;bg-menu-big&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;alertfe&quot;]/div[@class=&quot;alert-custom&quot;]/div[@class=&quot;body-alert&quot;]/div[@class=&quot;isi-body&quot;]/div[@class=&quot;bdr-12 bdr-86&quot;]/div[@class=&quot;isi-pilih-paket&quot;]/div[@class=&quot;ff-medium fc-86 fs-14 d-flex flex-row&quot;]/div[@class=&quot;align-items-center d-flex&quot;]/input[@class=&quot;mr-6&quot;]</value>
      <webElementGuid>05552682-1a67-44d6-9b79-5a4abbf602c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radio_pasang_ku']</value>
      <webElementGuid>417b3978-bbe5-4a94-9c1a-d45689281de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fbc44975-252a-4657-b5fb-cc2f580e4b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio_pasang_ku']</value>
      <webElementGuid>0b6d2e44-84ab-4e88-9793-88a674aa8c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
