<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cari Price List Transporter</name>
   <tag></tag>
   <elementGuidId>69d48fb3-d491-4c7a-8089-82b3ed014585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-manajemen-harga</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-manajemen-harga']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>215609e4-4d04-4bd2-ae1d-78158a499f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-manajemen-harga</value>
      <webElementGuid>f87f8550-e6c4-4a36-b492-65035166f646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>HT</value>
      <webElementGuid>07d542da-1d13-4406-ba15-1af5f4f5fe1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-sidebar  fw-medium fs-12</value>
      <webElementGuid>2db62dc3-f291-4bc0-b825-22e7866a1384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>/cari-harga-transport</value>
      <webElementGuid>8721a340-636b-435b-8c6a-84eb0d7ca38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6913b40e-237b-49d7-95fe-3482b7773284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari Price List Transporter</value>
      <webElementGuid>13d37c41-1a7b-49d7-9295-2d071d448f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-manajemen-harga&quot;)</value>
      <webElementGuid>3fcc1b88-bd50-4946-91d3-23530f496e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-manajemen-harga']</value>
      <webElementGuid>8e7ead83-fb5a-4f04-b907-1abbeee33712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-menu']/div[3]/a</value>
      <webElementGuid>566713b6-7f72-441d-92d2-b61b87391b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cari Price List Transporter')]</value>
      <webElementGuid>06a8f480-629e-492a-be3e-12ccf8690011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscription'])[1]/following::a[2]</value>
      <webElementGuid>69138acc-5bdb-4513-ba30-199acf178578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ke Transporter'])[1]/following::a[3]</value>
      <webElementGuid>e0d910a4-cf12-4580-af60-0deeea6a0b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlangganan'])[2]/preceding::a[2]</value>
      <webElementGuid>6c50d077-2fc8-42d4-982a-b094ba1b8328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Langganan'])[1]/preceding::a[2]</value>
      <webElementGuid>d7649311-cd37-45d3-9f31-f5ad70992da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari Price List Transporter']/parent::*</value>
      <webElementGuid>227a6658-a674-4a7a-b7c6-26696add7b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>02df71bd-4c77-40f8-8542-245cc7731431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>7f1d6916-52ac-4d9d-b491-2c0791919741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-manajemen-harga' and @href = '#' and (text() = 'Cari Price List Transporter' or . = 'Cari Price List Transporter')]</value>
      <webElementGuid>2bdcc424-583f-4b18-8b7e-c335427dcaac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
