<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah</name>
   <tag></tag>
   <elementGuidId>69873cf3-e794-4c82-abda-1c3024338699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54634a0c-3a47-42b9-ad71-678abb8334c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-submit</value>
      <webElementGuid>e5fd659e-8412-42b3-9459-b3eaf8cdd179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn upload-btn btn-flex ff-demi fs-14</value>
      <webElementGuid>e36e060f-8f08-4167-bf89-fc5a5f5b3534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>38a1afe4-f8f8-416d-9ac8-33ef4c75f89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	                            Tambah
	                          </value>
      <webElementGuid>71eae4f4-4210-4f6a-abd4-d925fbba78b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-submit&quot;)</value>
      <webElementGuid>f0fe1793-30d0-4aef-90bf-9b99a363cf68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form-submit']</value>
      <webElementGuid>5bf7faa1-860f-4903-b397-bbc5bb248e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div/div/div/div[2]/div/div[14]/div/button</value>
      <webElementGuid>a76d6005-a736-4f65-9382-6c8a52c01a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan untuk Shipper'])[1]/following::button[1]</value>
      <webElementGuid>43efb45a-2e5e-4173-94ed-875241a1a932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk bernavigasi, tekan tombol panah.'])[1]/preceding::button[2]</value>
      <webElementGuid>293a4dd0-d1a9-43b7-bb49-42adbb85857c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='←'])[1]/preceding::button[2]</value>
      <webElementGuid>8b9014b1-2810-4ec3-bf75-48816ffc549b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>9ba3ce2c-5dcf-47da-a9b1-888482c7eaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/button</value>
      <webElementGuid>eac878c3-fb9e-4f2d-a66c-a2cf93ccccbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'form-submit' and (text() = '
	                            Tambah
	                          ' or . = '
	                            Tambah
	                          ')]</value>
      <webElementGuid>4499ab65-7a44-4919-805b-9684e8d7ae18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
