<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_x_tinggi</name>
   <tag></tag>
   <elementGuidId>2ab26166-892c-42cd-ab4e-f069d6ab8974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dimensi_tinggi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dimensi_tinggi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71c02722-49f7-4333-87fd-c0d7960e84c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6ec1bdc-3cf0-45df-a1d7-cd7cbc248cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>24ba9520-bbf7-4ff5-9072-839c1904fc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tinggi</value>
      <webElementGuid>73465b26-a57c-4d88-b262-1a1a63a3b821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-component dimensi ff-medium pt-2 fs-12 formatDimensi satuan_berat text-center fc-1b</value>
      <webElementGuid>18f5caf5-6da4-482a-841b-b5291a427504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dimensi_tinggi</value>
      <webElementGuid>71e155ca-c92f-42c1-92b8-e4cde7e68805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>#dimensi_tinggi</value>
      <webElementGuid>46bc05bd-9080-4a2e-b7c8-cf5e14223183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>bb2e96ee-1c91-4fb8-b37f-230a5842621c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dimensi_tinggi&quot;)</value>
      <webElementGuid>c7c3bb49-45dd-4b09-be0e-982ffcecb1c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dimensi_tinggi']</value>
      <webElementGuid>8332344d-d257-4ed7-9923-db77b1ea75b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div/div/div/div[2]/div/div[10]/div[2]/div/div[3]/div/input[3]</value>
      <webElementGuid>4a6e104e-051d-48fd-b382-785ac13ed31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[3]</value>
      <webElementGuid>8e5fa0bf-aefb-460b-af04-1dd3b6e767c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tinggi' and @id = 'dimensi_tinggi' and @placeholder = 't']</value>
      <webElementGuid>876e9939-430f-4e92-988a-3ac2484cb896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
