<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan untuk Shipper_catatan</name>
   <tag></tag>
   <elementGuidId>7e3aec85-2bd9-44ac-94a6-0acf49112917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;catatan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='catatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>567d499c-7446-4e90-9151-fb21c49368c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>catatan</value>
      <webElementGuid>43c3f881-e28c-4410-8f97-8ad326dbf714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catatan ff-medium fc-1B fs-12 lh-normal</value>
      <webElementGuid>74631f2c-2d07-40b5-ae02-aef8f512463d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Catatan untuk Shipper</value>
      <webElementGuid>a9c78e3c-7061-4337-8e13-75bc31c6567b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e61afd02-4596-474a-8597-9b4e10b32c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-frontend&quot;)/div[@class=&quot;container px-5&quot;]/div[@class=&quot;d-flex  mb-3&quot;]/div[1]/div[1]/div[@class=&quot;card card-container&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;pr-0 justify-content-start d-flex&quot;]/textarea[@class=&quot;catatan ff-medium fc-1B fs-12 lh-normal&quot;]</value>
      <webElementGuid>f6967994-3a79-4c75-9d35-b0d69eef03a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='catatan']</value>
      <webElementGuid>2b7e5faf-1d2a-46a0-a933-5d9f4cb3319b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div/div/div/div[2]/div/div[13]/div[2]/textarea</value>
      <webElementGuid>ca99e443-dc51-486b-9a3f-037aea154963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>dbc94d55-6a96-44ef-9dce-fccbb0a13bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'catatan' and @placeholder = 'Masukkan Catatan untuk Shipper']</value>
      <webElementGuid>c6d8ff66-7776-4c0e-b108-f7dcc8052187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
