<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BARU_image-item-category</name>
   <tag></tag>
   <elementGuidId>31416b87-12d5-495f-ae22-da975d7ac319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menuCategory']/a[11]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af464913-4b6b-4e83-8d16-f1096705ddf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-item-category</value>
      <webElementGuid>a4cabae6-acdc-4f6b-b9ac-17c477e5784f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://azlogistik-live.s3.ap-southeast-3.amazonaws.com/content-general/assets/icon/kategori_menu/13.png</value>
      <webElementGuid>f1e1646d-6b9f-46b7-9c04-00bd73b2f3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuCategory&quot;)/a[@class=&quot;kategori-class&quot;]/div[@class=&quot;item-category&quot;]/div[@class=&quot;container-content-category&quot;]/div[@class=&quot;image-container-category&quot;]/img[@class=&quot;image-item-category&quot;]</value>
      <webElementGuid>8106bd1a-c1a4-4e64-87b6-3543a084edab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuCategory']/a[11]/div/div/div/img</value>
      <webElementGuid>f3c1f767-22f3-4b53-a4e2-b9adb4b049e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://azlogistik-live.s3.ap-southeast-3.amazonaws.com/content-general/assets/icon/kategori_menu/13.png')]</value>
      <webElementGuid>1c46f660-95c3-4a84-adb9-309b82127085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[11]/div/div/div/img</value>
      <webElementGuid>f7023f8b-ebdf-4afd-ae86-5f093b3f1313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://azlogistik-live.s3.ap-southeast-3.amazonaws.com/content-general/assets/icon/kategori_menu/13.png']</value>
      <webElementGuid>491db04c-eb27-45bf-9df5-ed9bcbecfdb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
