<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buat Price List Transporter</name>
   <tag></tag>
   <elementGuidId>e8a1f78b-d545-4253-b477-41b46cc52fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-manajemen-harga</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-manajemen-harga']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa867ed2-07cb-45d9-8d48-4aaf83c87351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-manajemen-harga</value>
      <webElementGuid>b97585d2-3b65-4d22-a727-09f8549cf516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>HT</value>
      <webElementGuid>723a63dc-6536-4575-a6e6-b301c03cd4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-sidebar  fw-medium fs-12</value>
      <webElementGuid>b9cb180c-5641-4b9e-a7b2-7bd5544ba39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>/manajemen-harga-transport</value>
      <webElementGuid>35d71978-2802-4656-b254-3a9732b67080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f15651bc-3eee-4a35-b263-917bfc453712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buat Price List Transporter</value>
      <webElementGuid>28e8630a-07d5-4d3a-828c-8a6b39ab2bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-manajemen-harga&quot;)</value>
      <webElementGuid>13e6d53a-4364-4145-88b9-b1afd3c0dca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-manajemen-harga']</value>
      <webElementGuid>8ba995d4-ce03-4095-b0f5-523af65cc993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-menu']/div[2]/a</value>
      <webElementGuid>38123688-6c6a-4fe1-9f74-1aa93012ba3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buat Price List Transporter')]</value>
      <webElementGuid>bd775a58-78a5-4e7b-baf0-dae0f616c292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscription'])[1]/following::a[1]</value>
      <webElementGuid>ecb76be5-a5be-4609-a65a-2898b631ebfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ke Shipper'])[1]/following::a[2]</value>
      <webElementGuid>9224211d-a114-4352-b9cb-d1da3ae8e6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlangganan'])[2]/preceding::a[3]</value>
      <webElementGuid>976b02f2-94d2-4e72-8169-cc502715d301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Langganan'])[1]/preceding::a[3]</value>
      <webElementGuid>73ec9c26-5f54-411f-8eb0-70342c0c852a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat Price List Transporter']/parent::*</value>
      <webElementGuid>f02b414e-e0de-4f5e-b6c2-fda6c28c23cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>917d387c-40c0-4880-bbff-b8300c9e9489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>bb25401e-8542-4a8a-9cd9-638832591e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-manajemen-harga' and @href = '#' and (text() = 'Buat Price List Transporter' or . = 'Buat Price List Transporter')]</value>
      <webElementGuid>abb48398-b04b-4b5b-a22f-093f8b52d616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
