<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>11313c12-d1f0-4443-beb3-b9e2e7f5c0a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-close-option > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-close-option']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7d1ed9ce-e863-4b43-a670-f000cf60897e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_resources/themes/muat/image/Subscription/close.svg</value>
      <webElementGuid>e2302aae-00ad-47d1-b36b-d170172f26be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-close-option&quot;)/img[1]</value>
      <webElementGuid>73f7f6b9-3f9f-432a-b400-8e27d724f9cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-close-option']/img</value>
      <webElementGuid>e626ebee-3588-4390-a119-4835628d189c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/button/img</value>
      <webElementGuid>3f03cc21-841a-4778-a00d-aa162b3106c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_resources/themes/muat/image/Subscription/close.svg']</value>
      <webElementGuid>ed5ea44c-2a23-419a-9b2d-23d09bef0ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
