<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Preview</name>
   <tag></tag>
   <elementGuidId>1f7b97ac-cd55-4ecf-a85c-0fbf0f6792e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPreview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPreview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9bda5ab0-c081-4d7d-8a6f-fe326f8b6392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-outline-az</value>
      <webElementGuid>0bd9e079-9a6a-453e-8389-6aeb2a98b1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPreview</value>
      <webElementGuid>5074fbfa-c2ee-43c8-bdc4-ff45da5a41b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Preview
                        </value>
      <webElementGuid>14bf914e-600c-4771-a6a6-4bdfe1bb0edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPreview&quot;)</value>
      <webElementGuid>592e96b2-a782-4b80-83c3-1833ce35dd46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPreview']</value>
      <webElementGuid>c4148994-fc9b-4f58-b5a6-608571d075be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ShipperMenu']/button</value>
      <webElementGuid>42835331-4553-4bf9-b6ec-4795aa5ed692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Transporter'])[1]/following::button[1]</value>
      <webElementGuid>bd7cfab6-723c-459f-83f5-fe9152f1d55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Shipper'])[1]/following::button[1]</value>
      <webElementGuid>be747221-ce32-4b0f-b585-96705fb04a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Perusahaan'])[1]/preceding::button[1]</value>
      <webElementGuid>bcbb2866-285e-46c4-92d2-fe0ca4207252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Perusahaan akan ditampilkan pada profil Anda untuk pengguna lainnya'])[1]/preceding::button[1]</value>
      <webElementGuid>0f0a4039-5353-4d33-8768-c593969b67c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preview']/parent::*</value>
      <webElementGuid>1f9df1af-23c4-4692-9fa0-ec2474d79305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/button</value>
      <webElementGuid>78545a14-cf5f-4960-a35d-789628a7cece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnPreview' and (text() = '
                            Preview
                        ' or . = '
                            Preview
                        ')]</value>
      <webElementGuid>a30398d5-bf07-448e-bcbc-46da4b05d0d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
