<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hubungi</name>
   <tag></tag>
   <elementGuidId>cf117535-e404-4430-8acf-6ad611047480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonHubungi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonHubungi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bb70e9b-c4d9-4095-9892-31881a6baf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover buttonHubungi</value>
      <webElementGuid>76f5bf32-6660-4620-8c74-b54470af3768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonHubungi</value>
      <webElementGuid>146a85b9-aa44-462a-a79c-aa16ff0598cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi</value>
      <webElementGuid>bbf7270b-1f8a-4ac3-9256-a23ce2235e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonHubungi&quot;)</value>
      <webElementGuid>2baf0d31-d5eb-42fd-8675-d5e6145ea86b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonHubungi']</value>
      <webElementGuid>99596868-a90b-4add-ac42-60fe60503027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Briko Batu Bata'])[1]/following::button[1]</value>
      <webElementGuid>f78757a3-effd-451c-9adb-4af3e77e547e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Barang Lainnya Dari Penjual'])[1]/preceding::button[1]</value>
      <webElementGuid>485ae263-71e4-407d-854e-92bfded829a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hubungi']/parent::*</value>
      <webElementGuid>ce179f16-313d-4407-9d21-ce6f524c17be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div[3]/button</value>
      <webElementGuid>2820f7af-9a2d-4e2f-9775-8f4d61c0d870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonHubungi' and (text() = 'Hubungi' or . = 'Hubungi')]</value>
      <webElementGuid>a023769e-baed-4b9a-829c-7bcac5c0e019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
