<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar</name>
   <tag></tag>
   <elementGuidId>d4886108-40a0-47ed-a5e9-a6b66a0e8346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnNextRegisBFShipper_step3_ptCV']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnNextRegisBFShipper_step3_ptCV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a071cc2-2d24-492a-a3c5-6fc038a90c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover ff-demi-az</value>
      <webElementGuid>e55b122d-1fad-4726-83de-ed562453cd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnNextRegisBFShipper_step3_ptCV</value>
      <webElementGuid>12fa7a90-ffd3-4e15-ab99-dc3e3bf8c05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Daftar
            </value>
      <webElementGuid>2870121f-7ced-41b3-acfa-1b1445d63d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnNextRegisBFShipper_step3_ptCV&quot;)</value>
      <webElementGuid>13034767-f7ee-4ced-b207-9f3836100d7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnNextRegisBFShipper_step3_ptCV']</value>
      <webElementGuid>f6212032-2a59-455c-b14b-f7896e3ff750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisBFShipperKelengkapanLegalitasPTCV']/div/div[12]/button</value>
      <webElementGuid>2714582c-c1b1-403e-a6d1-ec7cf4c938c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file jpg/png/ pdf/zip max. 5MB'])[3]/following::button[1]</value>
      <webElementGuid>a34fa51f-316a-4036-b40e-d7a8dcbeae20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[10]/following::button[1]</value>
      <webElementGuid>27569f5f-638f-46d7-a478-ecb74594e5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukuran File melebihi batas 5mb!'])[2]/preceding::button[1]</value>
      <webElementGuid>5f716def-8774-4154-9872-17fe6437a137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>5b442ee1-7ee6-4401-830e-6db6219c8fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/button</value>
      <webElementGuid>9283829e-8fa5-4f06-9a63-19f8f92f6037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnNextRegisBFShipper_step3_ptCV' and (text() = '
                Daftar
            ' or . = '
                Daftar
            ')]</value>
      <webElementGuid>81a61e5d-e860-4f7d-b278-38ddf6bc2d74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
