<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya_transport_2</name>
   <tag></tag>
   <elementGuidId>93ebf9c9-389c-453b-97e9-500687f4f036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btnDataPerusahaanSelanjutnya&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnNextRegisBFShipper_step1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3bcc879c-783c-448f-bd4a-b9271dbd3472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>margin-remover ff-demi-az</value>
      <webElementGuid>08252142-9db6-4554-8116-d4bf9ebd6196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnNextRegisBFShipper_step1</value>
      <webElementGuid>805fb431-3253-4650-8829-080119a2a3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Selanjutnya
            </value>
      <webElementGuid>ffa33251-5b95-4852-9179-93fb98ce8718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnNextRegisBFShipper_step1&quot;)</value>
      <webElementGuid>51c0fcbd-5603-4c5c-a551-33429ddb5262</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnNextRegisBFShipper_step1']</value>
      <webElementGuid>2130672e-7959-4354-b316-cbf10f4428d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisBFShipperKapasitasPengiriman']/div[2]/div[3]/button</value>
      <webElementGuid>d65355fe-9228-4fc5-a250-ac89b40bc8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah File'])[1]/following::button[1]</value>
      <webElementGuid>7afbd64d-90f8-4824-9e5e-60e603c72ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F8jO0IdaEAEFjSD.jpeg'])[1]/following::button[1]</value>
      <webElementGuid>8e39912d-6266-45ec-9630-c07877014134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maaf Sedang Terjadi Gangguan Teknis'])[1]/preceding::button[2]</value>
      <webElementGuid>9432b7db-8607-4fca-853b-341f66c3508c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KODE ERROR : 101'])[1]/preceding::button[2]</value>
      <webElementGuid>36528297-e9da-4b70-9c85-716788276be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>12cf7b4e-8502-4946-97c0-9202d83fc08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>d1154b77-a004-49a7-b43e-01f7fb072923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnNextRegisBFShipper_step1' and (text() = '
                Selanjutnya
            ' or . = '
                Selanjutnya
            ')]</value>
      <webElementGuid>63e68d38-0d36-4ab9-a6e8-110d456c6dd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
