<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Perusahaan_CompanyName</name>
   <tag></tag>
   <elementGuidId>0924d47e-1a9d-47ac-ad95-f65bbf7e68c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CompanyName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93325715-e070-4780-8815-7ece79e941f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c5586c79-4476-4f08-bbda-b1c4e7aa8eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyName</value>
      <webElementGuid>3d91360f-b6d6-4db3-b959-626d84d11c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input filled-requirement-dataPerusahaan</value>
      <webElementGuid>27e36dd6-5ef6-4aea-9a03-de14b4b25bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b99b6e70-2357-4c72-a278-9651dff0a227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama perusahaan</value>
      <webElementGuid>687b7350-9493-4a2b-9d70-d0fca8a8d358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyName&quot;)</value>
      <webElementGuid>9bc356c9-ba01-4e2b-8c3c-987a3f8a947b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyName']</value>
      <webElementGuid>07068b19-0f20-4634-b2dd-5df7e95230fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldCompanyName']/input</value>
      <webElementGuid>4dd0b565-0fbd-4e19-9498-e0dfb2074246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>35c294a5-8cd2-4f3d-ade5-b01812d45af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CompanyName' and @type = 'text' and @placeholder = 'Masukkan nama perusahaan']</value>
      <webElementGuid>7dd6b4fe-4c41-47c4-946a-4426da69f857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
