<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kec. Kenjeran, Kota Surabaya</name>
   <tag></tag>
   <elementGuidId>4869a31c-2c50-4c20-aeda-303c9eaa248c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PasangIklanForm']/div[8]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ff-medium.fc-1B.fs-12.mt-8.click-location-dropdownGoogle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>deda2ece-16c1-4dbe-80b7-7c0176bc18b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Kec. Kenjeran, Kota Surabaya</value>
      <webElementGuid>e884261c-52d4-43bc-bd86-283e764ba252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle</value>
      <webElementGuid>1add3d42-65a5-4908-b7df-1e87da57309c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kec. Kenjeran, Kota Surabaya</value>
      <webElementGuid>5be7e5c3-833d-4e32-8887-cc61c0b0d374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;parentDropdownGoogle d-flex flex-column&quot;]/div[@class=&quot;bg-white resultDropdown&quot;]/div[@class=&quot;ff-medium fc-1B fs-12 mt-8 click-location-dropdownGoogle&quot;]</value>
      <webElementGuid>4ba9e983-abf4-44dc-a513-9e0ad14adde9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[8]/div/div[3]/div</value>
      <webElementGuid>8e0a34c0-15dd-43d2-91d3-6aba59042cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::div[3]</value>
      <webElementGuid>144e72ca-dafd-4116-bea9-780f547dcaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kec.']/parent::*</value>
      <webElementGuid>c5cb3f86-6e13-4d16-93d9-1b5b5407ae1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[3]/div</value>
      <webElementGuid>36ade176-5050-4a74-aa0b-71abdc1dcc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kec. Kenjeran, Kota Surabaya' or . = 'Kec. Kenjeran, Kota Surabaya')]</value>
      <webElementGuid>d2c80461-3f90-4b8f-b1c4-2df034d472c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
