<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat_searchBoxModalAddress0</name>
   <tag></tag>
   <elementGuidId>86f33264-52d2-4358-850a-5b094bf343ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBoxModalAddress0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchBoxModalAddress0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6f00c33-dd6b-48dd-ad7b-de7710638c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb56e50b-c6e9-4015-b85f-50e631b222f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mapsSearch fs-12 fc-1b no-border</value>
      <webElementGuid>bdeddb7b-117c-4fb4-9a1b-2d19fa5e5f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBoxModalAddress0</value>
      <webElementGuid>239abab5-4939-4f4b-98a3-ccf2c75710c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hidden</name>
      <type>Main</type>
      <value>Address0</value>
      <webElementGuid>22287906-2d25-4f07-9c2c-04b814886f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan lokasi</value>
      <webElementGuid>7b9a6644-6225-4c2a-b6c7-354a83ece517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Anda Belum Memasukkan Pin Lokasi Alamat Perusahaan Anda!</value>
      <webElementGuid>dd8f7ca6-cc66-44a7-b269-03c6bcb22afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>95bf790c-11c8-4cc6-b84f-e5044298f744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f49ca753-b203-4465-9242-75498be4fa0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBoxModalAddress0&quot;)</value>
      <webElementGuid>ec7a72b7-b3f1-46d2-b7b6-c589314e328c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBoxModalAddress0']</value>
      <webElementGuid>1ee24a91-4167-475b-a625-bfbf5f481002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='parent-searchBoxModalPickUp']/div/div/input</value>
      <webElementGuid>1ad5bd43-15bb-46a9-b613-c79612a71329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>08fc0899-a6d7-40da-b3f7-0695123f3853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'searchBoxModalAddress0' and @placeholder = 'Masukkan lokasi']</value>
      <webElementGuid>506e6bb8-e1e4-4fe1-8333-f618b4a96828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
