<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_component-input-border l_97f996</name>
   <tag></tag>
   <elementGuidId>9e80f24f-fccf-4dc7-80b5-ffc0819b1ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@type='text'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.component-input-border.lh-normal.fc-1b.ff-medium</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c44d9f30-b184-4c31-9612-e40210ec8d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>component-input-border lh-normal fc-1b ff-medium</value>
      <webElementGuid>8b6eae60-4629-4b91-8071-78b0d9614876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0c97dd2-f411-4b87-873b-6d57894a3264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Deskripsi</value>
      <webElementGuid>6732aceb-adef-4023-ade6-1466fa4d665f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_deskripsi</value>
      <webElementGuid>5c21fdf7-8c90-4873-b8ee-9c213b537c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_deskripsi</value>
      <webElementGuid>adcd6648-860d-4876-b71b-715f4fbce990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_deskripsi</value>
      <webElementGuid>6a7ec2c2-7705-466c-b9a5-6761a0f61979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_deskripsi</value>
      <webElementGuid>d21fd794-d3b9-4a95-b57d-6c7c125c8dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_deskripsi</value>
      <webElementGuid>6f1e799f-a6d8-4fde-937d-00c68de6c66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dbff51be-b9b4-4be1-ae73-cc1417190e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>bcaae13d-dc41-4f77-873e-7b0b54c3bfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>Format File Tidak Sesuai Ketentuan!</value>
      <webElementGuid>63ebebf0-952f-457d-af28-b3576e45cffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_deskripsi</name>
      <type>Main</type>
      <value>Maksimal Karakter Melebihi Batas Ketentuan!</value>
      <webElementGuid>75eddefd-3f44-4ec0-8054-489507272aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_judul_promo</name>
      <type>Main</type>
      <value>Maksimal Karakter Melebihi Ketentuan!</value>
      <webElementGuid>c314c978-8e0f-48f5-8818-41d60aac17da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>Ukuran File Max 5MB!</value>
      <webElementGuid>8ef3d19c-7b43-4bb2-bc38-080fc9452e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_deskripsi</name>
      <type>Main</type>
      <value>Minimal Karakter Kurang Dari Ketentuan!</value>
      <webElementGuid>6068db30-6116-4f30-a024-cc6c91fab568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_judul_promo</name>
      <type>Main</type>
      <value>Minimal Karakter Kurang Dari Ketentuan!</value>
      <webElementGuid>c0c6cf80-5c29-49be-a6a3-49a53db7daef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG</value>
      <webElementGuid>4ae96877-9b58-47ce-86c0-6506b0e51bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_deskripsi</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>c8926d71-8bb3-45d9-bb83-8cdd3a4b81c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_judul_promo</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>9221b968-9b8a-4d19-bc7a-6470064b16b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_promo</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>32acc051-7482-418a-a19f-bb30c83603c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>58115232-21a9-4a25-b9ba-73002691e6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_deskripsi</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>06d54441-b657-43ab-8207-b87bc008f890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_judul_promo</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8627618f-4c47-4986-ada7-802de8b229f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;fs-12&quot;]/textarea[@class=&quot;component-input-border lh-normal fc-1b ff-medium&quot;]</value>
      <webElementGuid>22a7b6ce-4a33-48cf-8f6c-0b509c8d0aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[4]</value>
      <webElementGuid>79b55d92-ad91-4b60-a022-9f9cd09e39d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[13]/div[2]/div/div/div/div[2]/div[4]/textarea</value>
      <webElementGuid>4acd02b0-6b8e-44dc-8b01-39a0941a0ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>d85b293a-2bec-47b9-8baf-0f4e32a327d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @placeholder = 'Deskripsi']</value>
      <webElementGuid>3520ea47-c0aa-406a-9ef1-3d448d9c461d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
