<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email sudah terdaftar_inpEmail</name>
   <tag></tag>
   <elementGuidId>0d21304e-7eef-4a2e-98a7-48d542c66c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inpEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inpEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3da8545-65f4-4349-9d97-83f77fda934b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input-h48</value>
      <webElementGuid>271aeefd-868a-4f0c-b7f8-3144cb30d27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email/No. Whatsapp</value>
      <webElementGuid>728c0ee8-c80d-4941-a48f-7be0edb0218b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inpEmail</value>
      <webElementGuid>e3f51740-f82c-496b-9236-a8bb9045c1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpEmail&quot;)</value>
      <webElementGuid>97e47616-35e8-4130-9fe5-e9b82cce8a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inpEmail']</value>
      <webElementGuid>e2b8d2c3-c649-4ae6-bc05-8aa5b0eb45f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerkotakkanan']/div[8]/div/input</value>
      <webElementGuid>08b4131d-d934-4995-a31f-36a7097733a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>769f1efe-c2ce-4a63-a251-a72cda22a899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email/No. Whatsapp' and @id = 'inpEmail']</value>
      <webElementGuid>cf91ebe4-2927-4455-a944-9faf8b908747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
