<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Masuk</name>
   <tag></tag>
   <elementGuidId>daeb8a86-c40d-4bd6-b377-df559d7d63e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lblMasuk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lblMasuk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a45bf8c-4b49-48c8-8c82-08d6d0248ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl-btn-daftar</value>
      <webElementGuid>339a920b-a614-442a-850d-50bc2f8abd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lblMasuk</value>
      <webElementGuid>96610c86-8a23-4d4f-ad33-d047b6dc45f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>2a54cab4-16d7-4d89-95df-3e91daabeeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lblMasuk&quot;)</value>
      <webElementGuid>e6cca1b9-62e3-4d5f-868d-53084dd34247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lblMasuk']</value>
      <webElementGuid>c93d6d00-c247-4081-ae70-064104ed0faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnMasuk']/span</value>
      <webElementGuid>45b10bcc-71fd-41b1-b26e-8928a5efff0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/following::span[1]</value>
      <webElementGuid>cab2338a-bc3f-4363-92f9-d975074b89d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tetap Masuk'])[1]/following::span[2]</value>
      <webElementGuid>f274ccc9-122c-4fc7-bb4e-a06bc7719b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Punya Akun?'])[1]/preceding::span[1]</value>
      <webElementGuid>b1bc5d7a-86d5-451b-999a-e0e5695cfd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::span[2]</value>
      <webElementGuid>1ed4c65a-efa7-4808-8ac0-12d4814df06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>88d70eb0-1450-4744-a258-64f28696c0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/span</value>
      <webElementGuid>815975ba-d3a0-4f10-ab1d-d4f0cbfea4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lblMasuk' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>20b760de-ed71-4f19-9d61-2499ededbc68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
