<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Anda belum mengisi jumlah pengiriman__d2eb24</name>
   <tag></tag>
   <elementGuidId>ff01142d-0c35-4e79-9753-ea7dd2d015a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtKapasitasShipperBF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtKapasitasShipperBF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0ca4442-4199-4739-8ea5-81a56dd8ddcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>seprator(this)</value>
      <webElementGuid>5c31f89d-8fca-4f3b-988c-4d041db44420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>74cbf937-0e53-4cbf-8947-02f37015852b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78050923-8bc7-4f63-9af0-a13448a31fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autonumeric</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b9ed9967-6f12-4192-89d1-5b625fa7b8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-sep</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>beebfac6-c55a-4e89-8b94-3d42c1c75683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-no-style-fill form-input-number2-az txtKapasitasShipperBF</value>
      <webElementGuid>5e70bda0-3042-4bba-970d-8c3718e5e241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtKapasitasShipperBF</value>
      <webElementGuid>f1de8723-9c04-46ca-b1b3-40ec389066d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>114486e9-77bb-4873-ad92-26fc1603f204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtKapasitasShipperBF&quot;)</value>
      <webElementGuid>62dd1102-498a-4b1d-b3c8-6bcba0566bf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtKapasitasShipperBF']</value>
      <webElementGuid>8e8fbf37-6e02-4ee6-bf3f-5821385ed52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContInputTextKapasitasShipper']/input</value>
      <webElementGuid>71ae267c-beda-4e06-8878-88cef0adcc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>d8baac12-1508-4d1c-a927-4bee05b6c6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtKapasitasShipperBF']</value>
      <webElementGuid>2c9219b7-0261-440f-8f52-929a94e6e5d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
