<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Browse File</name>
   <tag></tag>
   <elementGuidId>f68b33d9-d514-4736-baef-579553e111b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addUpload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addUpload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cdbe5860-6bd8-4389-add6-554b29fdc5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addUpload</value>
      <webElementGuid>1d395ffb-9326-4aff-9693-58ecc0f70662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-12-az ff-demi-az fc-1b-az</value>
      <webElementGuid>379b6b76-75c5-4ff3-a39d-a7367ed54e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>upfileFotoVideo()</value>
      <webElementGuid>d0ec317a-e31c-4775-b579-4ab7940fa5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Browse File
                        </value>
      <webElementGuid>e58f392d-7827-4781-b18e-2403c70661e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addUpload&quot;)</value>
      <webElementGuid>bb71d9f6-d1b4-46d9-885d-adb49898dae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addUpload']</value>
      <webElementGuid>527a62ac-a945-44ed-a4d2-791454619be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalBox']/div/div/div[2]/div[6]/div[2]/a</value>
      <webElementGuid>77a3856a-79f6-47e6-83c2-b97b87d7ca53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Browse File')]</value>
      <webElementGuid>7a1df23b-f95a-4dbe-aae8-7184ace145ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Darurat'])[1]/following::a[1]</value>
      <webElementGuid>93e470b3-c8d4-453c-9f18-f33755ad3041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[16]/preceding::a[1]</value>
      <webElementGuid>0a4a45ae-d3c3-4146-bc67-5180d2630504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Browse File']/parent::*</value>
      <webElementGuid>06268449-725b-42db-a0db-4ee70270d976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/a</value>
      <webElementGuid>03e7ec46-0dc0-470f-9b59-37418bdc46b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addUpload' and (text() = '
                            Browse File
                        ' or . = '
                            Browse File
                        ')]</value>
      <webElementGuid>4b321ad4-205e-4e86-9ae9-5cc38e18c5be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
