<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload_foto_shipper_tm</name>
   <tag></tag>
   <elementGuidId>bae628e2-5182-4836-8316-6b2a661ecd6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;BtnUpload2&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnUploadFotoProfil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f83faa6-b745-4834-9cce-f3943b2dcaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover fixed-btn-96-32</value>
      <webElementGuid>aa2f571e-9dfc-489e-bb35-3382a5c46cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnUploadFotoProfil</value>
      <webElementGuid>96deb004-7633-4af7-806b-55d662fe93a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#ModalBox</value>
      <webElementGuid>5bd1e6b5-5617-4365-8410-95f7a62c6d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>857eecdc-4177-48ec-8f45-4a7f06cca50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parameter</name>
      <type>Main</type>
      <value>{&quot;type&quot;:&quot;ModalUpload&quot;,&quot;value&quot;:&quot;asd&quot;}</value>
      <webElementGuid>6fad95da-edc1-435a-b099-bc10d1aec1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>e6d372f5-ec57-4986-bfe6-56090f4f36d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnUploadFotoProfil&quot;)</value>
      <webElementGuid>0d4a517d-730d-4465-94ae-96d605b6292a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnUploadFotoProfil']</value>
      <webElementGuid>22cc130e-f85d-42d4-84fd-03734121a800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisBFShipperDataPerusahaan']/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>301d7c87-786a-43f3-ba9d-a02bfc242477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Harus diisi)'])[2]/following::button[1]</value>
      <webElementGuid>e7bdfa1a-bcfa-44e2-8e8e-701ab04e8fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logo Perusahaan*'])[1]/following::button[1]</value>
      <webElementGuid>ceafedc4-6f47-4281-81c4-b8a1bbe92dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file jpg/png max. 5MB'])[1]/preceding::button[1]</value>
      <webElementGuid>8fa75877-19ce-4da6-acd2-7ae742b71a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Perusahaan*'])[1]/preceding::button[1]</value>
      <webElementGuid>4265e3d3-5c15-4797-9ee5-05cdd605bfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>cdde5419-3bdc-4225-a996-96ea5f77799b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnUploadFotoProfil' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>a5487359-2567-424e-aab1-293968cd3f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
