<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email sudah terdaftar_inpEmail</name>
   <tag></tag>
   <elementGuidId>3e7b2ae0-caf2-4a3f-9680-adb9f2cf22f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inpEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inpEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25c35246-d40a-4d60-93a6-dc17c79a84c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input-h48</value>
      <webElementGuid>4b30b7f9-8018-49a4-963b-a4b3b617c184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email/No. Whatsapp</value>
      <webElementGuid>f788201c-0a5c-41d4-b491-53ce9f719289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inpEmail</value>
      <webElementGuid>e53c25f3-7f46-4b74-a837-d3e5459c4e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inpEmail&quot;)</value>
      <webElementGuid>5fa7f25b-8cae-49bd-a82b-22852c907f04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inpEmail']</value>
      <webElementGuid>3f1a5c7a-51b5-4990-926d-27cb09cb0add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerkotakkanan']/div[8]/div/input</value>
      <webElementGuid>7062106e-09e6-4f98-9b8b-b8be54982fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ab0c075e-3a7b-4ff9-aa58-682aa09187b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email/No. Whatsapp' and @id = 'inpEmail']</value>
      <webElementGuid>19450b59-49e0-46dc-9611-1467304b6618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
