<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ubah Foto</name>
   <tag></tag>
   <elementGuidId>65ceabb5-3499-480c-9149-20de3bffc035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ubahFotoHeader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ubahFotoHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da14764b-469a-4170-9248-9464b40a1482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ubahFotoHeader</value>
      <webElementGuid>8e001ed5-8692-41f6-bbb4-616d4d194621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#ModalBox</value>
      <webElementGuid>2e26ada7-a85a-4d5b-b67f-7d5c9d7f3704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>eeace543-b157-47e0-b6c7-3ff99ec2f07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parameter</name>
      <type>Main</type>
      <value>{&quot;type&quot;:&quot;ModalUpload&quot;,&quot;value&quot;:&quot;asd&quot;}</value>
      <webElementGuid>e6a6d38c-3695-4830-9a65-bcf3b81090ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Foto</value>
      <webElementGuid>c2ec4f0a-3ea6-4753-ac1d-7607f18af960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ubahFotoHeader&quot;)</value>
      <webElementGuid>d17bd1d4-5e87-41a4-938e-c7ea8191c896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ubahFotoHeader']</value>
      <webElementGuid>f9042b8e-3577-470d-ab5f-cd067f20c0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerMain']/div/div/div</value>
      <webElementGuid>bf9b3273-63e1-4732-8144-25cad2b29175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[4]/following::div[5]</value>
      <webElementGuid>364ca938-f5dd-49fd-95e2-3dca2850c210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maaf, Anda belum memiliki akses.'])[2]/following::div[6]</value>
      <webElementGuid>1c4e8d81-5bfc-44fc-bfc5-49670778ca5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TokekKrispy'])[1]/preceding::div[1]</value>
      <webElementGuid>c4a089c9-4364-4058-b992-c747e67d190f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Whatsapp'])[1]/preceding::div[2]</value>
      <webElementGuid>4c3146ee-bb88-4be6-9bd7-39b1a61b7f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah Foto']/parent::*</value>
      <webElementGuid>658300be-3580-429a-b130-cb0605717068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/div/div/div/div</value>
      <webElementGuid>badc33e4-fac2-4a55-8263-c93b5fee1023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ubahFotoHeader' and (text() = 'Ubah Foto' or . = 'Ubah Foto')]</value>
      <webElementGuid>4c3fe729-8230-463d-9a1c-e0186e000b34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
