<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan OTP_OTPField6</name>
   <tag></tag>
   <elementGuidId>f2c93321-7a5b-4aaf-b0db-5f61e9507764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OTPField6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OTPField6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe933953-7e55-4597-881e-524fdb16f6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input-general-number-az input-text-otp ff-bold-az fs-14 text-black ta-center line-height-16-8</value>
      <webElementGuid>b4516341-2662-4bbb-9c5e-179568540dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTPField6</value>
      <webElementGuid>07ba5c0a-9ef5-4907-9f05-8789f9a87e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a3d13bac-730b-4f60-94cd-c3e20658f306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTPField6&quot;)</value>
      <webElementGuid>5a9e04ad-105b-4984-860e-dab6bc702ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OTPField6']</value>
      <webElementGuid>ed43aed2-baab-4129-a0f4-6cf8811c6de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>8338a249-aeae-464d-a931-683065355720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OTPField6']</value>
      <webElementGuid>748efce1-af58-4f35-9bbb-7b1a2be7f843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
