<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan OTP_OTPField4</name>
   <tag></tag>
   <elementGuidId>971a85c0-a9c2-4ce3-9670-bed0581fd3fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OTPField4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OTPField4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b46f04b-2d24-40e9-95d2-c120361e0579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input-general-number-az input-text-otp ff-bold-az fs-14 text-black ta-center line-height-16-8</value>
      <webElementGuid>fee38062-6d30-4de4-b955-cf26d7f505b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTPField4</value>
      <webElementGuid>5cd70a25-4ae2-498d-94aa-f3ed4f4fda26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>53259528-920b-488e-8732-520dc7f4a696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTPField4&quot;)</value>
      <webElementGuid>2b23b4e5-d3b3-40f0-97c5-29e2ee87bb22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OTPField4']</value>
      <webElementGuid>16c192ae-fc0c-4b48-bc97-bffb2183c82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>b1cb0213-6ac4-4be3-bddd-37e52ff42bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OTPField4']</value>
      <webElementGuid>6572758f-af63-40ca-ba7e-ecc2c719f73f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
