<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Radio  Frekuensi_radio_info</name>
   <tag></tag>
   <elementGuidId>f7e70be9-9f84-4042-83ae-066fc2cc7109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f33a3004-03ce-462d-84ee-3a866e658710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f0477e6-da78-427a-96f3-efd6a551b164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2e7b0e72-c01c-42d1-9cd5-93ab2df7a0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio_info</value>
      <webElementGuid>42484b4c-45ae-4365-a02b-17138663c76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a78eb28-6fbc-4be7-b59e-71d484d56781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input ml-12 css-1sxenmq</value>
      <webElementGuid>ed68514f-9ca7-4720-bb9e-063fe02a394a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-13</value>
      <webElementGuid>969611a9-3501-417e-9803-427b6e621b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-13-helper-text</value>
      <webElementGuid>0c9140c5-98f0-4d12-b4b7-7d3e61f9411f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-13&quot;)</value>
      <webElementGuid>cf34a181-836b-4774-91f0-545023cc95b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-13']</value>
      <webElementGuid>14aa8f98-e661-41f8-b35c-aea6f385155c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div[2]/form/div/div/div[7]/div[2]/div/input</value>
      <webElementGuid>fe108219-f65e-47c6-88fc-3edccede205b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>f1b5cf0b-31b0-41dc-9420-5e114a32c9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radio_info' and @type = 'text' and @id = 'mui-13']</value>
      <webElementGuid>d011cea9-bd22-4386-8dba-85c41acfba77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
