<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Judul Promo_no-border fs-12</name>
   <tag></tag>
   <elementGuidId>bec9b854-88c4-45af-8da3-5216d97c54fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.component-input-border-container.mb-12 > input.no-border.fs-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fbc8ff5-2256-4e7f-b17c-bc33d2588da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12</value>
      <webElementGuid>ba5ca706-4129-44a9-91d4-91da3b9676df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22bf348a-0e54-4342-ad87-2c7dd260dd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Judul Promo</value>
      <webElementGuid>d0c4815b-401c-48f3-975b-58a08f474761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_judul_promo</value>
      <webElementGuid>b9e0842b-a7ab-4016-b29e-489631eef27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_judul_promo</value>
      <webElementGuid>3d14398b-41ab-4195-9c26-7cd365af1f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_judul_promo</value>
      <webElementGuid>82021403-8791-4e08-b46a-ccc815994bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_judul_promo</value>
      <webElementGuid>fee70389-1d5d-4bd3-9dd4-2eead233677e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_judul_promo</value>
      <webElementGuid>6c3abb3c-c541-49cc-8835-422befc83b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>270e7aa1-5151-4bfc-9703-6032fb9cb3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>judul</value>
      <webElementGuid>a2aa320d-1b32-4acc-b4d3-a26cb5e0f4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_image</name>
      <type>Main</type>
      <value>Format file tidak sesuai</value>
      <webElementGuid>04235a6e-c8f8-44cf-a88f-729c49a6529f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_deskripsi</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 500</value>
      <webElementGuid>c4584464-a204-40ce-97d7-29f07f17255c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_judul_promo</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 100</value>
      <webElementGuid>4ed8f701-6a3d-4174-a009-cf86192c48e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_image_size</name>
      <type>Main</type>
      <value>Ukuran file melebihi batas 5MB</value>
      <webElementGuid>c21773d9-c05c-4c4d-a3f8-e4408417ec0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_deskripsi</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>05e3fa94-c625-47bf-a5ee-0be30fa01020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_judul_promo</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>36cd6beb-1fb7-475d-8aa7-f7a49ab2bde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_image</name>
      <type>Main</type>
      <value>All, JPG, PNG, WEBP, SVG</value>
      <webElementGuid>a0a25aa7-fc21-43ea-a924-58e0471fbe40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_deskripsi</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>8bc02257-2276-4280-bcd2-42065b7e23f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_judul_promo</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ea972cda-a5fe-45aa-9411-59966403d963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_promo</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2f4eb2f0-0987-4b5a-9135-757127821956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_image_size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>908140bb-a9bc-41c8-b810-23e75a5ace3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_deskripsi</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8c52e334-368f-47dd-b97b-43c1b51f51a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_judul_promo</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ecaeab16-8c19-4828-aa08-25656594e757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;d-flex component-input-border-container mb-12&quot;]/input[@class=&quot;no-border fs-12&quot;]</value>
      <webElementGuid>ec0bebcc-853b-4ab9-b257-53523a9f2d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[10]</value>
      <webElementGuid>09b9c9f0-f510-4829-842b-dcf7fa26edd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[13]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>488fb856-243c-414d-a413-118f64c28541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[3]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>36615a79-70ea-4a7e-9516-70c0fb33ec5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Judul Promo']</value>
      <webElementGuid>43e664ac-e1f4-4db0-9f67-68f48f6b2a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
