<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no-border FormatInteger w-100</name>
   <tag></tag>
   <elementGuidId>86cfe166-79e5-4c5f-a504-2734173550f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.no-border.FormatInteger.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c348e90e-ce3e-4317-a38c-92387b4bcc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border FormatInteger w-100</value>
      <webElementGuid>51c6c78c-de00-4987-96be-3ed2d4268722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89b1019e-7679-46ce-80c3-2f821badc1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Tangki</value>
      <webElementGuid>62ce04ff-ec1c-41ee-a181-23ebbf9473ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>Jumlah_Tangki</value>
      <webElementGuid>e8b1d810-b18c-4595-9a25-a2d47fca52a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_jumlah_tangki</value>
      <webElementGuid>ac349313-9cf0-473f-bfaa-7530dab8f3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_value_var</name>
      <type>Main</type>
      <value>min_value_jumlah_tangki</value>
      <webElementGuid>fec1cf15-113c-4695-b77f-ee62fd35d8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_value_var</name>
      <type>Main</type>
      <value>max_value_jumlah_tangki</value>
      <webElementGuid>643b6788-f931-4cf0-b0d9-2472c33bbcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_value_var</name>
      <type>Main</type>
      <value>alert_min_value_jumlah_tangki</value>
      <webElementGuid>b921a42f-0b8f-4800-9063-ef53cc1b7c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_value_var</name>
      <type>Main</type>
      <value>alert_max_value_jumlah_tangki</value>
      <webElementGuid>a13d3fcb-0bd4-4def-aba6-eb8ea19fbfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4eeb5e1-1baf-4c0a-bc1b-984fd85f15da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_value_cbm_tangki</name>
      <type>Main</type>
      <value>Maksimal value 999.999.999!</value>
      <webElementGuid>f167b8e5-b4b8-4073-bf9f-ce79e2dd9b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_value_jumlah_tangki</name>
      <type>Main</type>
      <value>Maksimal value 999!</value>
      <webElementGuid>2adeb3ba-438b-45df-9113-20fc2f032396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_value_cbm_tangki</name>
      <type>Main</type>
      <value>Minimal value 1!</value>
      <webElementGuid>1a0be2bd-d25d-401a-ae97-3ee0426efe7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_value_jumlah_tangki</name>
      <type>Main</type>
      <value>Minimal value 1!</value>
      <webElementGuid>4e6c1c51-f1b9-412a-a4ad-457b91b1e3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_cbm_tangki</name>
      <type>Main</type>
      <value>Wajib diisi!</value>
      <webElementGuid>3908ffb1-ee97-42d2-8c75-d804f8d5cb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_jumlah_tangki</name>
      <type>Main</type>
      <value>Wajib diisi!</value>
      <webElementGuid>71837fc5-4514-4e85-b856-b6f3e0e5e698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_tipe_tangki</name>
      <type>Main</type>
      <value>Wajib diisi!</value>
      <webElementGuid>9f9c7fa7-cd0a-4536-9a94-04388c6e4d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_detail_tangki</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>f09f7d90-67b6-4b19-a0dd-3e8281c415bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_value_cbm_tangki</name>
      <type>Main</type>
      <value>999999999</value>
      <webElementGuid>b3fbfad1-570a-4a4f-8214-f34a48baf747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_value_jumlah_tangki</name>
      <type>Main</type>
      <value>999</value>
      <webElementGuid>b71a533a-cd00-4abf-99b0-c058c13c8323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_value_cbm_tangki</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bedf6ab7-bea4-4eb5-a30d-3a999995a166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_value_jumlah_tangki</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>97a26158-b759-4444-ae03-3afd0e6758be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[2]/div[@class=&quot;ComponentField no-border widget PlusMinComponentContainer d-flex flex-column&quot;]/div[@class=&quot;PlusMinComponent d-flex align-items-end&quot;]/div[2]/div[@class=&quot;flex-middle component-input-border-container fs-12 ff-medium&quot;]/input[@class=&quot;no-border FormatInteger w-100&quot;]</value>
      <webElementGuid>c2969239-0410-4453-ac7e-b21ffe674151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>71620092-1711-4423-abad-6b40e8ace0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[10]/div/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>6256a5e1-07bb-434f-9303-be033b766e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>4d054003-cd46-4939-9f39-2a6f6ceba2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Jumlah Tangki']</value>
      <webElementGuid>a419d7af-f2c1-4c48-b9cc-03ecadbe4ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
