<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama File_no-border fs-12 ff-medium</name>
   <tag></tag>
   <elementGuidId>d6387037-5604-4a5f-af4b-0db1fed7fe59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.component-input-border-container.mb-8 > input.no-border.fs-12.ff-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[16]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e50247d-dbe3-45ee-8bb5-f9c456f4d93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12 ff-medium</value>
      <webElementGuid>e1bc38c8-620f-4044-96fd-06199fcbaa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0f31f88-4127-49fd-9b26-c08ab0fe32d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Testimoni, Portofolio Pelanggan, Pelayanan</value>
      <webElementGuid>be3d15a5-c0e6-44e6-b727-ab26420353eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required_var</name>
      <type>Main</type>
      <value>alert_required_portofolio_testimoni</value>
      <webElementGuid>84ebd244-7265-459c-8ed3-e3c19e80f7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_nama_file</value>
      <webElementGuid>7c2f82c1-42f4-485d-beb9-1ec243238f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_nama_file</value>
      <webElementGuid>71d97e65-54f9-4622-bca1-71084b282c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_nama_file</value>
      <webElementGuid>0dba14f4-7f31-49bb-a70d-72ae89672290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_nama_file</value>
      <webElementGuid>a329004f-46b5-4886-ab53-ec800ce92d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a707e843-b845-48ae-be8b-9d50895a21d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>6db236a4-9fbe-48f1-afc7-ee6d4d583489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_file</name>
      <type>Main</type>
      <value>Format yang diperbolehkan adalah PDF dan DOCX!</value>
      <webElementGuid>5dd1a6d1-5d80-4ae3-be2d-13c54f408765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_nama_file</name>
      <type>Main</type>
      <value>Maksimal 255 karakter!</value>
      <webElementGuid>3e2bd517-23ee-4066-85c8-c6a8af4d1eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_file_size</name>
      <type>Main</type>
      <value>Ukuran maksimal 5MB!</value>
      <webElementGuid>1f3430b2-8ca6-45aa-a2bb-79fd14e2ae56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_nama_file</name>
      <type>Main</type>
      <value>Minimal 3 karakter</value>
      <webElementGuid>46368b14-e117-432a-84a5-1db2c9b1596a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_file</name>
      <type>Main</type>
      <value>All, PDF, DOCX, JPG, PNG</value>
      <webElementGuid>81522166-adb4-4f88-a6a8-5d73a4e9f234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_nama_file</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>730ddc45-4622-4b3f-8148-933aa4223112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_testimoni</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>deb8ff13-2bf6-411a-9c20-e864219eb6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_file_size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>70fc0d52-de66-4ef3-8d31-8446c152e1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_nama_file</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>62d00974-eb6d-47a4-a563-2a646ac09c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;div-grow&quot;]/div[@class=&quot;d-flex component-input-border-container mb-8&quot;]/input[@class=&quot;no-border fs-12 ff-medium&quot;]</value>
      <webElementGuid>6162864c-5c17-4cc1-ac25-9025a8b784b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[16]</value>
      <webElementGuid>6182556f-1b7c-4df4-b622-6ef660e44edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[20]/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>e121adcb-a78a-4cb1-8e31-82c8843964f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>f22bc11d-1a09-46bd-999c-2228f8fd4e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Testimoni, Portofolio Pelanggan, Pelayanan']</value>
      <webElementGuid>ee72a3d0-53f0-4a2c-b873-c4d492448b4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
