<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no-border fs-12 h-30 w-100</name>
   <tag></tag>
   <elementGuidId>f09a06a3-57f0-4bc0-90b9-c1199b04e37d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>373dd645-2c85-4a5a-882b-c887a919921d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border fs-12 h-30 w-100</value>
      <webElementGuid>ff685e73-9886-4928-9a52-e154a53e1771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7fff41fe-2ff8-4e49-9173-38b984b06d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Caption</value>
      <webElementGuid>c2ca451c-1c0b-4a93-8a7f-eb60415edd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>caption</value>
      <webElementGuid>9a970614-574b-4098-9371-bbac127358d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-group</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>193929eb-be10-49ea-8daf-5ace52f4fb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_limit_ext_video</name>
      <type>Main</type>
      <value>Ekstensi File tidak sesuai</value>
      <webElementGuid>1e664468-b502-482a-ba41-083982a0a031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_caption</name>
      <type>Main</type>
      <value>Karakter melebihi batas</value>
      <webElementGuid>f16f9bc1-ecee-4a2b-8c56-a4f6a45cc175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_video_size</name>
      <type>Main</type>
      <value>Ukuran File melebihi batas</value>
      <webElementGuid>aa3d9b31-3cbd-400f-913b-0242f9512274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_caption</name>
      <type>Main</type>
      <value>Field harus diisi</value>
      <webElementGuid>854298e0-fd18-4172-a182-c0ebdee238e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Field Harus Diisi</value>
      <webElementGuid>e47f53df-5a0b-4745-854b-19cdadf6c17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-limit_ext_video</name>
      <type>Main</type>
      <value>All, MP4, MKV</value>
      <webElementGuid>2b285d36-5dc2-4589-b620-9c23743b3527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_caption</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>5a3e8b25-7148-44b2-88eb-8abe7b8409b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_col_galeri</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>37657ddf-5f4a-4754-9d4b-965a6994f66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_video_size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>5f78aa16-c029-46bf-8dce-ff4bee268245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_caption</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9dac7e92-0e74-474f-a786-f2b2a15f2b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char_var</name>
      <type>Main</type>
      <value>min_char_caption</value>
      <webElementGuid>d44cf52f-0014-4c36-adf6-1f170122b932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char_var</name>
      <type>Main</type>
      <value>max_char_caption</value>
      <webElementGuid>66a0262e-c0b6-4b03-af50-475c7d95a610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char_var</name>
      <type>Main</type>
      <value>alert_min_char_caption</value>
      <webElementGuid>57434a4b-fa52-4e50-8591-1dd23a855f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char_var</name>
      <type>Main</type>
      <value>alert_max_char_caption</value>
      <webElementGuid>2c24155c-4b7f-4f7b-9ad3-2cb417d927fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField no-border mt-12&quot;]/div[@class=&quot;d-flex flex-column PlusMinComponentContainer&quot;]/div[@class=&quot;PlusMinComponent d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;d-flex component-input-border-container mb-8 h-32&quot;]/input[@class=&quot;no-border fs-12 h-30 w-100&quot;]</value>
      <webElementGuid>d2abae8e-d991-4aa3-9252-eca79205bbec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[13]</value>
      <webElementGuid>d25ea01c-2b8c-45fb-a87d-de293263a79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[17]/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>9aae3d03-a93e-4a5d-bd5b-4dc939ef71f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>bd5dc4cf-14af-417b-a65a-e2c5f06e8555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Caption']</value>
      <webElementGuid>4d640fec-95d7-4597-aab7-b9ac61ac175c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
