<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat_searchBoxModalAddress0</name>
   <tag></tag>
   <elementGuidId>516156ef-0f6e-4c83-aa57-a41a2b32910d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBoxModalAddress0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBoxModalAddress0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f801074-e47e-438e-bacc-fe5191df9fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfbc17d5-f885-4d19-9fb5-a447e31ed8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mapsSearch fs-12 fc-1b no-border</value>
      <webElementGuid>59f04c4b-3611-44bb-ba06-53a0bd4c7835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBoxModalAddress0</value>
      <webElementGuid>949610ae-cc2a-48e1-8762-5e8f7ee2d65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hidden</name>
      <type>Main</type>
      <value>Address0</value>
      <webElementGuid>1ccdf63f-366a-493e-b516-486700740b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan lokasi</value>
      <webElementGuid>d5da6c37-c7a1-4a00-96e8-16b522595360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi!</value>
      <webElementGuid>61280088-67af-49e0-bb87-b3a15bdde85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-child_column_name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>5fd51381-576b-4de1-afe0-308abf54a358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e8f7443a-78ea-40d0-b656-9220c43899e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBoxModalAddress0&quot;)</value>
      <webElementGuid>bf3e26aa-ed48-43b9-8b93-1f61fbee59ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBoxModalAddress0']</value>
      <webElementGuid>fb6cf16f-b183-4b2f-9818-0c3b2155fcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='parent-searchBoxModalPickUp']/div/div/input</value>
      <webElementGuid>7c618dd9-8495-4a25-af7b-f8bddc599bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>63458ce0-bd3b-41bf-9374-01677f7cb2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'searchBoxModalAddress0' and @placeholder = 'Masukkan lokasi']</value>
      <webElementGuid>57030713-2c20-4dee-9d9e-a6430a8217d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
