<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tipe Tangki</name>
   <tag></tag>
   <elementGuidId>95c88871-0167-4c6e-aee3-315ff2f2fae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-zu2o-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-zu2o-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8fef2405-a730-429d-9043-bfb46fc91142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>534f8371-85de-49a8-8215-ea9f75415141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-zu2o-container</value>
      <webElementGuid>1172ceba-fb98-44e4-afcb-658642de16c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>629ca919-b474-456e-a73a-eeb0991b816c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2019c267-ff0b-43e0-ae81-a355ae908915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tipe Tangki</value>
      <webElementGuid>143758b3-cc81-4f03-9929-ff681e661a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-zu2o-container&quot;)</value>
      <webElementGuid>0acf27dc-67e8-4cf2-a474-843e4ecdd197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-zu2o-container']</value>
      <webElementGuid>4f275067-60eb-4fe6-b86f-dd2889d0786a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[10]/div/div[2]/div/div/div/span/span/span/span</value>
      <webElementGuid>3f928b83-caf9-418b-82c3-91e2f61d7dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::span[4]</value>
      <webElementGuid>26c1c8e2-942f-44c6-9bfd-7a4d97a3da2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/div/div/div/span/span/span/span</value>
      <webElementGuid>5ea75261-2526-422d-a78b-fc3ec3c96dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-zu2o-container' and (text() = 'Tipe Tangki' or . = 'Tipe Tangki')]</value>
      <webElementGuid>6c1d89db-4876-4c11-ab49-6cdf9b3814c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
