<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pusat Bantuan</name>
   <tag></tag>
   <elementGuidId>5c79d555-f0af-47b9-ad27-d252ac000570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NavFAQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='NavFAQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8c337c4-6fa9-4376-ba0b-5ebf587027fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://muatmuat.com/traffic/redirect_faq?from=gen</value>
      <webElementGuid>05592fb6-f6a8-4bd2-aec0-1e2fc43cf3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-demi-az fs-14 text-black line-height-16-8</value>
      <webElementGuid>3193ce45-8a59-407f-a228-9201c2219680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NavFAQ</value>
      <webElementGuid>580eb226-cca6-48db-9e95-60f6e1d3cecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pusat Bantuan</value>
      <webElementGuid>ef1bef14-d8db-48f8-819e-dc06cf59ec53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;header-container&quot;]/div[@class=&quot;fixed-top main-header&quot;]/div[1]/nav[@class=&quot;nav-menu d-lg-block&quot;]/ul[1]/li[3]/div[@class=&quot;nav-point-header-container&quot;]/a[@id=&quot;NavFAQ&quot;]</value>
      <webElementGuid>a9465613-f379-4831-b4e0-50d91523e103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='NavFAQ']</value>
      <webElementGuid>a802a767-f84e-4de8-97e8-93fa92345a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pusat Bantuan')]</value>
      <webElementGuid>7221d630-718e-4607-8540-58ddd680bf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Kami'])[1]/following::a[1]</value>
      <webElementGuid>ff6c0563-37d3-447f-88b4-1a4eaf292b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>3ccdb420-7e5c-403e-8f37-c7fd263f5a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::a[1]</value>
      <webElementGuid>d87d88b4-4a93-4582-8d2f-64bcbeabb683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bergabung Bersama Kami'])[1]/preceding::a[2]</value>
      <webElementGuid>ffb84d26-55dd-4825-86c7-a902527caf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pusat Bantuan']/parent::*</value>
      <webElementGuid>50b7a9c6-fa3d-44fa-9565-07e8cf5c30ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://muatmuat.com/traffic/redirect_faq?from=gen')])[2]</value>
      <webElementGuid>a9bb3d16-577a-4a9a-bb63-d81a9476b526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a</value>
      <webElementGuid>2cb17521-2fc1-4054-b849-f84adc0cbd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://muatmuat.com/traffic/redirect_faq?from=gen' and @id = 'NavFAQ' and (text() = 'Pusat Bantuan' or . = 'Pusat Bantuan')]</value>
      <webElementGuid>b16350db-443b-4326-bd2e-a500694ee191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
