<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>789e931d-1205-49e0-a12e-905240a8203d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;InputFileSKKemenkumhamPendirianPTCV&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnUploadSKKemenkumhamPendirianPTCV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae08f342-50f5-41a5-b045-6f390171463e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover</value>
      <webElementGuid>9e36d948-7779-4b45-ab45-fae6ed6fe272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnUploadSKKemenkumhamPendirianPTCV</value>
      <webElementGuid>3243eaaa-2c2e-4c8e-9dd5-a1c24ff6f0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>43f9d888-56e4-4b02-b0a3-86a07fd100e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnUploadSKKemenkumhamPendirianPTCV&quot;)</value>
      <webElementGuid>8e776a31-fa2b-4302-b19d-e1a777bb163a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnUploadSKKemenkumhamPendirianPTCV']</value>
      <webElementGuid>eba7bfda-ade8-4b39-af79-bf7ef2622436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='fieldInputFileAnggaranDasarPTCV']/button)[2]</value>
      <webElementGuid>ceaef9f1-55a2-4c53-b3be-4259104ceaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Harus diisi)'])[5]/following::button[1]</value>
      <webElementGuid>3502f672-494e-457b-903a-3aa5de34eda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SK Kemenhumkam dari Akta Pendirian*'])[1]/following::button[1]</value>
      <webElementGuid>bddd0bb6-9f7b-4ed0-9fe4-53ac2b71be4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file jpg/png/ pdf/zip max. 5MB'])[1]/preceding::button[1]</value>
      <webElementGuid>ad30a3f0-6b8e-494a-a0bc-fb36175f1a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cover Akta Perubahan (bila ada)'])[1]/preceding::button[1]</value>
      <webElementGuid>8bb2ee36-5e32-4562-a69a-46816a5fa214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/button</value>
      <webElementGuid>bd5c79fb-10f9-4ca8-a009-d56f0eb13422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnUploadSKKemenkumhamPendirianPTCV' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>0ec12eea-8ab9-4f3d-9dae-5ae8cc729af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
