<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload_1_2_3</name>
   <tag></tag>
   <elementGuidId>59e4f530-951e-49a6-a3bc-21a67e522de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;InputFileKTPPTCV&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnUploadKTPPTCV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7cd46f0-0654-4214-b9b1-394c6e54580b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover tombol-Upload-legalitas</value>
      <webElementGuid>3b0e5a44-3d4e-4638-8e20-e54f54cf1c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnUploadKTPPTCV</value>
      <webElementGuid>5bf4550c-42d5-4093-b5fb-e2c48eac4ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>603a0b02-cade-46b6-b5a2-f7f14825feea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnUploadKTPPTCV&quot;)</value>
      <webElementGuid>cbf2e82a-046e-4dd3-82fa-d1ac27d226fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnUploadKTPPTCV']</value>
      <webElementGuid>e75e8f87-103c-4ac0-8cc7-2306e2f5b1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldInputFileKTPPTCV']/button</value>
      <webElementGuid>eeeaba1c-9d66-424e-9539-5891b28d4f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Harus diisi)'])[3]/following::button[1]</value>
      <webElementGuid>c5be6c4d-e0d5-42e2-a723-cf7ba072ff8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTP Pendaftar/Pemegang Akun*'])[1]/following::button[1]</value>
      <webElementGuid>63faad35-bba1-4f62-b378-a63d29063559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file jpg/png/ pdf/zip max. 5MB'])[1]/preceding::button[1]</value>
      <webElementGuid>6f498031-493a-48a6-9344-b6c81cd33bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cover Akta Pendirian*'])[1]/preceding::button[1]</value>
      <webElementGuid>a5543c8d-2ced-437c-9a88-2175b68db84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/button</value>
      <webElementGuid>7ca6c568-8139-4ff1-b798-5e88d9ea2cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnUploadKTPPTCV' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>9b9699c4-f2b3-41e7-b23f-7923aa348159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
