<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya_1</name>
   <tag></tag>
   <elementGuidId>1f534ded-8856-4f8f-b835-cb80ad166d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDataPerusahaanSelanjutnya</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDataPerusahaanSelanjutnya']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a895b00-96b7-42a9-a182-8f11d64f03da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>margin-remover</value>
      <webElementGuid>07cfadbb-a8f2-4c1a-8a8a-f791f07e0b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDataPerusahaanSelanjutnya</value>
      <webElementGuid>858289d8-cc88-4ddc-ae22-cfedea8cadb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>71f722aa-036e-4808-aa34-99b45d1845ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDataPerusahaanSelanjutnya&quot;)</value>
      <webElementGuid>8b067f5a-3499-49e3-a776-54ae419d0b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDataPerusahaanSelanjutnya']</value>
      <webElementGuid>72dbd739-6cec-43d8-9f5d-46c7e65cbc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisBFTransporterDataPerusahaan']/button</value>
      <webElementGuid>8a176e0d-a879-4036-a328-88a776bf84fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. HP PIC Sales Marketing 3'])[1]/following::button[1]</value>
      <webElementGuid>8e404808-7d12-4342-b570-d2971d8349c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama PIC Sales Marketing 3'])[1]/following::button[1]</value>
      <webElementGuid>5aa515cd-132b-4140-88b8-f8a2fab05813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat Umum'])[1]/preceding::button[2]</value>
      <webElementGuid>c1ff963c-701d-4105-b795-a1047ed4503d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat Tambahan'])[1]/preceding::button[2]</value>
      <webElementGuid>8adf2478-a7a5-41c0-93f5-57ad2b4ddb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>6080546a-7d4b-4792-9b86-88035c63ef83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button</value>
      <webElementGuid>32bae157-78ca-48a0-b341-dff99c76d71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnDataPerusahaanSelanjutnya' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>1cab3af5-7dcd-4eea-8f3d-8a4f47a45c6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
