<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload</name>
   <tag></tag>
   <elementGuidId>0939d7f2-1f21-4ec7-b956-0c684de0df64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnUploadFotoProfil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnUploadFotoProfil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df228159-ba57-4931-8697-886f7ca2be6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az</value>
      <webElementGuid>9635f706-9f56-479f-86ac-f37f59536688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnUploadFotoProfil</value>
      <webElementGuid>0a98a3cf-2eb7-4dab-a84e-87a01ec7d3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#ModalBox</value>
      <webElementGuid>e42d74f1-8a77-47a4-be5e-589263af9c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>a453682a-c807-4153-b6ac-9fbbcdf71ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parameter</name>
      <type>Main</type>
      <value>{&quot;type&quot;:&quot;ModalUpload&quot;,&quot;value&quot;:&quot;asd&quot;}</value>
      <webElementGuid>c4fbb5bd-dbf2-44e0-9601-0d8613bca56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>1d2b2c60-289f-40bd-8e02-55f53d49f849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnUploadFotoProfil&quot;)</value>
      <webElementGuid>6f0032bd-0ec1-4241-9c4d-110154d151e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnUploadFotoProfil']</value>
      <webElementGuid>ae1ee742-5ce4-476d-864d-05899bb558d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisBFTransporterDataPerusahaan']/div/div[6]/div[2]/div[2]/button</value>
      <webElementGuid>ada60d0e-fc56-45c2-bdac-6721e07e44df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logo Perusahaan*'])[1]/following::button[1]</value>
      <webElementGuid>a4b05ad9-746c-448d-8a66-1966b6dc3a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Perusahaan'])[1]/following::button[1]</value>
      <webElementGuid>435d6b6b-7b90-43bc-82f6-ef1b0840732a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file jpg/png max. 10MB'])[1]/preceding::button[1]</value>
      <webElementGuid>df93727d-1608-4366-9c11-e64195dbd61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Perusahaan*'])[1]/preceding::button[1]</value>
      <webElementGuid>0136e4fb-f538-48ed-8a13-5bcf8f982091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[2]/button</value>
      <webElementGuid>73fdc618-5553-4077-ad7a-8f45243f42ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnUploadFotoProfil' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>4a852b1e-90ce-4801-bbc6-3e4c584e1897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
