<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama PIC Sales Marketing 2_Pic2Name</name>
   <tag></tag>
   <elementGuidId>2fef5f68-119b-43cc-a8c0-fcddef1c9c3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Pic2Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pic2Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15ea3016-daf0-4bca-a561-a1837b512284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input</value>
      <webElementGuid>f00fb27e-d3b9-44b6-9c87-eba7343b6a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6530a7af-66bc-4787-863e-a0a71789b64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama PIC Sales Marketing 2</value>
      <webElementGuid>8e07d39c-f7b4-4745-bd9b-3bfa90b852f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pic2Name</value>
      <webElementGuid>2c2ea18b-2392-48ed-8a1f-195656913e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pic2Name&quot;)</value>
      <webElementGuid>c3ccf61e-6e67-48ef-a7d6-105c5947a6ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pic2Name']</value>
      <webElementGuid>6890402f-e818-40b0-aaa9-37836ee6272e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldPic2Name']/input</value>
      <webElementGuid>c98f0d37-d12f-47e9-83f5-fe3304e0032b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div[2]/div/input</value>
      <webElementGuid>fb33cb48-1f82-4646-a163-4f089e30f133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nama PIC Sales Marketing 2' and @id = 'Pic2Name']</value>
      <webElementGuid>2da9e6db-0c24-4b39-a290-d42760c9a2b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
