<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repair  Maintenance Service_ChkBoxPer_86aca7</name>
   <tag></tag>
   <elementGuidId>18e4ed3e-5234-4876-b1ef-2e25463fb849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChkBoxPerusahaan105</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkBoxPerusahaan105']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b1ddac9-8e43-4d05-9c8c-eb2e8568dd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>565e6518-f03d-4f7f-86d4-bd1d419e7797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-menu chkbox-perusahaan</value>
      <webElementGuid>54cc0d36-aff3-415b-b671-991aaa3c9670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkBoxPerusahaan105</value>
      <webElementGuid>614faaee-daed-4399-a983-d9b4ed2389b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkBoxPerusahaan105&quot;)</value>
      <webElementGuid>a922e42a-5582-4f75-9a5c-43a55eccc26a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkBoxPerusahaan105']</value>
      <webElementGuid>851ee542-f113-498b-944b-1fb82e0a6744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section_perusahaan']/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>96119947-0d2b-4daf-9dea-69cc5207b57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>b9214206-b8bd-48c8-939f-0ed0c11f1788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ChkBoxPerusahaan105']</value>
      <webElementGuid>7982a3d3-b032-4296-8557-6c731f71b8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
