<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transportation Store_ChkBoxPerusahaan925</name>
   <tag></tag>
   <elementGuidId>20fea287-b41f-46ce-ba1d-cd878f5a82a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ChkBoxPerusahaan925</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkBoxPerusahaan925']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2ab0d48-0d57-4b9c-9132-b273651ef9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>41c7dff1-b876-4cd6-a2af-8284ef805048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-menu chkbox-perusahaan</value>
      <webElementGuid>63563c8a-aa75-4945-9234-ecb139f37d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkBoxPerusahaan925</value>
      <webElementGuid>bc2d2a44-63ae-48d5-a790-304d2b245da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkBoxPerusahaan925&quot;)</value>
      <webElementGuid>a773021c-95de-4fed-a0fa-4f95e2694337</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkBoxPerusahaan925']</value>
      <webElementGuid>3f2a13b0-d3f0-40cf-ad17-63648fd3ba1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section_perusahaan']/div/div/div/div/div/div/input</value>
      <webElementGuid>70aa2695-834e-4c4a-9f59-ce34fe038f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/input</value>
      <webElementGuid>e64651ed-16ee-41eb-bc6b-e287a36d3d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ChkBoxPerusahaan925']</value>
      <webElementGuid>8bca3354-7340-410b-93c8-37de79b78c8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
