<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no-border form-control dropdownGoogl_af628b</name>
   <tag></tag>
   <elementGuidId>82c5df15-87c9-420c-b3e7-df8da8a2163b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.no-border.form-control.dropdownGoogle.ff-medium.fs-12.fc-1b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67ca0612-a97c-4d10-8893-e19ced95c1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ad7b365-478d-4045-bae2-fc03d2ea1d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border form-control dropdownGoogle ff-medium fs-12 fc-1b</value>
      <webElementGuid>ad9f148f-e0a1-4ad1-9e9c-67dbbb752843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>6b11ad73-d78f-4804-9545-ff528d882e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search</name>
      <type>Main</type>
      <value>kecamatan</value>
      <webElementGuid>5087d585-e807-4890-9c5c-f8fc0de5c395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>LokasiIklan</value>
      <webElementGuid>5774f113-23b3-4968-92c0-11d49128134a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Anda Belum Memasukkan Kecamatan!</value>
      <webElementGuid>d55fbc66-b6bf-4756-bff3-a768d5f6cdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0488293d-07c3-4bfc-aa8e-3c9cbda6fb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;parentDropdownGoogle d-flex flex-column&quot;]/div[@class=&quot;input-group mt-8 ComponentField component-input-border-container flex-middle&quot;]/input[@class=&quot;no-border form-control dropdownGoogle ff-medium fs-12 fc-1b&quot;]</value>
      <webElementGuid>ef5e5c3c-780c-4673-b8b6-ae2351cce5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>d0b01aa4-f8b8-42f3-8f13-d7b9d83d108f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[9]/div/div[2]/input</value>
      <webElementGuid>738fe73a-f783-4ca3-8698-bc5e30cea95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/input</value>
      <webElementGuid>e13e4ba5-1c3c-4d3a-826c-3a1dc05fbb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Kecamatan']</value>
      <webElementGuid>15ba5f5c-497e-46b2-9874-9f5458c2374d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
