<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3db79e61-aa21-4d74-aec9-5137626cbfd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeSpecialFirstTimer > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeSpecialFirstTimer']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d4942e25-cf69-45f8-bff9-4daa3c94123a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_resources/themes/muat/image/Subscription/close.svg</value>
      <webElementGuid>1e3dfd21-08ff-437a-a605-3a81c84813ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeSpecialFirstTimer&quot;)/img[1]</value>
      <webElementGuid>70fc4623-9722-4d10-a864-a17363cf53de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='closeSpecialFirstTimer']/img</value>
      <webElementGuid>1203b167-e89e-4a27-90d6-ec3efe862fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>00ca67a6-b762-4623-bfa3-b22a5c83ab2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_resources/themes/muat/image/Subscription/close.svg']</value>
      <webElementGuid>70c594bd-8ae2-4d75-aefc-b3ceb2c11ddf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
