<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya</name>
   <tag></tag>
   <elementGuidId>def49109-b0a5-497a-bc69-a0eb60880868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalConfirmPratenderOverride > div.modal-dialog.modal-dialog-centered.justify-content-center > div.modal-content > div.modal-body > div.d-flex.justify-content-center > button.btn-outline-blue.tombol-putih.btn-fix.ff-demi.yes-confirm-finished.btn-check-click.yes-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24353a6e-5289-4d72-adb4-e9ce5463b29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecb5cd23-4051-42b2-b2bb-450354ddf7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>884c58c4-4cbe-4127-9036-114886428cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modalconfirmnonaktif</value>
      <webElementGuid>89854384-b14c-46fa-8ee8-0cc0ed723172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-outline-blue tombol-putih btn-fix ff-demi yes-confirm-finished btn-check-click yes-btn</value>
      <webElementGuid>60ea498f-b0ae-43a2-9eb9-27e765b8e428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>https://qc.assetlogistik.com/bigfleets/prosesTenderAktifGrid</value>
      <webElementGuid>c09202db-3022-4463-a91e-d04c91776eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>0da4c836-15de-488b-b31e-c932a4cc47b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalConfirmPratenderOverride&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered justify-content-center&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/button[@class=&quot;btn-outline-blue tombol-putih btn-fix ff-demi yes-confirm-finished btn-check-click yes-btn&quot;]</value>
      <webElementGuid>194217e5-ef29-4842-9219-b875bd74eedc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>093ad9b2-4e92-464a-b923-684dbac1c7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalConfirmPratenderOverride']/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>65a65cb5-d05c-4e2b-92ff-82ad959ca31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[3]/following::button[1]</value>
      <webElementGuid>13a36531-7685-4090-a0d8-e93481781a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda yakin pilih info pratender ini? Data akan terisi dari nomor pratender yg dipilih'])[1]/following::button[2]</value>
      <webElementGuid>869f5c83-dcc9-4372-8eb6-5391bcac3306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahapan yang akan Anda lalui dalam Proses Tender'])[1]/preceding::button[1]</value>
      <webElementGuid>92e6d1f8-d4ef-4c0e-916e-70151d358ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Pra Tender'])[1]/preceding::button[1]</value>
      <webElementGuid>21c3dc33-2561-401f-a96a-0da95219576c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>bdc50d09-c9c9-42bb-a40e-a025d7013a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ya' or . = 'Ya')]</value>
      <webElementGuid>99e039aa-d0eb-434f-9b57-9e070d3e0644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>0781429a-9d27-49ca-b07a-106c5ed99159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalconfirmback']/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>6e54fd9d-54bc-44a0-83ce-736ceb1c01b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/following::button[1]</value>
      <webElementGuid>eb2703b0-e307-4993-8d4b-be2103af175e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda yakin ingin berpindah halaman? Data yang telah diisi tidak akan disimpan'])[1]/following::button[2]</value>
      <webElementGuid>abad64a3-826b-4204-8f00-682c9ecb8ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Lokasi'])[1]/preceding::button[1]</value>
      <webElementGuid>e54cfad7-6212-4f37-9ef9-c5194aeda8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terakhir Dicari'])[1]/preceding::button[1]</value>
      <webElementGuid>fc07c1ae-be1b-4e5a-b295-c40dbaf05b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ya']/parent::*</value>
      <webElementGuid>13420f60-528e-402f-a1b9-e3e13d73e946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>1c70b662-15da-4293-b2a1-6ed118f6959f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
