<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat</name>
   <tag></tag>
   <elementGuidId>70b2d838-26a1-458d-8044-e596141f9ce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efe72a5e-de66-4b0b-8427-d32a9cd0d029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ae7baf5-b7d7-4af1-b930-dd2da715a8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-submit</value>
      <webElementGuid>77f30062-2b99-40ab-87f3-a62bad1bb116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn upload-btn btn-fi btn-flex</value>
      <webElementGuid>3ce718af-38de-4335-92a2-8bb99378a2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buat</value>
      <webElementGuid>379d20d3-417e-4c75-b77c-b54b0109d4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-submit&quot;)</value>
      <webElementGuid>56997455-193d-49c6-b268-b8905b4ff1e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form-submit']</value>
      <webElementGuid>a2fe7b71-80bb-4fcf-9764-127e6a9e8a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[5]/div/button</value>
      <webElementGuid>1c38b31a-bfa4-4566-80ed-977fe24b6d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan :'])[1]/following::button[1]</value>
      <webElementGuid>dbbb02f6-0a6a-4a60-a2d7-1aa6f38f398a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[2]/following::button[1]</value>
      <webElementGuid>31eea39f-d0f7-4264-8924-d56fa9e10085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Destinasi / Bongkar'])[1]/preceding::button[2]</value>
      <webElementGuid>54cd5480-52b4-4802-9286-646711569d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi Pick Up / Muat'])[1]/preceding::button[3]</value>
      <webElementGuid>712d6910-3e44-473d-9e94-65e9dfdef73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat']/parent::*</value>
      <webElementGuid>b1e1b298-ea16-4cce-a50a-3ca644a38097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>357bc50d-a5c4-4007-93d5-c65c77577e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'form-submit' and (text() = 'Buat' or . = 'Buat')]</value>
      <webElementGuid>58ff6e64-8952-4478-8b6f-d9cd1accb598</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
