<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sd_tahap_tender4max_date</name>
   <tag></tag>
   <elementGuidId>bb5953a2-ff0e-410e-8655-c41c6247f9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#max-date-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max-date-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acc6ed30-c8aa-442c-9f05-6836cc5db93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5313b5f2-9dfd-4e0d-b3ac-324cb05776f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tahap_tender[4][max_date]</value>
      <webElementGuid>dcad5e44-4f6d-495a-b111-46b7a5198fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>Tanggal akhir</value>
      <webElementGuid>8dd202b1-4a33-42b6-8cb4-82cc358028b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>DD MMM YYYY</value>
      <webElementGuid>67c9405f-556a-49a8-aaf8-b6b6a5340446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max-date-5</value>
      <webElementGuid>51f6f937-cc95-4c4c-9bcd-ee093092f8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>20 Sep 2023</value>
      <webElementGuid>631e3a54-ca0b-4815-806d-b01246fc2f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tglSelesai input-pratender form-control input-medium input-text-pratender mr-10 max-date datepicker akhir i6 noOverlap optional</value>
      <webElementGuid>22b2992f-f269-458e-86ee-67a01fc29bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal akhir</value>
      <webElementGuid>56f33f7e-0460-4d4e-acb1-8a4468b27d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provide</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>5f801947-748a-4c3f-8a96-1d0c40f95e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max-date-5&quot;)</value>
      <webElementGuid>dfd5c891-24c4-4108-81c2-74696c95eaa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max-date-5']</value>
      <webElementGuid>f68387e4-d429-4e73-9b5a-b803f00d90eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tahapEksekusiTender']/div[2]/input[2]</value>
      <webElementGuid>20607683-75dd-415e-a4ae-6b71fc0c049f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input[2]</value>
      <webElementGuid>1be311ac-5714-413d-9858-2aab4b1a27c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tahap_tender[4][max_date]' and @id = 'max-date-5' and @placeholder = 'Tanggal akhir']</value>
      <webElementGuid>21f7c908-ba3d-4daf-89d3-79f5edea7907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
