<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_x_tinggi</name>
   <tag></tag>
   <elementGuidId>def34dc2-7199-4add-b2d2-ebc234f76e5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dimensi_tinggi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dimensi_tinggi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc7a47d4-4c87-4811-bcf3-8e221994a5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a36ed65-99f2-411c-8027-d27d416c4476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tinggi</value>
      <webElementGuid>8d2d97d2-09f7-4573-9d6c-67d1f434b2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>125a1d06-e770-4b75-aa03-2c42e11ffb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-component dimensi ff-medium  fs-12 formatDimensi satuan_berat_dimensi fc-1B text-center</value>
      <webElementGuid>bd2078f6-a44b-45b9-8fb4-64e36acaf515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dimensi_tinggi</value>
      <webElementGuid>1f78019b-d406-4b0a-a451-b38753fd6446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>#dimensi_tinggi</value>
      <webElementGuid>a31e62ef-facf-4b96-bf76-9a4b1fe09468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dimensi_tinggi&quot;)</value>
      <webElementGuid>12f2edb9-f5ba-44f1-8a5b-904dbf2a7855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dimensi_tinggi']</value>
      <webElementGuid>0d454d8c-63b0-4fd5-8bc2-3cc28f75aad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[2]/div[2]/div[3]/div[2]/div/input[3]</value>
      <webElementGuid>fb7cfe60-87c5-40c5-b090-2820eabbded3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[3]</value>
      <webElementGuid>db338c4d-c1e6-4804-ba21-2364abd817a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tinggi' and @placeholder = 't' and @id = 'dimensi_tinggi']</value>
      <webElementGuid>661b6829-de81-44fa-a414-0f650afdba8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
