<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Muatan_nama_muatan</name>
   <tag></tag>
   <elementGuidId>cbfe661d-424a-4882-94b4-5908b6d8d3e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama-muatan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nama-muatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c08cf2f-71bb-4b40-aa59-8303ddea9e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c8f368a-90c8-4d0b-85d1-ac3927f3d8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_muatan</value>
      <webElementGuid>41bbd98a-4212-42e7-9787-6f116be6dc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama-muatan</value>
      <webElementGuid>e7c8b23e-a014-4a32-ab2c-dcd56c7f9a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>acf9e065-6770-4301-a3a3-215cbd341d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fs-12 fc-1b ff-demi input-text-pratender pl-8px</value>
      <webElementGuid>efc1b9b5-246e-4931-acc9-c92549f99185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Muatan</value>
      <webElementGuid>a05d0142-1e7e-430d-aaed-b8d8d72ad7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama-muatan&quot;)</value>
      <webElementGuid>1dfa5f16-eb84-4947-a375-cd428fead9de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama-muatan']</value>
      <webElementGuid>e2e93f10-cd0c-4b08-9768-8a46b0492b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>461d97d9-ff10-45b4-99ce-54dbbf055808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>43f70a4b-7925-45a5-86ef-c10725626658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_muatan' and @id = 'nama-muatan' and @placeholder = 'Masukkan Nama Muatan']</value>
      <webElementGuid>27619e82-bd2d-42f6-9235-c9ffa2ceef19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
