<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(opsional)_berat_muatan</name>
   <tag></tag>
   <elementGuidId>7d6dbde7-00cf-48b6-83cd-552d183b4db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='berat-muatan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#berat-muatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f00f13f5-d2d5-4d81-9f05-8e82ffa80317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6108010f-63ff-46fe-90c5-4caa7c66157f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>berat_muatan</value>
      <webElementGuid>d57a4b53-4334-4ba5-bacf-bbf893071ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>berat-muatan</value>
      <webElementGuid>4b581486-8119-4de5-a3c5-ed296c07fd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3901e4a8-2657-4dc0-8644-2d00d5981463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fs-12 fc-1b ff-demi input-text-pratender input-medium mr-12 format-number-3-digit-after-comma pl-8px</value>
      <webElementGuid>e0dc778a-7f55-4a0d-b7e8-24a3ccb6d7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 50</value>
      <webElementGuid>629daa1c-ffed-43fd-974d-6b7dfdfa8ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;berat-muatan&quot;)</value>
      <webElementGuid>077e767d-11d3-4c0c-b493-f5783e755771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='berat-muatan']</value>
      <webElementGuid>7c711f1a-c76e-4b9f-a2bc-5e10d802f275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-berat']/input</value>
      <webElementGuid>55073ef6-6bf3-42ce-b0a5-fce121660172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>2c1ab73a-b9bf-4b2a-9535-51baef33b20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'berat_muatan' and @id = 'berat-muatan' and @placeholder = 'Contoh: 50']</value>
      <webElementGuid>fa2f99c3-8206-4351-8cf9-d885aee453ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
