<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode_tahap_tender4min_date</name>
   <tag></tag>
   <elementGuidId>e28e6c87-08c6-4fa6-be60-b6a6eb12333b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#min-date-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='min-date-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2b26620-ff4f-4201-8563-8ea0dfd1700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d22b028d-0a1a-4b64-9d8c-3e5f9eca0a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tahap_tender[4][min_date]</value>
      <webElementGuid>fc06fb0d-5296-435c-b010-b6e01dec9026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>DD MMM YYYY</value>
      <webElementGuid>c123434d-1740-4834-bd3c-81f427b4009f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>min-date-5</value>
      <webElementGuid>723284dc-7681-4bcc-8e19-bf55cf8cfdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>20 Sep 2023</value>
      <webElementGuid>c5af7749-dffe-42d4-86ee-ec4212c07fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>Tanggal mulai</value>
      <webElementGuid>1eacb5b8-1134-4d19-af72-d3f6ae04905d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tglMulai input-pratender form-control input-medium mr-8 input-text-pratender min-date datepicker awal i6 noOverlap optional</value>
      <webElementGuid>5fc63a1d-23f9-4551-9c56-61888fa733e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal Mulai</value>
      <webElementGuid>31a3c64b-8129-43f3-aa2d-df46fbb83801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provide</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>7b29b4c4-f162-4b96-8bbd-7b6c7110f859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;min-date-5&quot;)</value>
      <webElementGuid>a3ff83fb-39d7-458b-961d-ec990ce30bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='min-date-5']</value>
      <webElementGuid>94f717fb-e85e-4e14-aaae-c839cbffccae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tahapEksekusiTender']/div[2]/input</value>
      <webElementGuid>9923a75d-caa7-4af7-a10b-0b394de198f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[5]/div[2]/input</value>
      <webElementGuid>4a9038d4-9434-4d7d-a768-ed8121ac89db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tahap_tender[4][min_date]' and @id = 'min-date-5' and @placeholder = 'Tanggal Mulai']</value>
      <webElementGuid>b0efe536-b37a-468f-bf0e-a1efeaa6fe4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
