<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih TransporterMitra</name>
   <tag></tag>
   <elementGuidId>80e9cff1-d832-4836-b662-232fa4cacf45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pilihTransporter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pilihTransporter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06a5b199-ac65-45f8-85a9-0f4a6dffc2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9f6af57-b41b-47cc-a80c-1d21e233b38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary-new ff-demi fs-12</value>
      <webElementGuid>7228a8c6-8523-4b9f-a788-8396270ccd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pilihTransporter</value>
      <webElementGuid>310248ea-844f-4a13-badc-8109910bbab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>a0e5c7bf-297e-4331-911b-07175c64f3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#diumumkanKepada</value>
      <webElementGuid>21dfc5bc-2f08-442e-8735-730213dde33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Transporter/Mitra</value>
      <webElementGuid>4d3e192b-745b-4085-a1bc-b00df62fff5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pilihTransporter&quot;)</value>
      <webElementGuid>d343f7d5-0c3c-4c5f-9c1b-4d0bf3fc82c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pilihTransporter']</value>
      <webElementGuid>7d8f7008-c03b-4b14-8747-796de652d384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pilihTransporterBtn']/button</value>
      <webElementGuid>3fd58cd3-fa8c-4ea9-80b8-b387f0c57545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diumumkan Kepada*'])[1]/following::button[1]</value>
      <webElementGuid>33399b52-10b0-4104-868a-363c6cdbee29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;autogenerate>'])[1]/following::button[1]</value>
      <webElementGuid>cb6370ce-6642-4139-87a9-2cff91fa93b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Judul*'])[1]/preceding::button[1]</value>
      <webElementGuid>036287ee-b910-4aa5-9f8b-4e9050ca32d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Proses Tender'])[1]/preceding::button[1]</value>
      <webElementGuid>d6ecfd10-5036-44ff-8824-e3f113eac812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Transporter/Mitra']/parent::*</value>
      <webElementGuid>41ce1972-b326-43f3-93a3-27f2210e759d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/button</value>
      <webElementGuid>e925cd40-924b-4a9c-897f-5941e2bbba6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'pilihTransporter' and (text() = 'Pilih Transporter/Mitra' or . = 'Pilih Transporter/Mitra')]</value>
      <webElementGuid>78cf14fd-528d-4a4b-9813-afa8d57ab264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
