<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Judul_namaPratender</name>
   <tag></tag>
   <elementGuidId>7b674241-79af-4f86-9694-d25fb3158348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#judul</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='judul']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aed4931-8d26-4ac1-9a70-ab4e72341eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e71dd4e9-7965-46bc-95ab-017e2575372d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namaPratender</value>
      <webElementGuid>48f11720-3286-4ad4-a609-9343752d5b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judul</value>
      <webElementGuid>452e33b5-1fbe-4558-83d1-9ab204d762f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>39aafba7-8228-4c86-a0a5-aac4018f241b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fs-12 fc-1b input-text-pratender</value>
      <webElementGuid>778f5e71-dc9b-4cb6-888d-e2c2616b750a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Judul Tender</value>
      <webElementGuid>4e789c14-855d-41f3-966d-d4f5e4a7d13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judul&quot;)</value>
      <webElementGuid>5e20fbbd-d64f-459e-82f4-9a8bc3c286ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='judul']</value>
      <webElementGuid>d95b4e25-beef-4a0c-b4ea-f80056eaa5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>0cc65ed7-621e-4077-92db-498d1f2d2f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>270ff947-c228-403e-b88a-cc16f9ec5088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'namaPratender' and @id = 'judul' and @placeholder = 'Masukkan Judul Tender']</value>
      <webElementGuid>f79e2cde-1e44-41f0-b4d5-6b613424f579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
