<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode_tahap_tender1min_date</name>
   <tag></tag>
   <elementGuidId>56d18be0-1824-462f-a0a8-7ebb1e36c33e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#min-date-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='min-date-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fe6459b-a964-4581-9f5c-8080572d90de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fb8e3a1-3703-43c9-9abe-0767c335c3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tahap_tender[1][min_date]</value>
      <webElementGuid>039d8605-f2ee-4f2a-b83a-22b0c322329d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>DD MMM YYYY</value>
      <webElementGuid>779a1d9b-2346-457a-8e7b-aeeecacc9a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>min-date-3</value>
      <webElementGuid>d125bc84-5f0a-4140-a915-491ff6d2512e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>05 Sep 2023</value>
      <webElementGuid>2016c24e-ce04-4012-bbdb-b530440571af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>Tanggal mulai</value>
      <webElementGuid>dcf62a01-9761-4c3f-8eee-1197517ec40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tglMulai input-pratender form-control input-medium mr-8 input-text-pratender min-date datepicker awal i3 noOverlap</value>
      <webElementGuid>5ebbb715-2517-4161-b4d7-d0b986c0ffea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal mulai</value>
      <webElementGuid>2f02675e-658e-4d2d-9457-666be8e3f5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provide</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>d7761f0e-c70c-46a9-84db-0215eaa3df62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;min-date-3&quot;)</value>
      <webElementGuid>cf416f28-63b4-4831-814b-85137ee2d9c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='min-date-3']</value>
      <webElementGuid>62ae566e-9a5e-4f85-949a-bca857fd460f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tahapSeleksiPemenang']/div[2]/input</value>
      <webElementGuid>aa288cd4-5c01-4804-9bdf-74701b18451e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>1093b4e5-0f01-4e25-b3c7-fd7abc2c7397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tahap_tender[1][min_date]' and @id = 'min-date-3' and @placeholder = 'Tanggal mulai']</value>
      <webElementGuid>c219df48-112c-486b-9c43-58282a03e827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
