<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kota Surabaya_rute0destinasi</name>
   <tag></tag>
   <elementGuidId>c4d78849-0775-491a-bafc-518c5aa61fd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#destinasi0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='destinasi0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a55cd67-a798-4d7a-b962-b9fb603004fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a24e9cb3-a311-4e13-ba70-8f2addcf4d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rute[0][destinasi]</value>
      <webElementGuid>4ccf5d9c-66a6-42a3-9d94-8dace0554bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>destinasi0</value>
      <webElementGuid>0ab70f1c-0444-4122-a768-4d2e271344de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c3f554c7-5791-4368-93bb-cc73f9b6f3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fs-12 fc-1b ff-demi input-text-pratender pl-8px inputan-kota-destinasi mr-12 hg-32</value>
      <webElementGuid>7b77b6eb-cf3b-469d-b2fd-664a7d31a01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lokasi Destinasi</value>
      <webElementGuid>489c6d7c-df3d-44cb-9ea7-0ce130d8ebb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;destinasi0&quot;)</value>
      <webElementGuid>ce675d84-0157-4842-b103-8609f7f891a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='destinasi0']</value>
      <webElementGuid>2f944b00-fec5-45b4-936e-a093ddf3db51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row-rute-0']/div[2]/input[2]</value>
      <webElementGuid>b498e564-431e-4787-8c9c-c7a13f29b494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input[2]</value>
      <webElementGuid>25bd3bfc-41ee-495b-ac9b-5970393fb9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'rute[0][destinasi]' and @id = 'destinasi0' and @placeholder = 'Lokasi Destinasi']</value>
      <webElementGuid>17fe2f04-c061-4570-af22-4bf2b24f0c16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
