<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Muatan_nama_muatan</name>
   <tag></tag>
   <elementGuidId>cf055593-4ac2-4474-8a87-17848d29a4c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama-muatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama-muatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>577f57e7-a549-425e-b66c-5700057414db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43c6a213-55ae-4c21-a2e2-f7ac82eaa2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_muatan</value>
      <webElementGuid>6dc81859-861c-4ca4-ae19-f4bf58296c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama-muatan</value>
      <webElementGuid>5f2b0288-48d9-4a1a-a934-93ecb7a78c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4e79015f-b429-45f6-9763-5c89b36ad69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fs-12 fc-1b ff-demi input-text-pratender pl-8px</value>
      <webElementGuid>06466b28-cf7f-4cbe-8862-d0c2088bf7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Muatan</value>
      <webElementGuid>7121b4ad-def6-47d2-b3bc-6e189f31820d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama-muatan&quot;)</value>
      <webElementGuid>adfda2e5-6e9f-4d73-a9db-b4f435c22820</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama-muatan']</value>
      <webElementGuid>d41c70d9-f97d-43cf-ab6b-d2941940b54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-frontend']/div/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>657fa745-55e4-4eb4-8cbc-54bda587dec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>f77a6e84-6d04-4184-9eef-1f1a5ec4f7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_muatan' and @id = 'nama-muatan' and @placeholder = 'Masukkan Nama Muatan']</value>
      <webElementGuid>98373cba-feb0-4e27-86dd-344e62367bdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
