<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c6590386-d927-47a1-9fc2-814c60f55d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.close.btn.closeMaps > span > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapsModalnya0']/div/div/button/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>57bc51b2-a828-402f-9aba-6455bcc697cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_resources/themes/muat/image/icon/close-biru.svg</value>
      <webElementGuid>9f7f412e-7779-4270-8473-36a3025e675f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>545ca954-786c-4d8c-a782-1b9da39a63d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>dc58319c-713b-4683-b0a8-6ddfc92f5456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapsModalnya0&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content modal-see-map&quot;]/button[@class=&quot;close btn closeMaps&quot;]/span[1]/img[1]</value>
      <webElementGuid>77fba4f1-feb8-4194-9c86-357d67a0d97d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mapsModalnya0']/div/div/button/span/img</value>
      <webElementGuid>94d53864-e756-470f-99dd-857b556b221c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/img</value>
      <webElementGuid>e6d2b1c6-4281-4e2c-aec3-6a0d30a5e16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_resources/themes/muat/image/icon/close-biru.svg']</value>
      <webElementGuid>0e495275-63ed-4612-835c-b51232d5f2e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
