<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Kantor di Indonesia_FormatInteger</name>
   <tag></tag>
   <elementGuidId>b92ac32a-38f1-4540-8487-04e5e3106210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.FormatInteger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div/div[5]/div[1]/div[2]/div[2]/div[5]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc46edc7-faab-43fb-8734-12275632af71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormatInteger</value>
      <webElementGuid>0c9fd052-3904-48da-8334-ba3e0606cdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ad1766b-a643-45ae-ab10-7327649c5a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Jumlah Kantor di Indonesia</value>
      <webElementGuid>fe8fc54c-31c6-4249-ab61-2213ba661fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>JumlahKantordiIndonesia</value>
      <webElementGuid>9ab4bc08-c76b-423c-892a-0be8144c49c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_value</name>
      <type>Main</type>
      <value>Maksimal Jumlah Kantor 9.999.999.999.999</value>
      <webElementGuid>6206105f-1bcc-4d81-b901-c80c2d08709f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_value</name>
      <type>Main</type>
      <value>Minimal Jumlah Kantor 1</value>
      <webElementGuid>2aab3aff-e29e-45fe-88a1-63672ac9c60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_value</name>
      <type>Main</type>
      <value>9999999999999</value>
      <webElementGuid>5610e727-d668-46b4-b11e-de2087d34c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>59ff3a2e-df37-405b-8be8-6f679feec38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12 component-262 component-input-border-container&quot;]/input[@class=&quot;FormatInteger&quot;]</value>
      <webElementGuid>7daa8d75-e361-4638-aabd-361b476478b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>89266773-7056-4dac-a3f0-9bc2d9bed0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[5]/div[2]/input</value>
      <webElementGuid>c0692780-7ba3-457a-b20f-0cb305528a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>0cb73976-0db5-46a3-b2d6-4cd1c218eb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukan Jumlah Kantor di Indonesia']</value>
      <webElementGuid>ebc36a37-e725-481b-9121-667e3f6e11fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
