<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no-border form-control dropdownGoogl_af628b</name>
   <tag></tag>
   <elementGuidId>9be1b0af-2afb-4479-9a7b-67af83781b62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.no-border.form-control.dropdownGoogle.ff-medium.fs-12.fc-1b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa104913-d927-4dc3-b135-0dfd048c1def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>047886b0-f5a9-4cb8-8f0e-a5ee0f4fdd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-border form-control dropdownGoogle ff-medium fs-12 fc-1b</value>
      <webElementGuid>dc205f8d-6f3f-416f-ab6c-6375397bffad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Lokasi Iklan</value>
      <webElementGuid>3a73afad-2ace-497a-a646-fe7bdc792f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search</name>
      <type>Main</type>
      <value>kecamatan</value>
      <webElementGuid>b647fb4c-16b7-4fd6-8cfc-a595db4e0d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>LokasiIklan</value>
      <webElementGuid>296dc4df-a097-4887-8d84-ab1e4d4dec2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>39c3e486-d6ef-40e2-bc20-87a9837365ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>99f17f8a-cca9-422f-829c-5f1fee4c7c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;parentDropdownGoogle d-flex flex-column&quot;]/div[@class=&quot;input-group mt-8 ComponentField component-input-border-container flex-middle&quot;]/input[@class=&quot;no-border form-control dropdownGoogle ff-medium fs-12 fc-1b&quot;]</value>
      <webElementGuid>d7e60759-f738-4b39-88d3-17303bfd9bea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>d93f0588-8d91-4309-be9c-d09b33a0cc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[9]/div/div[2]/input</value>
      <webElementGuid>e428859c-f9c7-450b-8676-e8da6ffb9f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/input</value>
      <webElementGuid>aacabfaf-571d-459d-b00c-1768b9da6346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Lokasi Iklan']</value>
      <webElementGuid>1157fa21-77d4-47df-839e-7ddec636c923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
