<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_text_1_2</name>
   <tag></tag>
   <elementGuidId>f1c74888-fe4b-4d20-b8f0-e5639c726bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1f3d86b7-97fc-4af6-9de4-cf3d7a095fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcba29eb-d82b-4047-aa5f-5060f4fd0be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex : Senin - Jumat, pukul XX:XX - XX:XX</value>
      <webElementGuid>255421d2-e2d2-41f6-91fa-62de3796e757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>WaktuOperasional</value>
      <webElementGuid>23957c63-027a-4c64-b99c-5fa57fe78183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 1000</value>
      <webElementGuid>92c016cf-e6ca-4b56-b163-5d5d53f905b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>314d1c9d-8426-4d61-a63c-a7e276d7aa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>b0378b02-64af-469e-b5a4-c4ce814bf5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>33ff3b38-99ed-4d43-a0fd-8e874bba2c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>34dceb5a-eb53-4f85-b7af-ad2e56a3ab9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12 component-262 component-input-border&quot;]/textarea[1]</value>
      <webElementGuid>6f3394a1-45cc-4519-bd6b-7055166de05b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@type='text'])[3]</value>
      <webElementGuid>563d880e-1c71-4508-a710-e223053f58e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[8]/div[2]/textarea</value>
      <webElementGuid>1b0e808c-69cf-4da3-9e91-2c36d4911677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/textarea</value>
      <webElementGuid>fd08d343-a175-4113-989e-69664690fac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @placeholder = 'Ex : Senin - Jumat, pukul XX:XX - XX:XX']</value>
      <webElementGuid>775a4e72-9ba8-445e-9501-edb94794e4de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
