<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_text</name>
   <tag></tag>
   <elementGuidId>0732326e-2025-4af9-af89-3b20b54df0ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e2e52afe-db8c-4381-a542-6721881566ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ca7b023-2505-421b-8241-4d69b4a3b3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Tentang Perusahaan</value>
      <webElementGuid>ad1c9312-8a80-417e-b764-6f6180d72d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>TentangPerusahaan</value>
      <webElementGuid>fd13efd2-e4ca-491e-93b2-5a18b559747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 1000</value>
      <webElementGuid>ef2fc33c-05e9-4721-8823-dd0ce02ba29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>7bd17ff7-a76e-443f-bf83-ebfe0cafb026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>6a677c3d-c96d-4347-8f3c-ba6b2ba26e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>834263c9-2cea-49e5-b887-fdfac4d33bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d0a98a5d-c77e-46d4-92c7-c4670dce7397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField d-flex ff-medium fs-12 component-262 component-input-border&quot;]/textarea[1]</value>
      <webElementGuid>2ef57e81-9352-4191-b0cf-27972b443789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>32932f15-7375-4b19-b445-33cce793edf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[6]/div[2]/textarea</value>
      <webElementGuid>ed0489a9-115e-4b16-bd0f-fd3fdf189745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ed8b6ef3-5c00-4f1a-af4b-ef6f232f440d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @placeholder = 'Masukkan Tentang Perusahaan']</value>
      <webElementGuid>b7296ce0-ad76-4268-b42d-b6e62b0e7d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
