<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ff-medium fs-12_1</name>
   <tag></tag>
   <elementGuidId>8df648ba-cf03-4cdd-a5b0-e7fc5108a5a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db67fffd-c6bc-4c1c-90f9-8e5cd18bdf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-medium fs-12</value>
      <webElementGuid>7c277390-8cf5-4bea-af48-6329802b8929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f09b08ce-bddd-40bf-9e95-bf3b018299ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feform_column</name>
      <type>Main</type>
      <value>Keahlian</value>
      <webElementGuid>3b86501c-c2cf-47ba-a479-dc2ce5ee1322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Keahlian</value>
      <webElementGuid>efe19549-0c13-4630-8602-c108f83dcc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_max_char</name>
      <type>Main</type>
      <value>Maksimal karakter adalah 255</value>
      <webElementGuid>41d66fff-0da7-460f-947a-24f3174e0f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_min_char</name>
      <type>Main</type>
      <value>Minimal karakter adalah 5</value>
      <webElementGuid>3f975f0a-bb63-4154-a66d-0bcdb77e499a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alert_required</name>
      <type>Main</type>
      <value>Wajib diisi</value>
      <webElementGuid>f5bb0bd4-fb0e-49b4-8b60-488472724e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max_char</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>adca7b20-1c59-4691-873a-4f30b8a89c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_char</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>52cdb236-f4a6-4607-8ff4-40ac6bd0ed2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasangIklanForm&quot;)/div[@class=&quot;FormComponentContainer&quot;]/div[@class=&quot;ComponentField component-262 component-input-border&quot;]/input[@class=&quot;ff-medium fs-12&quot;]</value>
      <webElementGuid>3e60018c-6a1e-4f57-94ec-33db3ef80d40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>6aada9e3-b3ff-4d2b-964e-783827478932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[9]/div[2]/input</value>
      <webElementGuid>06776ac9-b11b-431b-b6f1-d3b5decaaf07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>cbcbf745-4e89-47a5-90d0-2b92491fb5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan Keahlian']</value>
      <webElementGuid>24a0e8f3-3174-48fe-b4a3-06cc93647880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
