<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Masukkan Rate Keahlian 2</name>
   <tag></tag>
   <elementGuidId>ca4eda53-d9c9-4ab9-ad46-dc92d8d4d600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-to4f-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[1]/div/div[5]/div[1]/div[2]/div[2]/div[12]/div[2]/div/span/span[1]/span/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac8fcaa0-c14c-420c-a7a7-f4400206a2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>17a38dfd-6b69-4dcd-8b73-92b4a92704d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-to4f-container</value>
      <webElementGuid>3047bc2b-08ea-4b57-8b26-975029c38e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>791c4a3f-f227-452e-b23f-1f6cfa6460fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cbef3cc8-a110-443a-b83d-4fa0767f8c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masukkan Rate Keahlian 2</value>
      <webElementGuid>de6c86dd-461e-4ddb-84f3-e4f62d4bfdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-to4f-container&quot;)</value>
      <webElementGuid>28792a75-48f6-4edd-a551-f360b573c615</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-to4f-container']</value>
      <webElementGuid>b1c7b106-77a0-4012-a6ee-709396083bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasangIklanForm']/div[12]/div[2]/div/span/span/span/span</value>
      <webElementGuid>8780e216-9103-41b7-9812-9a0971fa2676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate Keahlian 2'])[1]/following::span[4]</value>
      <webElementGuid>284d15fe-1595-4b04-9d9c-e33cbe4c9706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keahlian 2'])[1]/following::span[4]</value>
      <webElementGuid>d9146fea-6705-4283-961d-7c10a10538a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keahlian 3'])[1]/preceding::span[4]</value>
      <webElementGuid>27f5efe1-82d0-409d-8c0c-9a2e27a78976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/span/span/span/span</value>
      <webElementGuid>578140ca-a1db-4426-b7ec-e64163a18bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-to4f-container' and (text() = 'Masukkan Rate Keahlian 2' or . = 'Masukkan Rate Keahlian 2')]</value>
      <webElementGuid>52be4e35-2266-428f-b06b-fa1ef4c77874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
