<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar_shipper_tm</name>
   <tag></tag>
   <elementGuidId>04f4faf0-ba06-418f-8042-1dbec3d028ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btnKelengkapanPTSelanjutnya&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnNextRegisBFShipper_step3_ptCV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf36b748-fcff-4617-a347-a58d7ebeea6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol-primary-az margin-remover ff-demi-az</value>
      <webElementGuid>f57490b1-8352-4602-bd16-bf55c65e7b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnNextRegisBFShipper_step3_ptCV</value>
      <webElementGuid>25cb9207-27a9-4df8-8337-9f00c85cfb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Daftar
            </value>
      <webElementGuid>185ba38b-ceca-433c-b418-0374e8425631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnNextRegisBFShipper_step3_ptCV&quot;)</value>
      <webElementGuid>8396c3ad-d23d-4061-8e2c-c195c2d13154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnNextRegisBFShipper_step3_ptCV']</value>
      <webElementGuid>2e6bfa05-3c76-4e1b-9a8e-28c4992765d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormRegisBFShipperKelengkapanLegalitasPTCV']/div/div[12]/button</value>
      <webElementGuid>5f88c1e2-a666-45b2-9311-8e0dd9cdd6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format file jpg/png/ pdf/zip max. 5MB'])[3]/following::button[1]</value>
      <webElementGuid>085e95d0-d94f-4e6d-a504-e14f8522cabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[10]/following::button[1]</value>
      <webElementGuid>f2af8c93-c3c9-40a8-8d30-50b0aeaa834d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukuran File melebihi batas 5mb!'])[2]/preceding::button[1]</value>
      <webElementGuid>8857d756-5316-4dcc-9a05-0ce80f15eeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>1c72f1b7-14bb-4b74-9ca1-c080d0a58382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/button</value>
      <webElementGuid>b3a67914-acc3-4794-8f7b-d169658c83a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'BtnNextRegisBFShipper_step3_ptCV' and (text() = '
                Daftar
            ' or . = '
                Daftar
            ')]</value>
      <webElementGuid>ad8cb636-b504-454e-bfc4-6ea81be9bd0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
