<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. NPWP Perusahaan_TxtNoNPWPPTCV</name>
   <tag></tag>
   <elementGuidId>8c53c14e-9190-4d2a-abc5-c61c64e32ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TxtNoNPWPPTCV']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TxtNoNPWPPTCV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f7a90df-fe38-4262-8070-a13824687d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field-input form-input-number2-az filled-requirement-legalitasPTCV</value>
      <webElementGuid>f01f781e-55d5-4478-bd81-c9affc26b196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TxtNoNPWPPTCV</value>
      <webElementGuid>cb156764-3f0c-4793-9c71-eca785cd10ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b066a770-4073-49b1-86e6-0ba41c372a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>0a31236a-c790-4c1e-b3e0-86a0d3f709e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Min. 15 digit NPWP perusahaan</value>
      <webElementGuid>edc9264c-86ae-420a-be4f-53e9a75bd1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TxtNoNPWPPTCV&quot;)</value>
      <webElementGuid>bfe860a5-efc9-40f1-8e25-ed05194b75e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TxtNoNPWPPTCV']</value>
      <webElementGuid>1bd4db8a-5a3e-4300-ad74-fa2cff36dc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerNoNPWP']/input</value>
      <webElementGuid>81131729-8341-4a18-8ab8-9a6b522cb898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>c9756445-f137-4345-b6ad-7abc677890d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TxtNoNPWPPTCV' and @type = 'text' and @placeholder = 'Min. 15 digit NPWP perusahaan']</value>
      <webElementGuid>0d400990-a27f-4f92-a5f0-d7501c248a3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
