<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sisa Kuota_radio_pasang_ku</name>
   <tag></tag>
   <elementGuidId>b8726530-3711-4878-bb0b-fd0677b42377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radio_pasang_ku&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radio_pasang_ku']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81f17020-135b-4c7b-b91d-7c202eb38625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>36925ff4-c319-4963-b944-a675531714b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>40574</value>
      <webElementGuid>99cd4acc-9760-4c8e-9f69-88e7d9770cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio_pasang_ku</value>
      <webElementGuid>a9bc7522-aba2-4328-bdb7-d234d782ffe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-6</value>
      <webElementGuid>786a9c0a-706e-4760-bcf4-76ef8f6f5734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;bg-menu-big&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;alertfe&quot;]/div[@class=&quot;alert-custom&quot;]/div[@class=&quot;body-alert&quot;]/div[@class=&quot;isi-body&quot;]/div[@class=&quot;bdr-12 bdr-86&quot;]/div[@class=&quot;isi-pilih-paket&quot;]/div[@class=&quot;ff-medium fc-86 fs-14 d-flex flex-row&quot;]/div[@class=&quot;align-items-center d-flex&quot;]/input[@class=&quot;mr-6&quot;]</value>
      <webElementGuid>432ae569-c35c-4f7d-89d4-fbebb5dd5fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radio_pasang_ku']</value>
      <webElementGuid>be3452f6-db82-45ed-80af-ba898a62af01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c318cf7d-fb2d-4724-8904-40250f65eebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio_pasang_ku']</value>
      <webElementGuid>0cf9a494-6b07-4600-aec5-f66899aa6356</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
